// Code generated by ent, DO NOT EDIT.

package subscriptionplanmodel

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// PlanID applies equality check predicate on the "plan_id" field. It's identical to PlanIDEQ.
func PlanID(v int64) predicate.SubscriptionPlanModel {
	return predicate.SubscriptionPlanModel(sql.FieldEQ(FieldPlanID, v))
}

// EntryID applies equality check predicate on the "entry_id" field. It's identical to EntryIDEQ.
func EntryID(v int64) predicate.SubscriptionPlanModel {
	return predicate.SubscriptionPlanModel(sql.FieldEQ(FieldEntryID, v))
}

// PlanIDEQ applies the EQ predicate on the "plan_id" field.
func PlanIDEQ(v int64) predicate.SubscriptionPlanModel {
	return predicate.SubscriptionPlanModel(sql.FieldEQ(FieldPlanID, v))
}

// PlanIDNEQ applies the NEQ predicate on the "plan_id" field.
func PlanIDNEQ(v int64) predicate.SubscriptionPlanModel {
	return predicate.SubscriptionPlanModel(sql.FieldNEQ(FieldPlanID, v))
}

// PlanIDIn applies the In predicate on the "plan_id" field.
func PlanIDIn(vs ...int64) predicate.SubscriptionPlanModel {
	return predicate.SubscriptionPlanModel(sql.FieldIn(FieldPlanID, vs...))
}

// PlanIDNotIn applies the NotIn predicate on the "plan_id" field.
func PlanIDNotIn(vs ...int64) predicate.SubscriptionPlanModel {
	return predicate.SubscriptionPlanModel(sql.FieldNotIn(FieldPlanID, vs...))
}

// EntryIDEQ applies the EQ predicate on the "entry_id" field.
func EntryIDEQ(v int64) predicate.SubscriptionPlanModel {
	return predicate.SubscriptionPlanModel(sql.FieldEQ(FieldEntryID, v))
}

// EntryIDNEQ applies the NEQ predicate on the "entry_id" field.
func EntryIDNEQ(v int64) predicate.SubscriptionPlanModel {
	return predicate.SubscriptionPlanModel(sql.FieldNEQ(FieldEntryID, v))
}

// EntryIDIn applies the In predicate on the "entry_id" field.
func EntryIDIn(vs ...int64) predicate.SubscriptionPlanModel {
	return predicate.SubscriptionPlanModel(sql.FieldIn(FieldEntryID, vs...))
}

// EntryIDNotIn applies the NotIn predicate on the "entry_id" field.
func EntryIDNotIn(vs ...int64) predicate.SubscriptionPlanModel {
	return predicate.SubscriptionPlanModel(sql.FieldNotIn(FieldEntryID, vs...))
}

// HasPlan applies the HasEdge predicate on the "plan" edge.
func HasPlan() predicate.SubscriptionPlanModel {
	return predicate.SubscriptionPlanModel(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, PlanColumn),
			sqlgraph.Edge(sqlgraph.M2O, false, PlanTable, PlanColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPlanWith applies the HasEdge predicate on the "plan" edge with a given conditions (other predicates).
func HasPlanWith(preds ...predicate.SubscriptionPlan) predicate.SubscriptionPlanModel {
	return predicate.SubscriptionPlanModel(func(s *sql.Selector) {
		step := newPlanStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasEntry applies the HasEdge predicate on the "entry" edge.
func HasEntry() predicate.SubscriptionPlanModel {
	return predicate.SubscriptionPlanModel(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, EntryColumn),
			sqlgraph.Edge(sqlgraph.M2O, false, EntryTable, EntryColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEntryWith applies the HasEdge predicate on the "entry" edge with a given conditions (other predicates).
func HasEntryWith(preds ...predicate.ModelCatalogEntry) predicate.SubscriptionPlanModel {
	return predicate.SubscriptionPlanModel(func(s *sql.Selector) {
		step := newEntryStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SubscriptionPlanModel) predicate.SubscriptionPlanModel {
	return predicate.SubscriptionPlanModel(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SubscriptionPlanModel) predicate.SubscriptionPlanModel {
	return predicate.SubscriptionPlanModel(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SubscriptionPlanModel) predicate.SubscriptionPlanModel {
	return predicate.SubscriptionPlanModel(sql.NotPredicates(p))
}
