// Code generated by ent, DO NOT EDIT.

package modelcatalogbinding

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the modelcatalogbinding type in the database.
	Label = "model_catalog_binding"
	// FieldEntryID holds the string denoting the entry_id field in the database.
	FieldEntryID = "entry_id"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldPriority holds the string denoting the priority field in the database.
	FieldPriority = "priority"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeEntry holds the string denoting the entry edge name in mutations.
	EdgeEntry = "entry"
	// EdgeAccount holds the string denoting the account edge name in mutations.
	EdgeAccount = "account"
	// ModelCatalogEntryFieldID holds the string denoting the ID field of the ModelCatalogEntry.
	ModelCatalogEntryFieldID = "id"
	// AccountFieldID holds the string denoting the ID field of the Account.
	AccountFieldID = "id"
	// Table holds the table name of the modelcatalogbinding in the database.
	Table = "model_catalog_bindings"
	// EntryTable is the table that holds the entry relation/edge.
	EntryTable = "model_catalog_bindings"
	// EntryInverseTable is the table name for the ModelCatalogEntry entity.
	// It exists in this package in order to avoid circular dependency with the "modelcatalogentry" package.
	EntryInverseTable = "model_catalog_entries"
	// EntryColumn is the table column denoting the entry relation/edge.
	EntryColumn = "entry_id"
	// AccountTable is the table that holds the account relation/edge.
	AccountTable = "model_catalog_bindings"
	// AccountInverseTable is the table name for the Account entity.
	// It exists in this package in order to avoid circular dependency with the "account" package.
	AccountInverseTable = "accounts"
	// AccountColumn is the table column denoting the account relation/edge.
	AccountColumn = "account_id"
)

// Columns holds all SQL columns for modelcatalogbinding fields.
var Columns = []string{
	FieldEntryID,
	FieldAccountID,
	FieldPriority,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the ModelCatalogBinding queries.
type OrderOption func(*sql.Selector)

// ByEntryID orders the results by the entry_id field.
func ByEntryID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEntryID, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByPriority orders the results by the priority field.
func ByPriority(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPriority, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByEntryField orders the results by entry field.
func ByEntryField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEntryStep(), sql.OrderByField(field, opts...))
	}
}

// ByAccountField orders the results by account field.
func ByAccountField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAccountStep(), sql.OrderByField(field, opts...))
	}
}
func newEntryStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, EntryColumn),
		sqlgraph.To(EntryInverseTable, ModelCatalogEntryFieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, EntryTable, EntryColumn),
	)
}
func newAccountStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, AccountColumn),
		sqlgraph.To(AccountInverseTable, AccountFieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, AccountTable, AccountColumn),
	)
}
