// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/modelcatalogbinding"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ModelCatalogBindingDelete is the builder for deleting a ModelCatalogBinding entity.
type ModelCatalogBindingDelete struct {
	config
	hooks    []Hook
	mutation *ModelCatalogBindingMutation
}

// Where appends a list predicates to the ModelCatalogBindingDelete builder.
func (_d *ModelCatalogBindingDelete) Where(ps ...predicate.ModelCatalogBinding) *ModelCatalogBindingDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ModelCatalogBindingDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ModelCatalogBindingDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ModelCatalogBindingDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(modelcatalogbinding.Table, nil)
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ModelCatalogBindingDeleteOne is the builder for deleting a single ModelCatalogBinding entity.
type ModelCatalogBindingDeleteOne struct {
	_d *ModelCatalogBindingDelete
}

// Where appends a list predicates to the ModelCatalogBindingDelete builder.
func (_d *ModelCatalogBindingDeleteOne) Where(ps ...predicate.ModelCatalogBinding) *ModelCatalogBindingDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ModelCatalogBindingDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{modelcatalogbinding.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ModelCatalogBindingDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
