// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/modelcatalogentry"
	"github.com/Wei-Shaw/sub2api/internal/domain"
)

// ModelCatalogEntry is the model entity for the ModelCatalogEntry schema.
type ModelCatalogEntry struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Canonical model identifier; unique case-insensitively.
	ModelID string `json:"model_id,omitempty"`
	// Human-facing name; empty means show model_id.
	DisplayName string `json:"display_name,omitempty"`
	// Vendor that owns the model (anthropic/openai/gemini/xai/...); empty means unknown.
	Vendor string `json:"vendor,omitempty"`
	// Upstream protocols the model speaks: anthropic/chat_completions/responses/gemini.
	Protocols []string `json:"protocols,omitempty"`
	// token / per_request / image / video.
	BillingMode string `json:"billing_mode,omitempty"`
	// listed = 上架（用户可见且可调用）; unlisted = 下架。
	Status string `json:"status,omitempty"`
	// seed = 播种器维护，可被重新播种刷新; admin = 管理员维护，播种器不再覆盖。
	ManagedBy string `json:"managed_by,omitempty"`
	// InputPrice holds the value of the "input_price" field.
	InputPrice *float64 `json:"input_price,omitempty"`
	// OutputPrice holds the value of the "output_price" field.
	OutputPrice *float64 `json:"output_price,omitempty"`
	// CacheWritePrice holds the value of the "cache_write_price" field.
	CacheWritePrice *float64 `json:"cache_write_price,omitempty"`
	// CacheWrite1hPrice holds the value of the "cache_write_1h_price" field.
	CacheWrite1hPrice *float64 `json:"cache_write_1h_price,omitempty"`
	// CacheReadPrice holds the value of the "cache_read_price" field.
	CacheReadPrice *float64 `json:"cache_read_price,omitempty"`
	// ImageInputPrice holds the value of the "image_input_price" field.
	ImageInputPrice *float64 `json:"image_input_price,omitempty"`
	// ImageOutputPrice holds the value of the "image_output_price" field.
	ImageOutputPrice *float64 `json:"image_output_price,omitempty"`
	// ImageCacheReadPrice holds the value of the "image_cache_read_price" field.
	ImageCacheReadPrice *float64 `json:"image_cache_read_price,omitempty"`
	// AudioInputPrice holds the value of the "audio_input_price" field.
	AudioInputPrice *float64 `json:"audio_input_price,omitempty"`
	// AudioOutputPrice holds the value of the "audio_output_price" field.
	AudioOutputPrice *float64 `json:"audio_output_price,omitempty"`
	// PerRequestPrice holds the value of the "per_request_price" field.
	PerRequestPrice *float64 `json:"per_request_price,omitempty"`
	// SearchPricePerCall holds the value of the "search_price_per_call" field.
	SearchPricePerCall *float64 `json:"search_price_per_call,omitempty"`
	// XPostPrice holds the value of the "x_post_price" field.
	XPostPrice *float64 `json:"x_post_price,omitempty"`
	// XUserPrice holds the value of the "x_user_price" field.
	XUserPrice *float64 `json:"x_user_price,omitempty"`
	// MaxReasoningEffortMultiplier holds the value of the "max_reasoning_effort_multiplier" field.
	MaxReasoningEffortMultiplier *float64 `json:"max_reasoning_effort_multiplier,omitempty"`
	// SalePrices holds the value of the "sale_prices" field.
	SalePrices domain.CatalogSalePrices `json:"sale_prices,omitempty"`
	// Notes holds the value of the "notes" field.
	Notes *string `json:"notes,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ModelCatalogEntryQuery when eager-loading is set.
	Edges        ModelCatalogEntryEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ModelCatalogEntryEdges holds the relations/edges for other nodes in the graph.
type ModelCatalogEntryEdges struct {
	// Accounts holds the value of the accounts edge.
	Accounts []*Account `json:"accounts,omitempty"`
	// SubscriptionPlans holds the value of the subscription_plans edge.
	SubscriptionPlans []*SubscriptionPlan `json:"subscription_plans,omitempty"`
	// Bindings holds the value of the bindings edge.
	Bindings []*ModelCatalogBinding `json:"bindings,omitempty"`
	// PlanModels holds the value of the plan_models edge.
	PlanModels []*SubscriptionPlanModel `json:"plan_models,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// AccountsOrErr returns the Accounts value or an error if the edge
// was not loaded in eager-loading.
func (e ModelCatalogEntryEdges) AccountsOrErr() ([]*Account, error) {
	if e.loadedTypes[0] {
		return e.Accounts, nil
	}
	return nil, &NotLoadedError{edge: "accounts"}
}

// SubscriptionPlansOrErr returns the SubscriptionPlans value or an error if the edge
// was not loaded in eager-loading.
func (e ModelCatalogEntryEdges) SubscriptionPlansOrErr() ([]*SubscriptionPlan, error) {
	if e.loadedTypes[1] {
		return e.SubscriptionPlans, nil
	}
	return nil, &NotLoadedError{edge: "subscription_plans"}
}

// BindingsOrErr returns the Bindings value or an error if the edge
// was not loaded in eager-loading.
func (e ModelCatalogEntryEdges) BindingsOrErr() ([]*ModelCatalogBinding, error) {
	if e.loadedTypes[2] {
		return e.Bindings, nil
	}
	return nil, &NotLoadedError{edge: "bindings"}
}

// PlanModelsOrErr returns the PlanModels value or an error if the edge
// was not loaded in eager-loading.
func (e ModelCatalogEntryEdges) PlanModelsOrErr() ([]*SubscriptionPlanModel, error) {
	if e.loadedTypes[3] {
		return e.PlanModels, nil
	}
	return nil, &NotLoadedError{edge: "plan_models"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ModelCatalogEntry) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case modelcatalogentry.FieldProtocols, modelcatalogentry.FieldSalePrices:
			values[i] = new([]byte)
		case modelcatalogentry.FieldInputPrice, modelcatalogentry.FieldOutputPrice, modelcatalogentry.FieldCacheWritePrice, modelcatalogentry.FieldCacheWrite1hPrice, modelcatalogentry.FieldCacheReadPrice, modelcatalogentry.FieldImageInputPrice, modelcatalogentry.FieldImageOutputPrice, modelcatalogentry.FieldImageCacheReadPrice, modelcatalogentry.FieldAudioInputPrice, modelcatalogentry.FieldAudioOutputPrice, modelcatalogentry.FieldPerRequestPrice, modelcatalogentry.FieldSearchPricePerCall, modelcatalogentry.FieldXPostPrice, modelcatalogentry.FieldXUserPrice, modelcatalogentry.FieldMaxReasoningEffortMultiplier:
			values[i] = new(sql.NullFloat64)
		case modelcatalogentry.FieldID:
			values[i] = new(sql.NullInt64)
		case modelcatalogentry.FieldModelID, modelcatalogentry.FieldDisplayName, modelcatalogentry.FieldVendor, modelcatalogentry.FieldBillingMode, modelcatalogentry.FieldStatus, modelcatalogentry.FieldManagedBy, modelcatalogentry.FieldNotes:
			values[i] = new(sql.NullString)
		case modelcatalogentry.FieldCreatedAt, modelcatalogentry.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ModelCatalogEntry fields.
func (_m *ModelCatalogEntry) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case modelcatalogentry.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case modelcatalogentry.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case modelcatalogentry.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case modelcatalogentry.FieldModelID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model_id", values[i])
			} else if value.Valid {
				_m.ModelID = value.String
			}
		case modelcatalogentry.FieldDisplayName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field display_name", values[i])
			} else if value.Valid {
				_m.DisplayName = value.String
			}
		case modelcatalogentry.FieldVendor:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field vendor", values[i])
			} else if value.Valid {
				_m.Vendor = value.String
			}
		case modelcatalogentry.FieldProtocols:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field protocols", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Protocols); err != nil {
					return fmt.Errorf("unmarshal field protocols: %w", err)
				}
			}
		case modelcatalogentry.FieldBillingMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field billing_mode", values[i])
			} else if value.Valid {
				_m.BillingMode = value.String
			}
		case modelcatalogentry.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case modelcatalogentry.FieldManagedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field managed_by", values[i])
			} else if value.Valid {
				_m.ManagedBy = value.String
			}
		case modelcatalogentry.FieldInputPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field input_price", values[i])
			} else if value.Valid {
				_m.InputPrice = new(float64)
				*_m.InputPrice = value.Float64
			}
		case modelcatalogentry.FieldOutputPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field output_price", values[i])
			} else if value.Valid {
				_m.OutputPrice = new(float64)
				*_m.OutputPrice = value.Float64
			}
		case modelcatalogentry.FieldCacheWritePrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field cache_write_price", values[i])
			} else if value.Valid {
				_m.CacheWritePrice = new(float64)
				*_m.CacheWritePrice = value.Float64
			}
		case modelcatalogentry.FieldCacheWrite1hPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field cache_write_1h_price", values[i])
			} else if value.Valid {
				_m.CacheWrite1hPrice = new(float64)
				*_m.CacheWrite1hPrice = value.Float64
			}
		case modelcatalogentry.FieldCacheReadPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field cache_read_price", values[i])
			} else if value.Valid {
				_m.CacheReadPrice = new(float64)
				*_m.CacheReadPrice = value.Float64
			}
		case modelcatalogentry.FieldImageInputPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field image_input_price", values[i])
			} else if value.Valid {
				_m.ImageInputPrice = new(float64)
				*_m.ImageInputPrice = value.Float64
			}
		case modelcatalogentry.FieldImageOutputPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field image_output_price", values[i])
			} else if value.Valid {
				_m.ImageOutputPrice = new(float64)
				*_m.ImageOutputPrice = value.Float64
			}
		case modelcatalogentry.FieldImageCacheReadPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field image_cache_read_price", values[i])
			} else if value.Valid {
				_m.ImageCacheReadPrice = new(float64)
				*_m.ImageCacheReadPrice = value.Float64
			}
		case modelcatalogentry.FieldAudioInputPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field audio_input_price", values[i])
			} else if value.Valid {
				_m.AudioInputPrice = new(float64)
				*_m.AudioInputPrice = value.Float64
			}
		case modelcatalogentry.FieldAudioOutputPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field audio_output_price", values[i])
			} else if value.Valid {
				_m.AudioOutputPrice = new(float64)
				*_m.AudioOutputPrice = value.Float64
			}
		case modelcatalogentry.FieldPerRequestPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field per_request_price", values[i])
			} else if value.Valid {
				_m.PerRequestPrice = new(float64)
				*_m.PerRequestPrice = value.Float64
			}
		case modelcatalogentry.FieldSearchPricePerCall:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field search_price_per_call", values[i])
			} else if value.Valid {
				_m.SearchPricePerCall = new(float64)
				*_m.SearchPricePerCall = value.Float64
			}
		case modelcatalogentry.FieldXPostPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field x_post_price", values[i])
			} else if value.Valid {
				_m.XPostPrice = new(float64)
				*_m.XPostPrice = value.Float64
			}
		case modelcatalogentry.FieldXUserPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field x_user_price", values[i])
			} else if value.Valid {
				_m.XUserPrice = new(float64)
				*_m.XUserPrice = value.Float64
			}
		case modelcatalogentry.FieldMaxReasoningEffortMultiplier:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field max_reasoning_effort_multiplier", values[i])
			} else if value.Valid {
				_m.MaxReasoningEffortMultiplier = new(float64)
				*_m.MaxReasoningEffortMultiplier = value.Float64
			}
		case modelcatalogentry.FieldSalePrices:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field sale_prices", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.SalePrices); err != nil {
					return fmt.Errorf("unmarshal field sale_prices: %w", err)
				}
			}
		case modelcatalogentry.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = new(string)
				*_m.Notes = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ModelCatalogEntry.
// This includes values selected through modifiers, order, etc.
func (_m *ModelCatalogEntry) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAccounts queries the "accounts" edge of the ModelCatalogEntry entity.
func (_m *ModelCatalogEntry) QueryAccounts() *AccountQuery {
	return NewModelCatalogEntryClient(_m.config).QueryAccounts(_m)
}

// QuerySubscriptionPlans queries the "subscription_plans" edge of the ModelCatalogEntry entity.
func (_m *ModelCatalogEntry) QuerySubscriptionPlans() *SubscriptionPlanQuery {
	return NewModelCatalogEntryClient(_m.config).QuerySubscriptionPlans(_m)
}

// QueryBindings queries the "bindings" edge of the ModelCatalogEntry entity.
func (_m *ModelCatalogEntry) QueryBindings() *ModelCatalogBindingQuery {
	return NewModelCatalogEntryClient(_m.config).QueryBindings(_m)
}

// QueryPlanModels queries the "plan_models" edge of the ModelCatalogEntry entity.
func (_m *ModelCatalogEntry) QueryPlanModels() *SubscriptionPlanModelQuery {
	return NewModelCatalogEntryClient(_m.config).QueryPlanModels(_m)
}

// Update returns a builder for updating this ModelCatalogEntry.
// Note that you need to call ModelCatalogEntry.Unwrap() before calling this method if this ModelCatalogEntry
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ModelCatalogEntry) Update() *ModelCatalogEntryUpdateOne {
	return NewModelCatalogEntryClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ModelCatalogEntry entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ModelCatalogEntry) Unwrap() *ModelCatalogEntry {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ModelCatalogEntry is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ModelCatalogEntry) String() string {
	var builder strings.Builder
	builder.WriteString("ModelCatalogEntry(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("model_id=")
	builder.WriteString(_m.ModelID)
	builder.WriteString(", ")
	builder.WriteString("display_name=")
	builder.WriteString(_m.DisplayName)
	builder.WriteString(", ")
	builder.WriteString("vendor=")
	builder.WriteString(_m.Vendor)
	builder.WriteString(", ")
	builder.WriteString("protocols=")
	builder.WriteString(fmt.Sprintf("%v", _m.Protocols))
	builder.WriteString(", ")
	builder.WriteString("billing_mode=")
	builder.WriteString(_m.BillingMode)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("managed_by=")
	builder.WriteString(_m.ManagedBy)
	builder.WriteString(", ")
	if v := _m.InputPrice; v != nil {
		builder.WriteString("input_price=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.OutputPrice; v != nil {
		builder.WriteString("output_price=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.CacheWritePrice; v != nil {
		builder.WriteString("cache_write_price=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.CacheWrite1hPrice; v != nil {
		builder.WriteString("cache_write_1h_price=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.CacheReadPrice; v != nil {
		builder.WriteString("cache_read_price=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ImageInputPrice; v != nil {
		builder.WriteString("image_input_price=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ImageOutputPrice; v != nil {
		builder.WriteString("image_output_price=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ImageCacheReadPrice; v != nil {
		builder.WriteString("image_cache_read_price=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.AudioInputPrice; v != nil {
		builder.WriteString("audio_input_price=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.AudioOutputPrice; v != nil {
		builder.WriteString("audio_output_price=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.PerRequestPrice; v != nil {
		builder.WriteString("per_request_price=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.SearchPricePerCall; v != nil {
		builder.WriteString("search_price_per_call=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.XPostPrice; v != nil {
		builder.WriteString("x_post_price=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.XUserPrice; v != nil {
		builder.WriteString("x_user_price=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.MaxReasoningEffortMultiplier; v != nil {
		builder.WriteString("max_reasoning_effort_multiplier=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("sale_prices=")
	builder.WriteString(fmt.Sprintf("%v", _m.SalePrices))
	builder.WriteString(", ")
	if v := _m.Notes; v != nil {
		builder.WriteString("notes=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// ModelCatalogEntries is a parsable slice of ModelCatalogEntry.
type ModelCatalogEntries []*ModelCatalogEntry
