// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/modelcatalogpriceinterval"
)

// ModelCatalogPriceInterval is the model entity for the ModelCatalogPriceInterval schema.
type ModelCatalogPriceInterval struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 指向 model_catalog_entries.id。
	EntryID int64 `json:"entry_id,omitempty"`
	// MinTokens holds the value of the "min_tokens" field.
	MinTokens int `json:"min_tokens,omitempty"`
	// nil 表示无上界；无上界区间必须是最后一档。
	MaxTokens *int `json:"max_tokens,omitempty"`
	// 按次 / 图片 / 视频计费的档位标签，如 1K / 2K / HD。
	TierLabel string `json:"tier_label,omitempty"`
	// InputPrice holds the value of the "input_price" field.
	InputPrice *float64 `json:"input_price,omitempty"`
	// OutputPrice holds the value of the "output_price" field.
	OutputPrice *float64 `json:"output_price,omitempty"`
	// CacheWritePrice holds the value of the "cache_write_price" field.
	CacheWritePrice *float64 `json:"cache_write_price,omitempty"`
	// CacheWrite1hPrice holds the value of the "cache_write_1h_price" field.
	CacheWrite1hPrice *float64 `json:"cache_write_1h_price,omitempty"`
	// CacheReadPrice holds the value of the "cache_read_price" field.
	CacheReadPrice *float64 `json:"cache_read_price,omitempty"`
	// PerRequestPrice holds the value of the "per_request_price" field.
	PerRequestPrice *float64 `json:"per_request_price,omitempty"`
	// InputMultiplier holds the value of the "input_multiplier" field.
	InputMultiplier *float64 `json:"input_multiplier,omitempty"`
	// OutputMultiplier holds the value of the "output_multiplier" field.
	OutputMultiplier *float64 `json:"output_multiplier,omitempty"`
	// CacheWriteMultiplier holds the value of the "cache_write_multiplier" field.
	CacheWriteMultiplier *float64 `json:"cache_write_multiplier,omitempty"`
	// CacheReadMultiplier holds the value of the "cache_read_multiplier" field.
	CacheReadMultiplier *float64 `json:"cache_read_multiplier,omitempty"`
	// SortOrder holds the value of the "sort_order" field.
	SortOrder    int `json:"sort_order,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ModelCatalogPriceInterval) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case modelcatalogpriceinterval.FieldInputPrice, modelcatalogpriceinterval.FieldOutputPrice, modelcatalogpriceinterval.FieldCacheWritePrice, modelcatalogpriceinterval.FieldCacheWrite1hPrice, modelcatalogpriceinterval.FieldCacheReadPrice, modelcatalogpriceinterval.FieldPerRequestPrice, modelcatalogpriceinterval.FieldInputMultiplier, modelcatalogpriceinterval.FieldOutputMultiplier, modelcatalogpriceinterval.FieldCacheWriteMultiplier, modelcatalogpriceinterval.FieldCacheReadMultiplier:
			values[i] = new(sql.NullFloat64)
		case modelcatalogpriceinterval.FieldID, modelcatalogpriceinterval.FieldEntryID, modelcatalogpriceinterval.FieldMinTokens, modelcatalogpriceinterval.FieldMaxTokens, modelcatalogpriceinterval.FieldSortOrder:
			values[i] = new(sql.NullInt64)
		case modelcatalogpriceinterval.FieldTierLabel:
			values[i] = new(sql.NullString)
		case modelcatalogpriceinterval.FieldCreatedAt, modelcatalogpriceinterval.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ModelCatalogPriceInterval fields.
func (_m *ModelCatalogPriceInterval) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case modelcatalogpriceinterval.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case modelcatalogpriceinterval.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case modelcatalogpriceinterval.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case modelcatalogpriceinterval.FieldEntryID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field entry_id", values[i])
			} else if value.Valid {
				_m.EntryID = value.Int64
			}
		case modelcatalogpriceinterval.FieldMinTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field min_tokens", values[i])
			} else if value.Valid {
				_m.MinTokens = int(value.Int64)
			}
		case modelcatalogpriceinterval.FieldMaxTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_tokens", values[i])
			} else if value.Valid {
				_m.MaxTokens = new(int)
				*_m.MaxTokens = int(value.Int64)
			}
		case modelcatalogpriceinterval.FieldTierLabel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tier_label", values[i])
			} else if value.Valid {
				_m.TierLabel = value.String
			}
		case modelcatalogpriceinterval.FieldInputPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field input_price", values[i])
			} else if value.Valid {
				_m.InputPrice = new(float64)
				*_m.InputPrice = value.Float64
			}
		case modelcatalogpriceinterval.FieldOutputPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field output_price", values[i])
			} else if value.Valid {
				_m.OutputPrice = new(float64)
				*_m.OutputPrice = value.Float64
			}
		case modelcatalogpriceinterval.FieldCacheWritePrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field cache_write_price", values[i])
			} else if value.Valid {
				_m.CacheWritePrice = new(float64)
				*_m.CacheWritePrice = value.Float64
			}
		case modelcatalogpriceinterval.FieldCacheWrite1hPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field cache_write_1h_price", values[i])
			} else if value.Valid {
				_m.CacheWrite1hPrice = new(float64)
				*_m.CacheWrite1hPrice = value.Float64
			}
		case modelcatalogpriceinterval.FieldCacheReadPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field cache_read_price", values[i])
			} else if value.Valid {
				_m.CacheReadPrice = new(float64)
				*_m.CacheReadPrice = value.Float64
			}
		case modelcatalogpriceinterval.FieldPerRequestPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field per_request_price", values[i])
			} else if value.Valid {
				_m.PerRequestPrice = new(float64)
				*_m.PerRequestPrice = value.Float64
			}
		case modelcatalogpriceinterval.FieldInputMultiplier:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field input_multiplier", values[i])
			} else if value.Valid {
				_m.InputMultiplier = new(float64)
				*_m.InputMultiplier = value.Float64
			}
		case modelcatalogpriceinterval.FieldOutputMultiplier:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field output_multiplier", values[i])
			} else if value.Valid {
				_m.OutputMultiplier = new(float64)
				*_m.OutputMultiplier = value.Float64
			}
		case modelcatalogpriceinterval.FieldCacheWriteMultiplier:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field cache_write_multiplier", values[i])
			} else if value.Valid {
				_m.CacheWriteMultiplier = new(float64)
				*_m.CacheWriteMultiplier = value.Float64
			}
		case modelcatalogpriceinterval.FieldCacheReadMultiplier:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field cache_read_multiplier", values[i])
			} else if value.Valid {
				_m.CacheReadMultiplier = new(float64)
				*_m.CacheReadMultiplier = value.Float64
			}
		case modelcatalogpriceinterval.FieldSortOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort_order", values[i])
			} else if value.Valid {
				_m.SortOrder = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ModelCatalogPriceInterval.
// This includes values selected through modifiers, order, etc.
func (_m *ModelCatalogPriceInterval) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ModelCatalogPriceInterval.
// Note that you need to call ModelCatalogPriceInterval.Unwrap() before calling this method if this ModelCatalogPriceInterval
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ModelCatalogPriceInterval) Update() *ModelCatalogPriceIntervalUpdateOne {
	return NewModelCatalogPriceIntervalClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ModelCatalogPriceInterval entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ModelCatalogPriceInterval) Unwrap() *ModelCatalogPriceInterval {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ModelCatalogPriceInterval is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ModelCatalogPriceInterval) String() string {
	var builder strings.Builder
	builder.WriteString("ModelCatalogPriceInterval(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("entry_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.EntryID))
	builder.WriteString(", ")
	builder.WriteString("min_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.MinTokens))
	builder.WriteString(", ")
	if v := _m.MaxTokens; v != nil {
		builder.WriteString("max_tokens=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("tier_label=")
	builder.WriteString(_m.TierLabel)
	builder.WriteString(", ")
	if v := _m.InputPrice; v != nil {
		builder.WriteString("input_price=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.OutputPrice; v != nil {
		builder.WriteString("output_price=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.CacheWritePrice; v != nil {
		builder.WriteString("cache_write_price=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.CacheWrite1hPrice; v != nil {
		builder.WriteString("cache_write_1h_price=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.CacheReadPrice; v != nil {
		builder.WriteString("cache_read_price=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.PerRequestPrice; v != nil {
		builder.WriteString("per_request_price=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.InputMultiplier; v != nil {
		builder.WriteString("input_multiplier=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.OutputMultiplier; v != nil {
		builder.WriteString("output_multiplier=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.CacheWriteMultiplier; v != nil {
		builder.WriteString("cache_write_multiplier=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.CacheReadMultiplier; v != nil {
		builder.WriteString("cache_read_multiplier=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("sort_order=")
	builder.WriteString(fmt.Sprintf("%v", _m.SortOrder))
	builder.WriteByte(')')
	return builder.String()
}

// ModelCatalogPriceIntervals is a parsable slice of ModelCatalogPriceInterval.
type ModelCatalogPriceIntervals []*ModelCatalogPriceInterval
