// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/modelcatalogtimepricing"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ModelCatalogTimePricingDelete is the builder for deleting a ModelCatalogTimePricing entity.
type ModelCatalogTimePricingDelete struct {
	config
	hooks    []Hook
	mutation *ModelCatalogTimePricingMutation
}

// Where appends a list predicates to the ModelCatalogTimePricingDelete builder.
func (_d *ModelCatalogTimePricingDelete) Where(ps ...predicate.ModelCatalogTimePricing) *ModelCatalogTimePricingDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ModelCatalogTimePricingDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ModelCatalogTimePricingDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ModelCatalogTimePricingDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(modelcatalogtimepricing.Table, sqlgraph.NewFieldSpec(modelcatalogtimepricing.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ModelCatalogTimePricingDeleteOne is the builder for deleting a single ModelCatalogTimePricing entity.
type ModelCatalogTimePricingDeleteOne struct {
	_d *ModelCatalogTimePricingDelete
}

// Where appends a list predicates to the ModelCatalogTimePricingDelete builder.
func (_d *ModelCatalogTimePricingDeleteOne) Where(ps ...predicate.ModelCatalogTimePricing) *ModelCatalogTimePricingDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ModelCatalogTimePricingDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{modelcatalogtimepricing.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ModelCatalogTimePricingDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
