// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/modelcatalogbinding"
	"github.com/Wei-Shaw/sub2api/ent/modelcatalogentry"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/internal/domain"
)

// ModelCatalogBindingUpdate is the builder for updating ModelCatalogBinding entities.
type ModelCatalogBindingUpdate struct {
	config
	hooks    []Hook
	mutation *ModelCatalogBindingMutation
}

// Where appends a list predicates to the ModelCatalogBindingUpdate builder.
func (_u *ModelCatalogBindingUpdate) Where(ps ...predicate.ModelCatalogBinding) *ModelCatalogBindingUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetEntryID sets the "entry_id" field.
func (_u *ModelCatalogBindingUpdate) SetEntryID(v int64) *ModelCatalogBindingUpdate {
	_u.mutation.SetEntryID(v)
	return _u
}

// SetNillableEntryID sets the "entry_id" field if the given value is not nil.
func (_u *ModelCatalogBindingUpdate) SetNillableEntryID(v *int64) *ModelCatalogBindingUpdate {
	if v != nil {
		_u.SetEntryID(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *ModelCatalogBindingUpdate) SetAccountID(v int64) *ModelCatalogBindingUpdate {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *ModelCatalogBindingUpdate) SetNillableAccountID(v *int64) *ModelCatalogBindingUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetInputPrice sets the "input_price" field.
func (_u *ModelCatalogBindingUpdate) SetInputPrice(v float64) *ModelCatalogBindingUpdate {
	_u.mutation.ResetInputPrice()
	_u.mutation.SetInputPrice(v)
	return _u
}

// SetNillableInputPrice sets the "input_price" field if the given value is not nil.
func (_u *ModelCatalogBindingUpdate) SetNillableInputPrice(v *float64) *ModelCatalogBindingUpdate {
	if v != nil {
		_u.SetInputPrice(*v)
	}
	return _u
}

// AddInputPrice adds value to the "input_price" field.
func (_u *ModelCatalogBindingUpdate) AddInputPrice(v float64) *ModelCatalogBindingUpdate {
	_u.mutation.AddInputPrice(v)
	return _u
}

// SetOutputPrice sets the "output_price" field.
func (_u *ModelCatalogBindingUpdate) SetOutputPrice(v float64) *ModelCatalogBindingUpdate {
	_u.mutation.ResetOutputPrice()
	_u.mutation.SetOutputPrice(v)
	return _u
}

// SetNillableOutputPrice sets the "output_price" field if the given value is not nil.
func (_u *ModelCatalogBindingUpdate) SetNillableOutputPrice(v *float64) *ModelCatalogBindingUpdate {
	if v != nil {
		_u.SetOutputPrice(*v)
	}
	return _u
}

// AddOutputPrice adds value to the "output_price" field.
func (_u *ModelCatalogBindingUpdate) AddOutputPrice(v float64) *ModelCatalogBindingUpdate {
	_u.mutation.AddOutputPrice(v)
	return _u
}

// SetCacheWritePrice sets the "cache_write_price" field.
func (_u *ModelCatalogBindingUpdate) SetCacheWritePrice(v float64) *ModelCatalogBindingUpdate {
	_u.mutation.ResetCacheWritePrice()
	_u.mutation.SetCacheWritePrice(v)
	return _u
}

// SetNillableCacheWritePrice sets the "cache_write_price" field if the given value is not nil.
func (_u *ModelCatalogBindingUpdate) SetNillableCacheWritePrice(v *float64) *ModelCatalogBindingUpdate {
	if v != nil {
		_u.SetCacheWritePrice(*v)
	}
	return _u
}

// AddCacheWritePrice adds value to the "cache_write_price" field.
func (_u *ModelCatalogBindingUpdate) AddCacheWritePrice(v float64) *ModelCatalogBindingUpdate {
	_u.mutation.AddCacheWritePrice(v)
	return _u
}

// ClearCacheWritePrice clears the value of the "cache_write_price" field.
func (_u *ModelCatalogBindingUpdate) ClearCacheWritePrice() *ModelCatalogBindingUpdate {
	_u.mutation.ClearCacheWritePrice()
	return _u
}

// SetCacheWrite1hPrice sets the "cache_write_1h_price" field.
func (_u *ModelCatalogBindingUpdate) SetCacheWrite1hPrice(v float64) *ModelCatalogBindingUpdate {
	_u.mutation.ResetCacheWrite1hPrice()
	_u.mutation.SetCacheWrite1hPrice(v)
	return _u
}

// SetNillableCacheWrite1hPrice sets the "cache_write_1h_price" field if the given value is not nil.
func (_u *ModelCatalogBindingUpdate) SetNillableCacheWrite1hPrice(v *float64) *ModelCatalogBindingUpdate {
	if v != nil {
		_u.SetCacheWrite1hPrice(*v)
	}
	return _u
}

// AddCacheWrite1hPrice adds value to the "cache_write_1h_price" field.
func (_u *ModelCatalogBindingUpdate) AddCacheWrite1hPrice(v float64) *ModelCatalogBindingUpdate {
	_u.mutation.AddCacheWrite1hPrice(v)
	return _u
}

// ClearCacheWrite1hPrice clears the value of the "cache_write_1h_price" field.
func (_u *ModelCatalogBindingUpdate) ClearCacheWrite1hPrice() *ModelCatalogBindingUpdate {
	_u.mutation.ClearCacheWrite1hPrice()
	return _u
}

// SetCacheReadPrice sets the "cache_read_price" field.
func (_u *ModelCatalogBindingUpdate) SetCacheReadPrice(v float64) *ModelCatalogBindingUpdate {
	_u.mutation.ResetCacheReadPrice()
	_u.mutation.SetCacheReadPrice(v)
	return _u
}

// SetNillableCacheReadPrice sets the "cache_read_price" field if the given value is not nil.
func (_u *ModelCatalogBindingUpdate) SetNillableCacheReadPrice(v *float64) *ModelCatalogBindingUpdate {
	if v != nil {
		_u.SetCacheReadPrice(*v)
	}
	return _u
}

// AddCacheReadPrice adds value to the "cache_read_price" field.
func (_u *ModelCatalogBindingUpdate) AddCacheReadPrice(v float64) *ModelCatalogBindingUpdate {
	_u.mutation.AddCacheReadPrice(v)
	return _u
}

// ClearCacheReadPrice clears the value of the "cache_read_price" field.
func (_u *ModelCatalogBindingUpdate) ClearCacheReadPrice() *ModelCatalogBindingUpdate {
	_u.mutation.ClearCacheReadPrice()
	return _u
}

// SetPriceIntervals sets the "price_intervals" field.
func (_u *ModelCatalogBindingUpdate) SetPriceIntervals(v []domain.PriceSegment) *ModelCatalogBindingUpdate {
	_u.mutation.SetPriceIntervals(v)
	return _u
}

// AppendPriceIntervals appends value to the "price_intervals" field.
func (_u *ModelCatalogBindingUpdate) AppendPriceIntervals(v []domain.PriceSegment) *ModelCatalogBindingUpdate {
	_u.mutation.AppendPriceIntervals(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ModelCatalogBindingUpdate) SetUpdatedAt(v time.Time) *ModelCatalogBindingUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetEntry sets the "entry" edge to the ModelCatalogEntry entity.
func (_u *ModelCatalogBindingUpdate) SetEntry(v *ModelCatalogEntry) *ModelCatalogBindingUpdate {
	return _u.SetEntryID(v.ID)
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *ModelCatalogBindingUpdate) SetAccount(v *Account) *ModelCatalogBindingUpdate {
	return _u.SetAccountID(v.ID)
}

// Mutation returns the ModelCatalogBindingMutation object of the builder.
func (_u *ModelCatalogBindingUpdate) Mutation() *ModelCatalogBindingMutation {
	return _u.mutation
}

// ClearEntry clears the "entry" edge to the ModelCatalogEntry entity.
func (_u *ModelCatalogBindingUpdate) ClearEntry() *ModelCatalogBindingUpdate {
	_u.mutation.ClearEntry()
	return _u
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *ModelCatalogBindingUpdate) ClearAccount() *ModelCatalogBindingUpdate {
	_u.mutation.ClearAccount()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ModelCatalogBindingUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ModelCatalogBindingUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ModelCatalogBindingUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ModelCatalogBindingUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ModelCatalogBindingUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := modelcatalogbinding.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ModelCatalogBindingUpdate) check() error {
	if _u.mutation.EntryCleared() && len(_u.mutation.EntryIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ModelCatalogBinding.entry"`)
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ModelCatalogBinding.account"`)
	}
	return nil
}

func (_u *ModelCatalogBindingUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(modelcatalogbinding.Table, modelcatalogbinding.Columns, sqlgraph.NewFieldSpec(modelcatalogbinding.FieldEntryID, field.TypeInt64), sqlgraph.NewFieldSpec(modelcatalogbinding.FieldAccountID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.InputPrice(); ok {
		_spec.SetField(modelcatalogbinding.FieldInputPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedInputPrice(); ok {
		_spec.AddField(modelcatalogbinding.FieldInputPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.OutputPrice(); ok {
		_spec.SetField(modelcatalogbinding.FieldOutputPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOutputPrice(); ok {
		_spec.AddField(modelcatalogbinding.FieldOutputPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CacheWritePrice(); ok {
		_spec.SetField(modelcatalogbinding.FieldCacheWritePrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCacheWritePrice(); ok {
		_spec.AddField(modelcatalogbinding.FieldCacheWritePrice, field.TypeFloat64, value)
	}
	if _u.mutation.CacheWritePriceCleared() {
		_spec.ClearField(modelcatalogbinding.FieldCacheWritePrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.CacheWrite1hPrice(); ok {
		_spec.SetField(modelcatalogbinding.FieldCacheWrite1hPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCacheWrite1hPrice(); ok {
		_spec.AddField(modelcatalogbinding.FieldCacheWrite1hPrice, field.TypeFloat64, value)
	}
	if _u.mutation.CacheWrite1hPriceCleared() {
		_spec.ClearField(modelcatalogbinding.FieldCacheWrite1hPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.CacheReadPrice(); ok {
		_spec.SetField(modelcatalogbinding.FieldCacheReadPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCacheReadPrice(); ok {
		_spec.AddField(modelcatalogbinding.FieldCacheReadPrice, field.TypeFloat64, value)
	}
	if _u.mutation.CacheReadPriceCleared() {
		_spec.ClearField(modelcatalogbinding.FieldCacheReadPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.PriceIntervals(); ok {
		_spec.SetField(modelcatalogbinding.FieldPriceIntervals, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPriceIntervals(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, modelcatalogbinding.FieldPriceIntervals, value)
		})
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(modelcatalogbinding.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.EntryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   modelcatalogbinding.EntryTable,
			Columns: []string{modelcatalogbinding.EntryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelcatalogentry.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EntryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   modelcatalogbinding.EntryTable,
			Columns: []string{modelcatalogbinding.EntryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelcatalogentry.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   modelcatalogbinding.AccountTable,
			Columns: []string{modelcatalogbinding.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   modelcatalogbinding.AccountTable,
			Columns: []string{modelcatalogbinding.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{modelcatalogbinding.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ModelCatalogBindingUpdateOne is the builder for updating a single ModelCatalogBinding entity.
type ModelCatalogBindingUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ModelCatalogBindingMutation
}

// SetEntryID sets the "entry_id" field.
func (_u *ModelCatalogBindingUpdateOne) SetEntryID(v int64) *ModelCatalogBindingUpdateOne {
	_u.mutation.SetEntryID(v)
	return _u
}

// SetNillableEntryID sets the "entry_id" field if the given value is not nil.
func (_u *ModelCatalogBindingUpdateOne) SetNillableEntryID(v *int64) *ModelCatalogBindingUpdateOne {
	if v != nil {
		_u.SetEntryID(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *ModelCatalogBindingUpdateOne) SetAccountID(v int64) *ModelCatalogBindingUpdateOne {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *ModelCatalogBindingUpdateOne) SetNillableAccountID(v *int64) *ModelCatalogBindingUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetInputPrice sets the "input_price" field.
func (_u *ModelCatalogBindingUpdateOne) SetInputPrice(v float64) *ModelCatalogBindingUpdateOne {
	_u.mutation.ResetInputPrice()
	_u.mutation.SetInputPrice(v)
	return _u
}

// SetNillableInputPrice sets the "input_price" field if the given value is not nil.
func (_u *ModelCatalogBindingUpdateOne) SetNillableInputPrice(v *float64) *ModelCatalogBindingUpdateOne {
	if v != nil {
		_u.SetInputPrice(*v)
	}
	return _u
}

// AddInputPrice adds value to the "input_price" field.
func (_u *ModelCatalogBindingUpdateOne) AddInputPrice(v float64) *ModelCatalogBindingUpdateOne {
	_u.mutation.AddInputPrice(v)
	return _u
}

// SetOutputPrice sets the "output_price" field.
func (_u *ModelCatalogBindingUpdateOne) SetOutputPrice(v float64) *ModelCatalogBindingUpdateOne {
	_u.mutation.ResetOutputPrice()
	_u.mutation.SetOutputPrice(v)
	return _u
}

// SetNillableOutputPrice sets the "output_price" field if the given value is not nil.
func (_u *ModelCatalogBindingUpdateOne) SetNillableOutputPrice(v *float64) *ModelCatalogBindingUpdateOne {
	if v != nil {
		_u.SetOutputPrice(*v)
	}
	return _u
}

// AddOutputPrice adds value to the "output_price" field.
func (_u *ModelCatalogBindingUpdateOne) AddOutputPrice(v float64) *ModelCatalogBindingUpdateOne {
	_u.mutation.AddOutputPrice(v)
	return _u
}

// SetCacheWritePrice sets the "cache_write_price" field.
func (_u *ModelCatalogBindingUpdateOne) SetCacheWritePrice(v float64) *ModelCatalogBindingUpdateOne {
	_u.mutation.ResetCacheWritePrice()
	_u.mutation.SetCacheWritePrice(v)
	return _u
}

// SetNillableCacheWritePrice sets the "cache_write_price" field if the given value is not nil.
func (_u *ModelCatalogBindingUpdateOne) SetNillableCacheWritePrice(v *float64) *ModelCatalogBindingUpdateOne {
	if v != nil {
		_u.SetCacheWritePrice(*v)
	}
	return _u
}

// AddCacheWritePrice adds value to the "cache_write_price" field.
func (_u *ModelCatalogBindingUpdateOne) AddCacheWritePrice(v float64) *ModelCatalogBindingUpdateOne {
	_u.mutation.AddCacheWritePrice(v)
	return _u
}

// ClearCacheWritePrice clears the value of the "cache_write_price" field.
func (_u *ModelCatalogBindingUpdateOne) ClearCacheWritePrice() *ModelCatalogBindingUpdateOne {
	_u.mutation.ClearCacheWritePrice()
	return _u
}

// SetCacheWrite1hPrice sets the "cache_write_1h_price" field.
func (_u *ModelCatalogBindingUpdateOne) SetCacheWrite1hPrice(v float64) *ModelCatalogBindingUpdateOne {
	_u.mutation.ResetCacheWrite1hPrice()
	_u.mutation.SetCacheWrite1hPrice(v)
	return _u
}

// SetNillableCacheWrite1hPrice sets the "cache_write_1h_price" field if the given value is not nil.
func (_u *ModelCatalogBindingUpdateOne) SetNillableCacheWrite1hPrice(v *float64) *ModelCatalogBindingUpdateOne {
	if v != nil {
		_u.SetCacheWrite1hPrice(*v)
	}
	return _u
}

// AddCacheWrite1hPrice adds value to the "cache_write_1h_price" field.
func (_u *ModelCatalogBindingUpdateOne) AddCacheWrite1hPrice(v float64) *ModelCatalogBindingUpdateOne {
	_u.mutation.AddCacheWrite1hPrice(v)
	return _u
}

// ClearCacheWrite1hPrice clears the value of the "cache_write_1h_price" field.
func (_u *ModelCatalogBindingUpdateOne) ClearCacheWrite1hPrice() *ModelCatalogBindingUpdateOne {
	_u.mutation.ClearCacheWrite1hPrice()
	return _u
}

// SetCacheReadPrice sets the "cache_read_price" field.
func (_u *ModelCatalogBindingUpdateOne) SetCacheReadPrice(v float64) *ModelCatalogBindingUpdateOne {
	_u.mutation.ResetCacheReadPrice()
	_u.mutation.SetCacheReadPrice(v)
	return _u
}

// SetNillableCacheReadPrice sets the "cache_read_price" field if the given value is not nil.
func (_u *ModelCatalogBindingUpdateOne) SetNillableCacheReadPrice(v *float64) *ModelCatalogBindingUpdateOne {
	if v != nil {
		_u.SetCacheReadPrice(*v)
	}
	return _u
}

// AddCacheReadPrice adds value to the "cache_read_price" field.
func (_u *ModelCatalogBindingUpdateOne) AddCacheReadPrice(v float64) *ModelCatalogBindingUpdateOne {
	_u.mutation.AddCacheReadPrice(v)
	return _u
}

// ClearCacheReadPrice clears the value of the "cache_read_price" field.
func (_u *ModelCatalogBindingUpdateOne) ClearCacheReadPrice() *ModelCatalogBindingUpdateOne {
	_u.mutation.ClearCacheReadPrice()
	return _u
}

// SetPriceIntervals sets the "price_intervals" field.
func (_u *ModelCatalogBindingUpdateOne) SetPriceIntervals(v []domain.PriceSegment) *ModelCatalogBindingUpdateOne {
	_u.mutation.SetPriceIntervals(v)
	return _u
}

// AppendPriceIntervals appends value to the "price_intervals" field.
func (_u *ModelCatalogBindingUpdateOne) AppendPriceIntervals(v []domain.PriceSegment) *ModelCatalogBindingUpdateOne {
	_u.mutation.AppendPriceIntervals(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ModelCatalogBindingUpdateOne) SetUpdatedAt(v time.Time) *ModelCatalogBindingUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetEntry sets the "entry" edge to the ModelCatalogEntry entity.
func (_u *ModelCatalogBindingUpdateOne) SetEntry(v *ModelCatalogEntry) *ModelCatalogBindingUpdateOne {
	return _u.SetEntryID(v.ID)
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *ModelCatalogBindingUpdateOne) SetAccount(v *Account) *ModelCatalogBindingUpdateOne {
	return _u.SetAccountID(v.ID)
}

// Mutation returns the ModelCatalogBindingMutation object of the builder.
func (_u *ModelCatalogBindingUpdateOne) Mutation() *ModelCatalogBindingMutation {
	return _u.mutation
}

// ClearEntry clears the "entry" edge to the ModelCatalogEntry entity.
func (_u *ModelCatalogBindingUpdateOne) ClearEntry() *ModelCatalogBindingUpdateOne {
	_u.mutation.ClearEntry()
	return _u
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *ModelCatalogBindingUpdateOne) ClearAccount() *ModelCatalogBindingUpdateOne {
	_u.mutation.ClearAccount()
	return _u
}

// Where appends a list predicates to the ModelCatalogBindingUpdate builder.
func (_u *ModelCatalogBindingUpdateOne) Where(ps ...predicate.ModelCatalogBinding) *ModelCatalogBindingUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ModelCatalogBindingUpdateOne) Select(field string, fields ...string) *ModelCatalogBindingUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ModelCatalogBinding entity.
func (_u *ModelCatalogBindingUpdateOne) Save(ctx context.Context) (*ModelCatalogBinding, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ModelCatalogBindingUpdateOne) SaveX(ctx context.Context) *ModelCatalogBinding {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ModelCatalogBindingUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ModelCatalogBindingUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ModelCatalogBindingUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := modelcatalogbinding.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ModelCatalogBindingUpdateOne) check() error {
	if _u.mutation.EntryCleared() && len(_u.mutation.EntryIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ModelCatalogBinding.entry"`)
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ModelCatalogBinding.account"`)
	}
	return nil
}

func (_u *ModelCatalogBindingUpdateOne) sqlSave(ctx context.Context) (_node *ModelCatalogBinding, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(modelcatalogbinding.Table, modelcatalogbinding.Columns, sqlgraph.NewFieldSpec(modelcatalogbinding.FieldEntryID, field.TypeInt64), sqlgraph.NewFieldSpec(modelcatalogbinding.FieldAccountID, field.TypeInt64))
	if id, ok := _u.mutation.EntryID(); !ok {
		return nil, &ValidationError{Name: "entry_id", err: errors.New(`ent: missing "ModelCatalogBinding.entry_id" for update`)}
	} else {
		_spec.Node.CompositeID[0].Value = id
	}
	if id, ok := _u.mutation.AccountID(); !ok {
		return nil, &ValidationError{Name: "account_id", err: errors.New(`ent: missing "ModelCatalogBinding.account_id" for update`)}
	} else {
		_spec.Node.CompositeID[1].Value = id
	}
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, len(fields))
		for i, f := range fields {
			if !modelcatalogbinding.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			_spec.Node.Columns[i] = f
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.InputPrice(); ok {
		_spec.SetField(modelcatalogbinding.FieldInputPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedInputPrice(); ok {
		_spec.AddField(modelcatalogbinding.FieldInputPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.OutputPrice(); ok {
		_spec.SetField(modelcatalogbinding.FieldOutputPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOutputPrice(); ok {
		_spec.AddField(modelcatalogbinding.FieldOutputPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CacheWritePrice(); ok {
		_spec.SetField(modelcatalogbinding.FieldCacheWritePrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCacheWritePrice(); ok {
		_spec.AddField(modelcatalogbinding.FieldCacheWritePrice, field.TypeFloat64, value)
	}
	if _u.mutation.CacheWritePriceCleared() {
		_spec.ClearField(modelcatalogbinding.FieldCacheWritePrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.CacheWrite1hPrice(); ok {
		_spec.SetField(modelcatalogbinding.FieldCacheWrite1hPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCacheWrite1hPrice(); ok {
		_spec.AddField(modelcatalogbinding.FieldCacheWrite1hPrice, field.TypeFloat64, value)
	}
	if _u.mutation.CacheWrite1hPriceCleared() {
		_spec.ClearField(modelcatalogbinding.FieldCacheWrite1hPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.CacheReadPrice(); ok {
		_spec.SetField(modelcatalogbinding.FieldCacheReadPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCacheReadPrice(); ok {
		_spec.AddField(modelcatalogbinding.FieldCacheReadPrice, field.TypeFloat64, value)
	}
	if _u.mutation.CacheReadPriceCleared() {
		_spec.ClearField(modelcatalogbinding.FieldCacheReadPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.PriceIntervals(); ok {
		_spec.SetField(modelcatalogbinding.FieldPriceIntervals, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPriceIntervals(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, modelcatalogbinding.FieldPriceIntervals, value)
		})
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(modelcatalogbinding.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.EntryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   modelcatalogbinding.EntryTable,
			Columns: []string{modelcatalogbinding.EntryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelcatalogentry.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EntryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   modelcatalogbinding.EntryTable,
			Columns: []string{modelcatalogbinding.EntryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelcatalogentry.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   modelcatalogbinding.AccountTable,
			Columns: []string{modelcatalogbinding.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   modelcatalogbinding.AccountTable,
			Columns: []string{modelcatalogbinding.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ModelCatalogBinding{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{modelcatalogbinding.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
