// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/modelcatalogtimepricing"
)

// ModelCatalogTimePricingCreate is the builder for creating a ModelCatalogTimePricing entity.
type ModelCatalogTimePricingCreate struct {
	config
	mutation *ModelCatalogTimePricingMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ModelCatalogTimePricingCreate) SetCreatedAt(v time.Time) *ModelCatalogTimePricingCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ModelCatalogTimePricingCreate) SetNillableCreatedAt(v *time.Time) *ModelCatalogTimePricingCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ModelCatalogTimePricingCreate) SetUpdatedAt(v time.Time) *ModelCatalogTimePricingCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ModelCatalogTimePricingCreate) SetNillableUpdatedAt(v *time.Time) *ModelCatalogTimePricingCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetEntryID sets the "entry_id" field.
func (_c *ModelCatalogTimePricingCreate) SetEntryID(v int64) *ModelCatalogTimePricingCreate {
	_c.mutation.SetEntryID(v)
	return _c
}

// SetTimezone sets the "timezone" field.
func (_c *ModelCatalogTimePricingCreate) SetTimezone(v string) *ModelCatalogTimePricingCreate {
	_c.mutation.SetTimezone(v)
	return _c
}

// SetNillableTimezone sets the "timezone" field if the given value is not nil.
func (_c *ModelCatalogTimePricingCreate) SetNillableTimezone(v *string) *ModelCatalogTimePricingCreate {
	if v != nil {
		_c.SetTimezone(*v)
	}
	return _c
}

// SetWeekdaysOnly sets the "weekdays_only" field.
func (_c *ModelCatalogTimePricingCreate) SetWeekdaysOnly(v bool) *ModelCatalogTimePricingCreate {
	_c.mutation.SetWeekdaysOnly(v)
	return _c
}

// SetNillableWeekdaysOnly sets the "weekdays_only" field if the given value is not nil.
func (_c *ModelCatalogTimePricingCreate) SetNillableWeekdaysOnly(v *bool) *ModelCatalogTimePricingCreate {
	if v != nil {
		_c.SetWeekdaysOnly(*v)
	}
	return _c
}

// SetPeriods sets the "periods" field.
func (_c *ModelCatalogTimePricingCreate) SetPeriods(v []map[string]interface{}) *ModelCatalogTimePricingCreate {
	_c.mutation.SetPeriods(v)
	return _c
}

// Mutation returns the ModelCatalogTimePricingMutation object of the builder.
func (_c *ModelCatalogTimePricingCreate) Mutation() *ModelCatalogTimePricingMutation {
	return _c.mutation
}

// Save creates the ModelCatalogTimePricing in the database.
func (_c *ModelCatalogTimePricingCreate) Save(ctx context.Context) (*ModelCatalogTimePricing, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ModelCatalogTimePricingCreate) SaveX(ctx context.Context) *ModelCatalogTimePricing {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ModelCatalogTimePricingCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ModelCatalogTimePricingCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ModelCatalogTimePricingCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := modelcatalogtimepricing.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := modelcatalogtimepricing.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Timezone(); !ok {
		v := modelcatalogtimepricing.DefaultTimezone
		_c.mutation.SetTimezone(v)
	}
	if _, ok := _c.mutation.WeekdaysOnly(); !ok {
		v := modelcatalogtimepricing.DefaultWeekdaysOnly
		_c.mutation.SetWeekdaysOnly(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ModelCatalogTimePricingCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ModelCatalogTimePricing.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ModelCatalogTimePricing.updated_at"`)}
	}
	if _, ok := _c.mutation.EntryID(); !ok {
		return &ValidationError{Name: "entry_id", err: errors.New(`ent: missing required field "ModelCatalogTimePricing.entry_id"`)}
	}
	if _, ok := _c.mutation.Timezone(); !ok {
		return &ValidationError{Name: "timezone", err: errors.New(`ent: missing required field "ModelCatalogTimePricing.timezone"`)}
	}
	if v, ok := _c.mutation.Timezone(); ok {
		if err := modelcatalogtimepricing.TimezoneValidator(v); err != nil {
			return &ValidationError{Name: "timezone", err: fmt.Errorf(`ent: validator failed for field "ModelCatalogTimePricing.timezone": %w`, err)}
		}
	}
	if _, ok := _c.mutation.WeekdaysOnly(); !ok {
		return &ValidationError{Name: "weekdays_only", err: errors.New(`ent: missing required field "ModelCatalogTimePricing.weekdays_only"`)}
	}
	return nil
}

func (_c *ModelCatalogTimePricingCreate) sqlSave(ctx context.Context) (*ModelCatalogTimePricing, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ModelCatalogTimePricingCreate) createSpec() (*ModelCatalogTimePricing, *sqlgraph.CreateSpec) {
	var (
		_node = &ModelCatalogTimePricing{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(modelcatalogtimepricing.Table, sqlgraph.NewFieldSpec(modelcatalogtimepricing.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(modelcatalogtimepricing.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(modelcatalogtimepricing.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.EntryID(); ok {
		_spec.SetField(modelcatalogtimepricing.FieldEntryID, field.TypeInt64, value)
		_node.EntryID = value
	}
	if value, ok := _c.mutation.Timezone(); ok {
		_spec.SetField(modelcatalogtimepricing.FieldTimezone, field.TypeString, value)
		_node.Timezone = value
	}
	if value, ok := _c.mutation.WeekdaysOnly(); ok {
		_spec.SetField(modelcatalogtimepricing.FieldWeekdaysOnly, field.TypeBool, value)
		_node.WeekdaysOnly = value
	}
	if value, ok := _c.mutation.Periods(); ok {
		_spec.SetField(modelcatalogtimepricing.FieldPeriods, field.TypeJSON, value)
		_node.Periods = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ModelCatalogTimePricing.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ModelCatalogTimePricingUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ModelCatalogTimePricingCreate) OnConflict(opts ...sql.ConflictOption) *ModelCatalogTimePricingUpsertOne {
	_c.conflict = opts
	return &ModelCatalogTimePricingUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ModelCatalogTimePricing.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ModelCatalogTimePricingCreate) OnConflictColumns(columns ...string) *ModelCatalogTimePricingUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ModelCatalogTimePricingUpsertOne{
		create: _c,
	}
}

type (
	// ModelCatalogTimePricingUpsertOne is the builder for "upsert"-ing
	//  one ModelCatalogTimePricing node.
	ModelCatalogTimePricingUpsertOne struct {
		create *ModelCatalogTimePricingCreate
	}

	// ModelCatalogTimePricingUpsert is the "OnConflict" setter.
	ModelCatalogTimePricingUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ModelCatalogTimePricingUpsert) SetUpdatedAt(v time.Time) *ModelCatalogTimePricingUpsert {
	u.Set(modelcatalogtimepricing.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ModelCatalogTimePricingUpsert) UpdateUpdatedAt() *ModelCatalogTimePricingUpsert {
	u.SetExcluded(modelcatalogtimepricing.FieldUpdatedAt)
	return u
}

// SetEntryID sets the "entry_id" field.
func (u *ModelCatalogTimePricingUpsert) SetEntryID(v int64) *ModelCatalogTimePricingUpsert {
	u.Set(modelcatalogtimepricing.FieldEntryID, v)
	return u
}

// UpdateEntryID sets the "entry_id" field to the value that was provided on create.
func (u *ModelCatalogTimePricingUpsert) UpdateEntryID() *ModelCatalogTimePricingUpsert {
	u.SetExcluded(modelcatalogtimepricing.FieldEntryID)
	return u
}

// AddEntryID adds v to the "entry_id" field.
func (u *ModelCatalogTimePricingUpsert) AddEntryID(v int64) *ModelCatalogTimePricingUpsert {
	u.Add(modelcatalogtimepricing.FieldEntryID, v)
	return u
}

// SetTimezone sets the "timezone" field.
func (u *ModelCatalogTimePricingUpsert) SetTimezone(v string) *ModelCatalogTimePricingUpsert {
	u.Set(modelcatalogtimepricing.FieldTimezone, v)
	return u
}

// UpdateTimezone sets the "timezone" field to the value that was provided on create.
func (u *ModelCatalogTimePricingUpsert) UpdateTimezone() *ModelCatalogTimePricingUpsert {
	u.SetExcluded(modelcatalogtimepricing.FieldTimezone)
	return u
}

// SetWeekdaysOnly sets the "weekdays_only" field.
func (u *ModelCatalogTimePricingUpsert) SetWeekdaysOnly(v bool) *ModelCatalogTimePricingUpsert {
	u.Set(modelcatalogtimepricing.FieldWeekdaysOnly, v)
	return u
}

// UpdateWeekdaysOnly sets the "weekdays_only" field to the value that was provided on create.
func (u *ModelCatalogTimePricingUpsert) UpdateWeekdaysOnly() *ModelCatalogTimePricingUpsert {
	u.SetExcluded(modelcatalogtimepricing.FieldWeekdaysOnly)
	return u
}

// SetPeriods sets the "periods" field.
func (u *ModelCatalogTimePricingUpsert) SetPeriods(v []map[string]interface{}) *ModelCatalogTimePricingUpsert {
	u.Set(modelcatalogtimepricing.FieldPeriods, v)
	return u
}

// UpdatePeriods sets the "periods" field to the value that was provided on create.
func (u *ModelCatalogTimePricingUpsert) UpdatePeriods() *ModelCatalogTimePricingUpsert {
	u.SetExcluded(modelcatalogtimepricing.FieldPeriods)
	return u
}

// ClearPeriods clears the value of the "periods" field.
func (u *ModelCatalogTimePricingUpsert) ClearPeriods() *ModelCatalogTimePricingUpsert {
	u.SetNull(modelcatalogtimepricing.FieldPeriods)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ModelCatalogTimePricing.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ModelCatalogTimePricingUpsertOne) UpdateNewValues() *ModelCatalogTimePricingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(modelcatalogtimepricing.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ModelCatalogTimePricing.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ModelCatalogTimePricingUpsertOne) Ignore() *ModelCatalogTimePricingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ModelCatalogTimePricingUpsertOne) DoNothing() *ModelCatalogTimePricingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ModelCatalogTimePricingCreate.OnConflict
// documentation for more info.
func (u *ModelCatalogTimePricingUpsertOne) Update(set func(*ModelCatalogTimePricingUpsert)) *ModelCatalogTimePricingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ModelCatalogTimePricingUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ModelCatalogTimePricingUpsertOne) SetUpdatedAt(v time.Time) *ModelCatalogTimePricingUpsertOne {
	return u.Update(func(s *ModelCatalogTimePricingUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ModelCatalogTimePricingUpsertOne) UpdateUpdatedAt() *ModelCatalogTimePricingUpsertOne {
	return u.Update(func(s *ModelCatalogTimePricingUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetEntryID sets the "entry_id" field.
func (u *ModelCatalogTimePricingUpsertOne) SetEntryID(v int64) *ModelCatalogTimePricingUpsertOne {
	return u.Update(func(s *ModelCatalogTimePricingUpsert) {
		s.SetEntryID(v)
	})
}

// AddEntryID adds v to the "entry_id" field.
func (u *ModelCatalogTimePricingUpsertOne) AddEntryID(v int64) *ModelCatalogTimePricingUpsertOne {
	return u.Update(func(s *ModelCatalogTimePricingUpsert) {
		s.AddEntryID(v)
	})
}

// UpdateEntryID sets the "entry_id" field to the value that was provided on create.
func (u *ModelCatalogTimePricingUpsertOne) UpdateEntryID() *ModelCatalogTimePricingUpsertOne {
	return u.Update(func(s *ModelCatalogTimePricingUpsert) {
		s.UpdateEntryID()
	})
}

// SetTimezone sets the "timezone" field.
func (u *ModelCatalogTimePricingUpsertOne) SetTimezone(v string) *ModelCatalogTimePricingUpsertOne {
	return u.Update(func(s *ModelCatalogTimePricingUpsert) {
		s.SetTimezone(v)
	})
}

// UpdateTimezone sets the "timezone" field to the value that was provided on create.
func (u *ModelCatalogTimePricingUpsertOne) UpdateTimezone() *ModelCatalogTimePricingUpsertOne {
	return u.Update(func(s *ModelCatalogTimePricingUpsert) {
		s.UpdateTimezone()
	})
}

// SetWeekdaysOnly sets the "weekdays_only" field.
func (u *ModelCatalogTimePricingUpsertOne) SetWeekdaysOnly(v bool) *ModelCatalogTimePricingUpsertOne {
	return u.Update(func(s *ModelCatalogTimePricingUpsert) {
		s.SetWeekdaysOnly(v)
	})
}

// UpdateWeekdaysOnly sets the "weekdays_only" field to the value that was provided on create.
func (u *ModelCatalogTimePricingUpsertOne) UpdateWeekdaysOnly() *ModelCatalogTimePricingUpsertOne {
	return u.Update(func(s *ModelCatalogTimePricingUpsert) {
		s.UpdateWeekdaysOnly()
	})
}

// SetPeriods sets the "periods" field.
func (u *ModelCatalogTimePricingUpsertOne) SetPeriods(v []map[string]interface{}) *ModelCatalogTimePricingUpsertOne {
	return u.Update(func(s *ModelCatalogTimePricingUpsert) {
		s.SetPeriods(v)
	})
}

// UpdatePeriods sets the "periods" field to the value that was provided on create.
func (u *ModelCatalogTimePricingUpsertOne) UpdatePeriods() *ModelCatalogTimePricingUpsertOne {
	return u.Update(func(s *ModelCatalogTimePricingUpsert) {
		s.UpdatePeriods()
	})
}

// ClearPeriods clears the value of the "periods" field.
func (u *ModelCatalogTimePricingUpsertOne) ClearPeriods() *ModelCatalogTimePricingUpsertOne {
	return u.Update(func(s *ModelCatalogTimePricingUpsert) {
		s.ClearPeriods()
	})
}

// Exec executes the query.
func (u *ModelCatalogTimePricingUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ModelCatalogTimePricingCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ModelCatalogTimePricingUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ModelCatalogTimePricingUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ModelCatalogTimePricingUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ModelCatalogTimePricingCreateBulk is the builder for creating many ModelCatalogTimePricing entities in bulk.
type ModelCatalogTimePricingCreateBulk struct {
	config
	err      error
	builders []*ModelCatalogTimePricingCreate
	conflict []sql.ConflictOption
}

// Save creates the ModelCatalogTimePricing entities in the database.
func (_c *ModelCatalogTimePricingCreateBulk) Save(ctx context.Context) ([]*ModelCatalogTimePricing, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ModelCatalogTimePricing, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ModelCatalogTimePricingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ModelCatalogTimePricingCreateBulk) SaveX(ctx context.Context) []*ModelCatalogTimePricing {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ModelCatalogTimePricingCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ModelCatalogTimePricingCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ModelCatalogTimePricing.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ModelCatalogTimePricingUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ModelCatalogTimePricingCreateBulk) OnConflict(opts ...sql.ConflictOption) *ModelCatalogTimePricingUpsertBulk {
	_c.conflict = opts
	return &ModelCatalogTimePricingUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ModelCatalogTimePricing.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ModelCatalogTimePricingCreateBulk) OnConflictColumns(columns ...string) *ModelCatalogTimePricingUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ModelCatalogTimePricingUpsertBulk{
		create: _c,
	}
}

// ModelCatalogTimePricingUpsertBulk is the builder for "upsert"-ing
// a bulk of ModelCatalogTimePricing nodes.
type ModelCatalogTimePricingUpsertBulk struct {
	create *ModelCatalogTimePricingCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ModelCatalogTimePricing.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ModelCatalogTimePricingUpsertBulk) UpdateNewValues() *ModelCatalogTimePricingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(modelcatalogtimepricing.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ModelCatalogTimePricing.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ModelCatalogTimePricingUpsertBulk) Ignore() *ModelCatalogTimePricingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ModelCatalogTimePricingUpsertBulk) DoNothing() *ModelCatalogTimePricingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ModelCatalogTimePricingCreateBulk.OnConflict
// documentation for more info.
func (u *ModelCatalogTimePricingUpsertBulk) Update(set func(*ModelCatalogTimePricingUpsert)) *ModelCatalogTimePricingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ModelCatalogTimePricingUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ModelCatalogTimePricingUpsertBulk) SetUpdatedAt(v time.Time) *ModelCatalogTimePricingUpsertBulk {
	return u.Update(func(s *ModelCatalogTimePricingUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ModelCatalogTimePricingUpsertBulk) UpdateUpdatedAt() *ModelCatalogTimePricingUpsertBulk {
	return u.Update(func(s *ModelCatalogTimePricingUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetEntryID sets the "entry_id" field.
func (u *ModelCatalogTimePricingUpsertBulk) SetEntryID(v int64) *ModelCatalogTimePricingUpsertBulk {
	return u.Update(func(s *ModelCatalogTimePricingUpsert) {
		s.SetEntryID(v)
	})
}

// AddEntryID adds v to the "entry_id" field.
func (u *ModelCatalogTimePricingUpsertBulk) AddEntryID(v int64) *ModelCatalogTimePricingUpsertBulk {
	return u.Update(func(s *ModelCatalogTimePricingUpsert) {
		s.AddEntryID(v)
	})
}

// UpdateEntryID sets the "entry_id" field to the value that was provided on create.
func (u *ModelCatalogTimePricingUpsertBulk) UpdateEntryID() *ModelCatalogTimePricingUpsertBulk {
	return u.Update(func(s *ModelCatalogTimePricingUpsert) {
		s.UpdateEntryID()
	})
}

// SetTimezone sets the "timezone" field.
func (u *ModelCatalogTimePricingUpsertBulk) SetTimezone(v string) *ModelCatalogTimePricingUpsertBulk {
	return u.Update(func(s *ModelCatalogTimePricingUpsert) {
		s.SetTimezone(v)
	})
}

// UpdateTimezone sets the "timezone" field to the value that was provided on create.
func (u *ModelCatalogTimePricingUpsertBulk) UpdateTimezone() *ModelCatalogTimePricingUpsertBulk {
	return u.Update(func(s *ModelCatalogTimePricingUpsert) {
		s.UpdateTimezone()
	})
}

// SetWeekdaysOnly sets the "weekdays_only" field.
func (u *ModelCatalogTimePricingUpsertBulk) SetWeekdaysOnly(v bool) *ModelCatalogTimePricingUpsertBulk {
	return u.Update(func(s *ModelCatalogTimePricingUpsert) {
		s.SetWeekdaysOnly(v)
	})
}

// UpdateWeekdaysOnly sets the "weekdays_only" field to the value that was provided on create.
func (u *ModelCatalogTimePricingUpsertBulk) UpdateWeekdaysOnly() *ModelCatalogTimePricingUpsertBulk {
	return u.Update(func(s *ModelCatalogTimePricingUpsert) {
		s.UpdateWeekdaysOnly()
	})
}

// SetPeriods sets the "periods" field.
func (u *ModelCatalogTimePricingUpsertBulk) SetPeriods(v []map[string]interface{}) *ModelCatalogTimePricingUpsertBulk {
	return u.Update(func(s *ModelCatalogTimePricingUpsert) {
		s.SetPeriods(v)
	})
}

// UpdatePeriods sets the "periods" field to the value that was provided on create.
func (u *ModelCatalogTimePricingUpsertBulk) UpdatePeriods() *ModelCatalogTimePricingUpsertBulk {
	return u.Update(func(s *ModelCatalogTimePricingUpsert) {
		s.UpdatePeriods()
	})
}

// ClearPeriods clears the value of the "periods" field.
func (u *ModelCatalogTimePricingUpsertBulk) ClearPeriods() *ModelCatalogTimePricingUpsertBulk {
	return u.Update(func(s *ModelCatalogTimePricingUpsert) {
		s.ClearPeriods()
	})
}

// Exec executes the query.
func (u *ModelCatalogTimePricingUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ModelCatalogTimePricingCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ModelCatalogTimePricingCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ModelCatalogTimePricingUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
