// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/modelcatalogentry"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ModelCatalogEntryUpdate is the builder for updating ModelCatalogEntry entities.
type ModelCatalogEntryUpdate struct {
	config
	hooks    []Hook
	mutation *ModelCatalogEntryMutation
}

// Where appends a list predicates to the ModelCatalogEntryUpdate builder.
func (_u *ModelCatalogEntryUpdate) Where(ps ...predicate.ModelCatalogEntry) *ModelCatalogEntryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ModelCatalogEntryUpdate) SetUpdatedAt(v time.Time) *ModelCatalogEntryUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetModelID sets the "model_id" field.
func (_u *ModelCatalogEntryUpdate) SetModelID(v string) *ModelCatalogEntryUpdate {
	_u.mutation.SetModelID(v)
	return _u
}

// SetNillableModelID sets the "model_id" field if the given value is not nil.
func (_u *ModelCatalogEntryUpdate) SetNillableModelID(v *string) *ModelCatalogEntryUpdate {
	if v != nil {
		_u.SetModelID(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *ModelCatalogEntryUpdate) SetDisplayName(v string) *ModelCatalogEntryUpdate {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *ModelCatalogEntryUpdate) SetNillableDisplayName(v *string) *ModelCatalogEntryUpdate {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// SetVendor sets the "vendor" field.
func (_u *ModelCatalogEntryUpdate) SetVendor(v string) *ModelCatalogEntryUpdate {
	_u.mutation.SetVendor(v)
	return _u
}

// SetNillableVendor sets the "vendor" field if the given value is not nil.
func (_u *ModelCatalogEntryUpdate) SetNillableVendor(v *string) *ModelCatalogEntryUpdate {
	if v != nil {
		_u.SetVendor(*v)
	}
	return _u
}

// SetProtocols sets the "protocols" field.
func (_u *ModelCatalogEntryUpdate) SetProtocols(v []string) *ModelCatalogEntryUpdate {
	_u.mutation.SetProtocols(v)
	return _u
}

// AppendProtocols appends value to the "protocols" field.
func (_u *ModelCatalogEntryUpdate) AppendProtocols(v []string) *ModelCatalogEntryUpdate {
	_u.mutation.AppendProtocols(v)
	return _u
}

// ClearProtocols clears the value of the "protocols" field.
func (_u *ModelCatalogEntryUpdate) ClearProtocols() *ModelCatalogEntryUpdate {
	_u.mutation.ClearProtocols()
	return _u
}

// SetBillingMode sets the "billing_mode" field.
func (_u *ModelCatalogEntryUpdate) SetBillingMode(v string) *ModelCatalogEntryUpdate {
	_u.mutation.SetBillingMode(v)
	return _u
}

// SetNillableBillingMode sets the "billing_mode" field if the given value is not nil.
func (_u *ModelCatalogEntryUpdate) SetNillableBillingMode(v *string) *ModelCatalogEntryUpdate {
	if v != nil {
		_u.SetBillingMode(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ModelCatalogEntryUpdate) SetStatus(v string) *ModelCatalogEntryUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ModelCatalogEntryUpdate) SetNillableStatus(v *string) *ModelCatalogEntryUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetManagedBy sets the "managed_by" field.
func (_u *ModelCatalogEntryUpdate) SetManagedBy(v string) *ModelCatalogEntryUpdate {
	_u.mutation.SetManagedBy(v)
	return _u
}

// SetNillableManagedBy sets the "managed_by" field if the given value is not nil.
func (_u *ModelCatalogEntryUpdate) SetNillableManagedBy(v *string) *ModelCatalogEntryUpdate {
	if v != nil {
		_u.SetManagedBy(*v)
	}
	return _u
}

// SetRoutePlatform sets the "route_platform" field.
func (_u *ModelCatalogEntryUpdate) SetRoutePlatform(v string) *ModelCatalogEntryUpdate {
	_u.mutation.SetRoutePlatform(v)
	return _u
}

// SetNillableRoutePlatform sets the "route_platform" field if the given value is not nil.
func (_u *ModelCatalogEntryUpdate) SetNillableRoutePlatform(v *string) *ModelCatalogEntryUpdate {
	if v != nil {
		_u.SetRoutePlatform(*v)
	}
	return _u
}

// SetInputPrice sets the "input_price" field.
func (_u *ModelCatalogEntryUpdate) SetInputPrice(v float64) *ModelCatalogEntryUpdate {
	_u.mutation.ResetInputPrice()
	_u.mutation.SetInputPrice(v)
	return _u
}

// SetNillableInputPrice sets the "input_price" field if the given value is not nil.
func (_u *ModelCatalogEntryUpdate) SetNillableInputPrice(v *float64) *ModelCatalogEntryUpdate {
	if v != nil {
		_u.SetInputPrice(*v)
	}
	return _u
}

// AddInputPrice adds value to the "input_price" field.
func (_u *ModelCatalogEntryUpdate) AddInputPrice(v float64) *ModelCatalogEntryUpdate {
	_u.mutation.AddInputPrice(v)
	return _u
}

// ClearInputPrice clears the value of the "input_price" field.
func (_u *ModelCatalogEntryUpdate) ClearInputPrice() *ModelCatalogEntryUpdate {
	_u.mutation.ClearInputPrice()
	return _u
}

// SetOutputPrice sets the "output_price" field.
func (_u *ModelCatalogEntryUpdate) SetOutputPrice(v float64) *ModelCatalogEntryUpdate {
	_u.mutation.ResetOutputPrice()
	_u.mutation.SetOutputPrice(v)
	return _u
}

// SetNillableOutputPrice sets the "output_price" field if the given value is not nil.
func (_u *ModelCatalogEntryUpdate) SetNillableOutputPrice(v *float64) *ModelCatalogEntryUpdate {
	if v != nil {
		_u.SetOutputPrice(*v)
	}
	return _u
}

// AddOutputPrice adds value to the "output_price" field.
func (_u *ModelCatalogEntryUpdate) AddOutputPrice(v float64) *ModelCatalogEntryUpdate {
	_u.mutation.AddOutputPrice(v)
	return _u
}

// ClearOutputPrice clears the value of the "output_price" field.
func (_u *ModelCatalogEntryUpdate) ClearOutputPrice() *ModelCatalogEntryUpdate {
	_u.mutation.ClearOutputPrice()
	return _u
}

// SetCacheWritePrice sets the "cache_write_price" field.
func (_u *ModelCatalogEntryUpdate) SetCacheWritePrice(v float64) *ModelCatalogEntryUpdate {
	_u.mutation.ResetCacheWritePrice()
	_u.mutation.SetCacheWritePrice(v)
	return _u
}

// SetNillableCacheWritePrice sets the "cache_write_price" field if the given value is not nil.
func (_u *ModelCatalogEntryUpdate) SetNillableCacheWritePrice(v *float64) *ModelCatalogEntryUpdate {
	if v != nil {
		_u.SetCacheWritePrice(*v)
	}
	return _u
}

// AddCacheWritePrice adds value to the "cache_write_price" field.
func (_u *ModelCatalogEntryUpdate) AddCacheWritePrice(v float64) *ModelCatalogEntryUpdate {
	_u.mutation.AddCacheWritePrice(v)
	return _u
}

// ClearCacheWritePrice clears the value of the "cache_write_price" field.
func (_u *ModelCatalogEntryUpdate) ClearCacheWritePrice() *ModelCatalogEntryUpdate {
	_u.mutation.ClearCacheWritePrice()
	return _u
}

// SetCacheWrite1hPrice sets the "cache_write_1h_price" field.
func (_u *ModelCatalogEntryUpdate) SetCacheWrite1hPrice(v float64) *ModelCatalogEntryUpdate {
	_u.mutation.ResetCacheWrite1hPrice()
	_u.mutation.SetCacheWrite1hPrice(v)
	return _u
}

// SetNillableCacheWrite1hPrice sets the "cache_write_1h_price" field if the given value is not nil.
func (_u *ModelCatalogEntryUpdate) SetNillableCacheWrite1hPrice(v *float64) *ModelCatalogEntryUpdate {
	if v != nil {
		_u.SetCacheWrite1hPrice(*v)
	}
	return _u
}

// AddCacheWrite1hPrice adds value to the "cache_write_1h_price" field.
func (_u *ModelCatalogEntryUpdate) AddCacheWrite1hPrice(v float64) *ModelCatalogEntryUpdate {
	_u.mutation.AddCacheWrite1hPrice(v)
	return _u
}

// ClearCacheWrite1hPrice clears the value of the "cache_write_1h_price" field.
func (_u *ModelCatalogEntryUpdate) ClearCacheWrite1hPrice() *ModelCatalogEntryUpdate {
	_u.mutation.ClearCacheWrite1hPrice()
	return _u
}

// SetCacheReadPrice sets the "cache_read_price" field.
func (_u *ModelCatalogEntryUpdate) SetCacheReadPrice(v float64) *ModelCatalogEntryUpdate {
	_u.mutation.ResetCacheReadPrice()
	_u.mutation.SetCacheReadPrice(v)
	return _u
}

// SetNillableCacheReadPrice sets the "cache_read_price" field if the given value is not nil.
func (_u *ModelCatalogEntryUpdate) SetNillableCacheReadPrice(v *float64) *ModelCatalogEntryUpdate {
	if v != nil {
		_u.SetCacheReadPrice(*v)
	}
	return _u
}

// AddCacheReadPrice adds value to the "cache_read_price" field.
func (_u *ModelCatalogEntryUpdate) AddCacheReadPrice(v float64) *ModelCatalogEntryUpdate {
	_u.mutation.AddCacheReadPrice(v)
	return _u
}

// ClearCacheReadPrice clears the value of the "cache_read_price" field.
func (_u *ModelCatalogEntryUpdate) ClearCacheReadPrice() *ModelCatalogEntryUpdate {
	_u.mutation.ClearCacheReadPrice()
	return _u
}

// SetImageInputPrice sets the "image_input_price" field.
func (_u *ModelCatalogEntryUpdate) SetImageInputPrice(v float64) *ModelCatalogEntryUpdate {
	_u.mutation.ResetImageInputPrice()
	_u.mutation.SetImageInputPrice(v)
	return _u
}

// SetNillableImageInputPrice sets the "image_input_price" field if the given value is not nil.
func (_u *ModelCatalogEntryUpdate) SetNillableImageInputPrice(v *float64) *ModelCatalogEntryUpdate {
	if v != nil {
		_u.SetImageInputPrice(*v)
	}
	return _u
}

// AddImageInputPrice adds value to the "image_input_price" field.
func (_u *ModelCatalogEntryUpdate) AddImageInputPrice(v float64) *ModelCatalogEntryUpdate {
	_u.mutation.AddImageInputPrice(v)
	return _u
}

// ClearImageInputPrice clears the value of the "image_input_price" field.
func (_u *ModelCatalogEntryUpdate) ClearImageInputPrice() *ModelCatalogEntryUpdate {
	_u.mutation.ClearImageInputPrice()
	return _u
}

// SetImageOutputPrice sets the "image_output_price" field.
func (_u *ModelCatalogEntryUpdate) SetImageOutputPrice(v float64) *ModelCatalogEntryUpdate {
	_u.mutation.ResetImageOutputPrice()
	_u.mutation.SetImageOutputPrice(v)
	return _u
}

// SetNillableImageOutputPrice sets the "image_output_price" field if the given value is not nil.
func (_u *ModelCatalogEntryUpdate) SetNillableImageOutputPrice(v *float64) *ModelCatalogEntryUpdate {
	if v != nil {
		_u.SetImageOutputPrice(*v)
	}
	return _u
}

// AddImageOutputPrice adds value to the "image_output_price" field.
func (_u *ModelCatalogEntryUpdate) AddImageOutputPrice(v float64) *ModelCatalogEntryUpdate {
	_u.mutation.AddImageOutputPrice(v)
	return _u
}

// ClearImageOutputPrice clears the value of the "image_output_price" field.
func (_u *ModelCatalogEntryUpdate) ClearImageOutputPrice() *ModelCatalogEntryUpdate {
	_u.mutation.ClearImageOutputPrice()
	return _u
}

// SetImageCacheReadPrice sets the "image_cache_read_price" field.
func (_u *ModelCatalogEntryUpdate) SetImageCacheReadPrice(v float64) *ModelCatalogEntryUpdate {
	_u.mutation.ResetImageCacheReadPrice()
	_u.mutation.SetImageCacheReadPrice(v)
	return _u
}

// SetNillableImageCacheReadPrice sets the "image_cache_read_price" field if the given value is not nil.
func (_u *ModelCatalogEntryUpdate) SetNillableImageCacheReadPrice(v *float64) *ModelCatalogEntryUpdate {
	if v != nil {
		_u.SetImageCacheReadPrice(*v)
	}
	return _u
}

// AddImageCacheReadPrice adds value to the "image_cache_read_price" field.
func (_u *ModelCatalogEntryUpdate) AddImageCacheReadPrice(v float64) *ModelCatalogEntryUpdate {
	_u.mutation.AddImageCacheReadPrice(v)
	return _u
}

// ClearImageCacheReadPrice clears the value of the "image_cache_read_price" field.
func (_u *ModelCatalogEntryUpdate) ClearImageCacheReadPrice() *ModelCatalogEntryUpdate {
	_u.mutation.ClearImageCacheReadPrice()
	return _u
}

// SetInputPricePriority sets the "input_price_priority" field.
func (_u *ModelCatalogEntryUpdate) SetInputPricePriority(v float64) *ModelCatalogEntryUpdate {
	_u.mutation.ResetInputPricePriority()
	_u.mutation.SetInputPricePriority(v)
	return _u
}

// SetNillableInputPricePriority sets the "input_price_priority" field if the given value is not nil.
func (_u *ModelCatalogEntryUpdate) SetNillableInputPricePriority(v *float64) *ModelCatalogEntryUpdate {
	if v != nil {
		_u.SetInputPricePriority(*v)
	}
	return _u
}

// AddInputPricePriority adds value to the "input_price_priority" field.
func (_u *ModelCatalogEntryUpdate) AddInputPricePriority(v float64) *ModelCatalogEntryUpdate {
	_u.mutation.AddInputPricePriority(v)
	return _u
}

// ClearInputPricePriority clears the value of the "input_price_priority" field.
func (_u *ModelCatalogEntryUpdate) ClearInputPricePriority() *ModelCatalogEntryUpdate {
	_u.mutation.ClearInputPricePriority()
	return _u
}

// SetOutputPricePriority sets the "output_price_priority" field.
func (_u *ModelCatalogEntryUpdate) SetOutputPricePriority(v float64) *ModelCatalogEntryUpdate {
	_u.mutation.ResetOutputPricePriority()
	_u.mutation.SetOutputPricePriority(v)
	return _u
}

// SetNillableOutputPricePriority sets the "output_price_priority" field if the given value is not nil.
func (_u *ModelCatalogEntryUpdate) SetNillableOutputPricePriority(v *float64) *ModelCatalogEntryUpdate {
	if v != nil {
		_u.SetOutputPricePriority(*v)
	}
	return _u
}

// AddOutputPricePriority adds value to the "output_price_priority" field.
func (_u *ModelCatalogEntryUpdate) AddOutputPricePriority(v float64) *ModelCatalogEntryUpdate {
	_u.mutation.AddOutputPricePriority(v)
	return _u
}

// ClearOutputPricePriority clears the value of the "output_price_priority" field.
func (_u *ModelCatalogEntryUpdate) ClearOutputPricePriority() *ModelCatalogEntryUpdate {
	_u.mutation.ClearOutputPricePriority()
	return _u
}

// SetCacheWritePricePriority sets the "cache_write_price_priority" field.
func (_u *ModelCatalogEntryUpdate) SetCacheWritePricePriority(v float64) *ModelCatalogEntryUpdate {
	_u.mutation.ResetCacheWritePricePriority()
	_u.mutation.SetCacheWritePricePriority(v)
	return _u
}

// SetNillableCacheWritePricePriority sets the "cache_write_price_priority" field if the given value is not nil.
func (_u *ModelCatalogEntryUpdate) SetNillableCacheWritePricePriority(v *float64) *ModelCatalogEntryUpdate {
	if v != nil {
		_u.SetCacheWritePricePriority(*v)
	}
	return _u
}

// AddCacheWritePricePriority adds value to the "cache_write_price_priority" field.
func (_u *ModelCatalogEntryUpdate) AddCacheWritePricePriority(v float64) *ModelCatalogEntryUpdate {
	_u.mutation.AddCacheWritePricePriority(v)
	return _u
}

// ClearCacheWritePricePriority clears the value of the "cache_write_price_priority" field.
func (_u *ModelCatalogEntryUpdate) ClearCacheWritePricePriority() *ModelCatalogEntryUpdate {
	_u.mutation.ClearCacheWritePricePriority()
	return _u
}

// SetCacheReadPricePriority sets the "cache_read_price_priority" field.
func (_u *ModelCatalogEntryUpdate) SetCacheReadPricePriority(v float64) *ModelCatalogEntryUpdate {
	_u.mutation.ResetCacheReadPricePriority()
	_u.mutation.SetCacheReadPricePriority(v)
	return _u
}

// SetNillableCacheReadPricePriority sets the "cache_read_price_priority" field if the given value is not nil.
func (_u *ModelCatalogEntryUpdate) SetNillableCacheReadPricePriority(v *float64) *ModelCatalogEntryUpdate {
	if v != nil {
		_u.SetCacheReadPricePriority(*v)
	}
	return _u
}

// AddCacheReadPricePriority adds value to the "cache_read_price_priority" field.
func (_u *ModelCatalogEntryUpdate) AddCacheReadPricePriority(v float64) *ModelCatalogEntryUpdate {
	_u.mutation.AddCacheReadPricePriority(v)
	return _u
}

// ClearCacheReadPricePriority clears the value of the "cache_read_price_priority" field.
func (_u *ModelCatalogEntryUpdate) ClearCacheReadPricePriority() *ModelCatalogEntryUpdate {
	_u.mutation.ClearCacheReadPricePriority()
	return _u
}

// SetPerRequestPrice sets the "per_request_price" field.
func (_u *ModelCatalogEntryUpdate) SetPerRequestPrice(v float64) *ModelCatalogEntryUpdate {
	_u.mutation.ResetPerRequestPrice()
	_u.mutation.SetPerRequestPrice(v)
	return _u
}

// SetNillablePerRequestPrice sets the "per_request_price" field if the given value is not nil.
func (_u *ModelCatalogEntryUpdate) SetNillablePerRequestPrice(v *float64) *ModelCatalogEntryUpdate {
	if v != nil {
		_u.SetPerRequestPrice(*v)
	}
	return _u
}

// AddPerRequestPrice adds value to the "per_request_price" field.
func (_u *ModelCatalogEntryUpdate) AddPerRequestPrice(v float64) *ModelCatalogEntryUpdate {
	_u.mutation.AddPerRequestPrice(v)
	return _u
}

// ClearPerRequestPrice clears the value of the "per_request_price" field.
func (_u *ModelCatalogEntryUpdate) ClearPerRequestPrice() *ModelCatalogEntryUpdate {
	_u.mutation.ClearPerRequestPrice()
	return _u
}

// SetLongContextInputThreshold sets the "long_context_input_threshold" field.
func (_u *ModelCatalogEntryUpdate) SetLongContextInputThreshold(v int) *ModelCatalogEntryUpdate {
	_u.mutation.ResetLongContextInputThreshold()
	_u.mutation.SetLongContextInputThreshold(v)
	return _u
}

// SetNillableLongContextInputThreshold sets the "long_context_input_threshold" field if the given value is not nil.
func (_u *ModelCatalogEntryUpdate) SetNillableLongContextInputThreshold(v *int) *ModelCatalogEntryUpdate {
	if v != nil {
		_u.SetLongContextInputThreshold(*v)
	}
	return _u
}

// AddLongContextInputThreshold adds value to the "long_context_input_threshold" field.
func (_u *ModelCatalogEntryUpdate) AddLongContextInputThreshold(v int) *ModelCatalogEntryUpdate {
	_u.mutation.AddLongContextInputThreshold(v)
	return _u
}

// ClearLongContextInputThreshold clears the value of the "long_context_input_threshold" field.
func (_u *ModelCatalogEntryUpdate) ClearLongContextInputThreshold() *ModelCatalogEntryUpdate {
	_u.mutation.ClearLongContextInputThreshold()
	return _u
}

// SetLongContextThresholdInclusive sets the "long_context_threshold_inclusive" field.
func (_u *ModelCatalogEntryUpdate) SetLongContextThresholdInclusive(v bool) *ModelCatalogEntryUpdate {
	_u.mutation.SetLongContextThresholdInclusive(v)
	return _u
}

// SetNillableLongContextThresholdInclusive sets the "long_context_threshold_inclusive" field if the given value is not nil.
func (_u *ModelCatalogEntryUpdate) SetNillableLongContextThresholdInclusive(v *bool) *ModelCatalogEntryUpdate {
	if v != nil {
		_u.SetLongContextThresholdInclusive(*v)
	}
	return _u
}

// SetLongContextInputMultiplier sets the "long_context_input_multiplier" field.
func (_u *ModelCatalogEntryUpdate) SetLongContextInputMultiplier(v float64) *ModelCatalogEntryUpdate {
	_u.mutation.ResetLongContextInputMultiplier()
	_u.mutation.SetLongContextInputMultiplier(v)
	return _u
}

// SetNillableLongContextInputMultiplier sets the "long_context_input_multiplier" field if the given value is not nil.
func (_u *ModelCatalogEntryUpdate) SetNillableLongContextInputMultiplier(v *float64) *ModelCatalogEntryUpdate {
	if v != nil {
		_u.SetLongContextInputMultiplier(*v)
	}
	return _u
}

// AddLongContextInputMultiplier adds value to the "long_context_input_multiplier" field.
func (_u *ModelCatalogEntryUpdate) AddLongContextInputMultiplier(v float64) *ModelCatalogEntryUpdate {
	_u.mutation.AddLongContextInputMultiplier(v)
	return _u
}

// ClearLongContextInputMultiplier clears the value of the "long_context_input_multiplier" field.
func (_u *ModelCatalogEntryUpdate) ClearLongContextInputMultiplier() *ModelCatalogEntryUpdate {
	_u.mutation.ClearLongContextInputMultiplier()
	return _u
}

// SetLongContextOutputMultiplier sets the "long_context_output_multiplier" field.
func (_u *ModelCatalogEntryUpdate) SetLongContextOutputMultiplier(v float64) *ModelCatalogEntryUpdate {
	_u.mutation.ResetLongContextOutputMultiplier()
	_u.mutation.SetLongContextOutputMultiplier(v)
	return _u
}

// SetNillableLongContextOutputMultiplier sets the "long_context_output_multiplier" field if the given value is not nil.
func (_u *ModelCatalogEntryUpdate) SetNillableLongContextOutputMultiplier(v *float64) *ModelCatalogEntryUpdate {
	if v != nil {
		_u.SetLongContextOutputMultiplier(*v)
	}
	return _u
}

// AddLongContextOutputMultiplier adds value to the "long_context_output_multiplier" field.
func (_u *ModelCatalogEntryUpdate) AddLongContextOutputMultiplier(v float64) *ModelCatalogEntryUpdate {
	_u.mutation.AddLongContextOutputMultiplier(v)
	return _u
}

// ClearLongContextOutputMultiplier clears the value of the "long_context_output_multiplier" field.
func (_u *ModelCatalogEntryUpdate) ClearLongContextOutputMultiplier() *ModelCatalogEntryUpdate {
	_u.mutation.ClearLongContextOutputMultiplier()
	return _u
}

// SetFastMultiplier sets the "fast_multiplier" field.
func (_u *ModelCatalogEntryUpdate) SetFastMultiplier(v float64) *ModelCatalogEntryUpdate {
	_u.mutation.ResetFastMultiplier()
	_u.mutation.SetFastMultiplier(v)
	return _u
}

// SetNillableFastMultiplier sets the "fast_multiplier" field if the given value is not nil.
func (_u *ModelCatalogEntryUpdate) SetNillableFastMultiplier(v *float64) *ModelCatalogEntryUpdate {
	if v != nil {
		_u.SetFastMultiplier(*v)
	}
	return _u
}

// AddFastMultiplier adds value to the "fast_multiplier" field.
func (_u *ModelCatalogEntryUpdate) AddFastMultiplier(v float64) *ModelCatalogEntryUpdate {
	_u.mutation.AddFastMultiplier(v)
	return _u
}

// ClearFastMultiplier clears the value of the "fast_multiplier" field.
func (_u *ModelCatalogEntryUpdate) ClearFastMultiplier() *ModelCatalogEntryUpdate {
	_u.mutation.ClearFastMultiplier()
	return _u
}

// SetFlexMultiplier sets the "flex_multiplier" field.
func (_u *ModelCatalogEntryUpdate) SetFlexMultiplier(v float64) *ModelCatalogEntryUpdate {
	_u.mutation.ResetFlexMultiplier()
	_u.mutation.SetFlexMultiplier(v)
	return _u
}

// SetNillableFlexMultiplier sets the "flex_multiplier" field if the given value is not nil.
func (_u *ModelCatalogEntryUpdate) SetNillableFlexMultiplier(v *float64) *ModelCatalogEntryUpdate {
	if v != nil {
		_u.SetFlexMultiplier(*v)
	}
	return _u
}

// AddFlexMultiplier adds value to the "flex_multiplier" field.
func (_u *ModelCatalogEntryUpdate) AddFlexMultiplier(v float64) *ModelCatalogEntryUpdate {
	_u.mutation.AddFlexMultiplier(v)
	return _u
}

// ClearFlexMultiplier clears the value of the "flex_multiplier" field.
func (_u *ModelCatalogEntryUpdate) ClearFlexMultiplier() *ModelCatalogEntryUpdate {
	_u.mutation.ClearFlexMultiplier()
	return _u
}

// SetMaxReasoningEffortMultiplier sets the "max_reasoning_effort_multiplier" field.
func (_u *ModelCatalogEntryUpdate) SetMaxReasoningEffortMultiplier(v float64) *ModelCatalogEntryUpdate {
	_u.mutation.ResetMaxReasoningEffortMultiplier()
	_u.mutation.SetMaxReasoningEffortMultiplier(v)
	return _u
}

// SetNillableMaxReasoningEffortMultiplier sets the "max_reasoning_effort_multiplier" field if the given value is not nil.
func (_u *ModelCatalogEntryUpdate) SetNillableMaxReasoningEffortMultiplier(v *float64) *ModelCatalogEntryUpdate {
	if v != nil {
		_u.SetMaxReasoningEffortMultiplier(*v)
	}
	return _u
}

// AddMaxReasoningEffortMultiplier adds value to the "max_reasoning_effort_multiplier" field.
func (_u *ModelCatalogEntryUpdate) AddMaxReasoningEffortMultiplier(v float64) *ModelCatalogEntryUpdate {
	_u.mutation.AddMaxReasoningEffortMultiplier(v)
	return _u
}

// ClearMaxReasoningEffortMultiplier clears the value of the "max_reasoning_effort_multiplier" field.
func (_u *ModelCatalogEntryUpdate) ClearMaxReasoningEffortMultiplier() *ModelCatalogEntryUpdate {
	_u.mutation.ClearMaxReasoningEffortMultiplier()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *ModelCatalogEntryUpdate) SetNotes(v string) *ModelCatalogEntryUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *ModelCatalogEntryUpdate) SetNillableNotes(v *string) *ModelCatalogEntryUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *ModelCatalogEntryUpdate) ClearNotes() *ModelCatalogEntryUpdate {
	_u.mutation.ClearNotes()
	return _u
}

// AddAccountIDs adds the "accounts" edge to the Account entity by IDs.
func (_u *ModelCatalogEntryUpdate) AddAccountIDs(ids ...int64) *ModelCatalogEntryUpdate {
	_u.mutation.AddAccountIDs(ids...)
	return _u
}

// AddAccounts adds the "accounts" edges to the Account entity.
func (_u *ModelCatalogEntryUpdate) AddAccounts(v ...*Account) *ModelCatalogEntryUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAccountIDs(ids...)
}

// Mutation returns the ModelCatalogEntryMutation object of the builder.
func (_u *ModelCatalogEntryUpdate) Mutation() *ModelCatalogEntryMutation {
	return _u.mutation
}

// ClearAccounts clears all "accounts" edges to the Account entity.
func (_u *ModelCatalogEntryUpdate) ClearAccounts() *ModelCatalogEntryUpdate {
	_u.mutation.ClearAccounts()
	return _u
}

// RemoveAccountIDs removes the "accounts" edge to Account entities by IDs.
func (_u *ModelCatalogEntryUpdate) RemoveAccountIDs(ids ...int64) *ModelCatalogEntryUpdate {
	_u.mutation.RemoveAccountIDs(ids...)
	return _u
}

// RemoveAccounts removes "accounts" edges to Account entities.
func (_u *ModelCatalogEntryUpdate) RemoveAccounts(v ...*Account) *ModelCatalogEntryUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAccountIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ModelCatalogEntryUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ModelCatalogEntryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ModelCatalogEntryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ModelCatalogEntryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ModelCatalogEntryUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := modelcatalogentry.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ModelCatalogEntryUpdate) check() error {
	if v, ok := _u.mutation.ModelID(); ok {
		if err := modelcatalogentry.ModelIDValidator(v); err != nil {
			return &ValidationError{Name: "model_id", err: fmt.Errorf(`ent: validator failed for field "ModelCatalogEntry.model_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DisplayName(); ok {
		if err := modelcatalogentry.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "ModelCatalogEntry.display_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Vendor(); ok {
		if err := modelcatalogentry.VendorValidator(v); err != nil {
			return &ValidationError{Name: "vendor", err: fmt.Errorf(`ent: validator failed for field "ModelCatalogEntry.vendor": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BillingMode(); ok {
		if err := modelcatalogentry.BillingModeValidator(v); err != nil {
			return &ValidationError{Name: "billing_mode", err: fmt.Errorf(`ent: validator failed for field "ModelCatalogEntry.billing_mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := modelcatalogentry.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ModelCatalogEntry.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ManagedBy(); ok {
		if err := modelcatalogentry.ManagedByValidator(v); err != nil {
			return &ValidationError{Name: "managed_by", err: fmt.Errorf(`ent: validator failed for field "ModelCatalogEntry.managed_by": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RoutePlatform(); ok {
		if err := modelcatalogentry.RoutePlatformValidator(v); err != nil {
			return &ValidationError{Name: "route_platform", err: fmt.Errorf(`ent: validator failed for field "ModelCatalogEntry.route_platform": %w`, err)}
		}
	}
	return nil
}

func (_u *ModelCatalogEntryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(modelcatalogentry.Table, modelcatalogentry.Columns, sqlgraph.NewFieldSpec(modelcatalogentry.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(modelcatalogentry.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ModelID(); ok {
		_spec.SetField(modelcatalogentry.FieldModelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(modelcatalogentry.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Vendor(); ok {
		_spec.SetField(modelcatalogentry.FieldVendor, field.TypeString, value)
	}
	if value, ok := _u.mutation.Protocols(); ok {
		_spec.SetField(modelcatalogentry.FieldProtocols, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedProtocols(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, modelcatalogentry.FieldProtocols, value)
		})
	}
	if _u.mutation.ProtocolsCleared() {
		_spec.ClearField(modelcatalogentry.FieldProtocols, field.TypeJSON)
	}
	if value, ok := _u.mutation.BillingMode(); ok {
		_spec.SetField(modelcatalogentry.FieldBillingMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(modelcatalogentry.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ManagedBy(); ok {
		_spec.SetField(modelcatalogentry.FieldManagedBy, field.TypeString, value)
	}
	if value, ok := _u.mutation.RoutePlatform(); ok {
		_spec.SetField(modelcatalogentry.FieldRoutePlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.InputPrice(); ok {
		_spec.SetField(modelcatalogentry.FieldInputPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedInputPrice(); ok {
		_spec.AddField(modelcatalogentry.FieldInputPrice, field.TypeFloat64, value)
	}
	if _u.mutation.InputPriceCleared() {
		_spec.ClearField(modelcatalogentry.FieldInputPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.OutputPrice(); ok {
		_spec.SetField(modelcatalogentry.FieldOutputPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOutputPrice(); ok {
		_spec.AddField(modelcatalogentry.FieldOutputPrice, field.TypeFloat64, value)
	}
	if _u.mutation.OutputPriceCleared() {
		_spec.ClearField(modelcatalogentry.FieldOutputPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.CacheWritePrice(); ok {
		_spec.SetField(modelcatalogentry.FieldCacheWritePrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCacheWritePrice(); ok {
		_spec.AddField(modelcatalogentry.FieldCacheWritePrice, field.TypeFloat64, value)
	}
	if _u.mutation.CacheWritePriceCleared() {
		_spec.ClearField(modelcatalogentry.FieldCacheWritePrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.CacheWrite1hPrice(); ok {
		_spec.SetField(modelcatalogentry.FieldCacheWrite1hPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCacheWrite1hPrice(); ok {
		_spec.AddField(modelcatalogentry.FieldCacheWrite1hPrice, field.TypeFloat64, value)
	}
	if _u.mutation.CacheWrite1hPriceCleared() {
		_spec.ClearField(modelcatalogentry.FieldCacheWrite1hPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.CacheReadPrice(); ok {
		_spec.SetField(modelcatalogentry.FieldCacheReadPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCacheReadPrice(); ok {
		_spec.AddField(modelcatalogentry.FieldCacheReadPrice, field.TypeFloat64, value)
	}
	if _u.mutation.CacheReadPriceCleared() {
		_spec.ClearField(modelcatalogentry.FieldCacheReadPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ImageInputPrice(); ok {
		_spec.SetField(modelcatalogentry.FieldImageInputPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedImageInputPrice(); ok {
		_spec.AddField(modelcatalogentry.FieldImageInputPrice, field.TypeFloat64, value)
	}
	if _u.mutation.ImageInputPriceCleared() {
		_spec.ClearField(modelcatalogentry.FieldImageInputPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ImageOutputPrice(); ok {
		_spec.SetField(modelcatalogentry.FieldImageOutputPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedImageOutputPrice(); ok {
		_spec.AddField(modelcatalogentry.FieldImageOutputPrice, field.TypeFloat64, value)
	}
	if _u.mutation.ImageOutputPriceCleared() {
		_spec.ClearField(modelcatalogentry.FieldImageOutputPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ImageCacheReadPrice(); ok {
		_spec.SetField(modelcatalogentry.FieldImageCacheReadPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedImageCacheReadPrice(); ok {
		_spec.AddField(modelcatalogentry.FieldImageCacheReadPrice, field.TypeFloat64, value)
	}
	if _u.mutation.ImageCacheReadPriceCleared() {
		_spec.ClearField(modelcatalogentry.FieldImageCacheReadPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.InputPricePriority(); ok {
		_spec.SetField(modelcatalogentry.FieldInputPricePriority, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedInputPricePriority(); ok {
		_spec.AddField(modelcatalogentry.FieldInputPricePriority, field.TypeFloat64, value)
	}
	if _u.mutation.InputPricePriorityCleared() {
		_spec.ClearField(modelcatalogentry.FieldInputPricePriority, field.TypeFloat64)
	}
	if value, ok := _u.mutation.OutputPricePriority(); ok {
		_spec.SetField(modelcatalogentry.FieldOutputPricePriority, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOutputPricePriority(); ok {
		_spec.AddField(modelcatalogentry.FieldOutputPricePriority, field.TypeFloat64, value)
	}
	if _u.mutation.OutputPricePriorityCleared() {
		_spec.ClearField(modelcatalogentry.FieldOutputPricePriority, field.TypeFloat64)
	}
	if value, ok := _u.mutation.CacheWritePricePriority(); ok {
		_spec.SetField(modelcatalogentry.FieldCacheWritePricePriority, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCacheWritePricePriority(); ok {
		_spec.AddField(modelcatalogentry.FieldCacheWritePricePriority, field.TypeFloat64, value)
	}
	if _u.mutation.CacheWritePricePriorityCleared() {
		_spec.ClearField(modelcatalogentry.FieldCacheWritePricePriority, field.TypeFloat64)
	}
	if value, ok := _u.mutation.CacheReadPricePriority(); ok {
		_spec.SetField(modelcatalogentry.FieldCacheReadPricePriority, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCacheReadPricePriority(); ok {
		_spec.AddField(modelcatalogentry.FieldCacheReadPricePriority, field.TypeFloat64, value)
	}
	if _u.mutation.CacheReadPricePriorityCleared() {
		_spec.ClearField(modelcatalogentry.FieldCacheReadPricePriority, field.TypeFloat64)
	}
	if value, ok := _u.mutation.PerRequestPrice(); ok {
		_spec.SetField(modelcatalogentry.FieldPerRequestPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPerRequestPrice(); ok {
		_spec.AddField(modelcatalogentry.FieldPerRequestPrice, field.TypeFloat64, value)
	}
	if _u.mutation.PerRequestPriceCleared() {
		_spec.ClearField(modelcatalogentry.FieldPerRequestPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.LongContextInputThreshold(); ok {
		_spec.SetField(modelcatalogentry.FieldLongContextInputThreshold, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLongContextInputThreshold(); ok {
		_spec.AddField(modelcatalogentry.FieldLongContextInputThreshold, field.TypeInt, value)
	}
	if _u.mutation.LongContextInputThresholdCleared() {
		_spec.ClearField(modelcatalogentry.FieldLongContextInputThreshold, field.TypeInt)
	}
	if value, ok := _u.mutation.LongContextThresholdInclusive(); ok {
		_spec.SetField(modelcatalogentry.FieldLongContextThresholdInclusive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LongContextInputMultiplier(); ok {
		_spec.SetField(modelcatalogentry.FieldLongContextInputMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLongContextInputMultiplier(); ok {
		_spec.AddField(modelcatalogentry.FieldLongContextInputMultiplier, field.TypeFloat64, value)
	}
	if _u.mutation.LongContextInputMultiplierCleared() {
		_spec.ClearField(modelcatalogentry.FieldLongContextInputMultiplier, field.TypeFloat64)
	}
	if value, ok := _u.mutation.LongContextOutputMultiplier(); ok {
		_spec.SetField(modelcatalogentry.FieldLongContextOutputMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLongContextOutputMultiplier(); ok {
		_spec.AddField(modelcatalogentry.FieldLongContextOutputMultiplier, field.TypeFloat64, value)
	}
	if _u.mutation.LongContextOutputMultiplierCleared() {
		_spec.ClearField(modelcatalogentry.FieldLongContextOutputMultiplier, field.TypeFloat64)
	}
	if value, ok := _u.mutation.FastMultiplier(); ok {
		_spec.SetField(modelcatalogentry.FieldFastMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedFastMultiplier(); ok {
		_spec.AddField(modelcatalogentry.FieldFastMultiplier, field.TypeFloat64, value)
	}
	if _u.mutation.FastMultiplierCleared() {
		_spec.ClearField(modelcatalogentry.FieldFastMultiplier, field.TypeFloat64)
	}
	if value, ok := _u.mutation.FlexMultiplier(); ok {
		_spec.SetField(modelcatalogentry.FieldFlexMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedFlexMultiplier(); ok {
		_spec.AddField(modelcatalogentry.FieldFlexMultiplier, field.TypeFloat64, value)
	}
	if _u.mutation.FlexMultiplierCleared() {
		_spec.ClearField(modelcatalogentry.FieldFlexMultiplier, field.TypeFloat64)
	}
	if value, ok := _u.mutation.MaxReasoningEffortMultiplier(); ok {
		_spec.SetField(modelcatalogentry.FieldMaxReasoningEffortMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMaxReasoningEffortMultiplier(); ok {
		_spec.AddField(modelcatalogentry.FieldMaxReasoningEffortMultiplier, field.TypeFloat64, value)
	}
	if _u.mutation.MaxReasoningEffortMultiplierCleared() {
		_spec.ClearField(modelcatalogentry.FieldMaxReasoningEffortMultiplier, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(modelcatalogentry.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(modelcatalogentry.FieldNotes, field.TypeString)
	}
	if _u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   modelcatalogentry.AccountsTable,
			Columns: modelcatalogentry.AccountsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		createE := &ModelCatalogBindingCreate{config: _u.config, mutation: newModelCatalogBindingMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAccountsIDs(); len(nodes) > 0 && !_u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   modelcatalogentry.AccountsTable,
			Columns: modelcatalogentry.AccountsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &ModelCatalogBindingCreate{config: _u.config, mutation: newModelCatalogBindingMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   modelcatalogentry.AccountsTable,
			Columns: modelcatalogentry.AccountsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &ModelCatalogBindingCreate{config: _u.config, mutation: newModelCatalogBindingMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{modelcatalogentry.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ModelCatalogEntryUpdateOne is the builder for updating a single ModelCatalogEntry entity.
type ModelCatalogEntryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ModelCatalogEntryMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ModelCatalogEntryUpdateOne) SetUpdatedAt(v time.Time) *ModelCatalogEntryUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetModelID sets the "model_id" field.
func (_u *ModelCatalogEntryUpdateOne) SetModelID(v string) *ModelCatalogEntryUpdateOne {
	_u.mutation.SetModelID(v)
	return _u
}

// SetNillableModelID sets the "model_id" field if the given value is not nil.
func (_u *ModelCatalogEntryUpdateOne) SetNillableModelID(v *string) *ModelCatalogEntryUpdateOne {
	if v != nil {
		_u.SetModelID(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *ModelCatalogEntryUpdateOne) SetDisplayName(v string) *ModelCatalogEntryUpdateOne {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *ModelCatalogEntryUpdateOne) SetNillableDisplayName(v *string) *ModelCatalogEntryUpdateOne {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// SetVendor sets the "vendor" field.
func (_u *ModelCatalogEntryUpdateOne) SetVendor(v string) *ModelCatalogEntryUpdateOne {
	_u.mutation.SetVendor(v)
	return _u
}

// SetNillableVendor sets the "vendor" field if the given value is not nil.
func (_u *ModelCatalogEntryUpdateOne) SetNillableVendor(v *string) *ModelCatalogEntryUpdateOne {
	if v != nil {
		_u.SetVendor(*v)
	}
	return _u
}

// SetProtocols sets the "protocols" field.
func (_u *ModelCatalogEntryUpdateOne) SetProtocols(v []string) *ModelCatalogEntryUpdateOne {
	_u.mutation.SetProtocols(v)
	return _u
}

// AppendProtocols appends value to the "protocols" field.
func (_u *ModelCatalogEntryUpdateOne) AppendProtocols(v []string) *ModelCatalogEntryUpdateOne {
	_u.mutation.AppendProtocols(v)
	return _u
}

// ClearProtocols clears the value of the "protocols" field.
func (_u *ModelCatalogEntryUpdateOne) ClearProtocols() *ModelCatalogEntryUpdateOne {
	_u.mutation.ClearProtocols()
	return _u
}

// SetBillingMode sets the "billing_mode" field.
func (_u *ModelCatalogEntryUpdateOne) SetBillingMode(v string) *ModelCatalogEntryUpdateOne {
	_u.mutation.SetBillingMode(v)
	return _u
}

// SetNillableBillingMode sets the "billing_mode" field if the given value is not nil.
func (_u *ModelCatalogEntryUpdateOne) SetNillableBillingMode(v *string) *ModelCatalogEntryUpdateOne {
	if v != nil {
		_u.SetBillingMode(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ModelCatalogEntryUpdateOne) SetStatus(v string) *ModelCatalogEntryUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ModelCatalogEntryUpdateOne) SetNillableStatus(v *string) *ModelCatalogEntryUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetManagedBy sets the "managed_by" field.
func (_u *ModelCatalogEntryUpdateOne) SetManagedBy(v string) *ModelCatalogEntryUpdateOne {
	_u.mutation.SetManagedBy(v)
	return _u
}

// SetNillableManagedBy sets the "managed_by" field if the given value is not nil.
func (_u *ModelCatalogEntryUpdateOne) SetNillableManagedBy(v *string) *ModelCatalogEntryUpdateOne {
	if v != nil {
		_u.SetManagedBy(*v)
	}
	return _u
}

// SetRoutePlatform sets the "route_platform" field.
func (_u *ModelCatalogEntryUpdateOne) SetRoutePlatform(v string) *ModelCatalogEntryUpdateOne {
	_u.mutation.SetRoutePlatform(v)
	return _u
}

// SetNillableRoutePlatform sets the "route_platform" field if the given value is not nil.
func (_u *ModelCatalogEntryUpdateOne) SetNillableRoutePlatform(v *string) *ModelCatalogEntryUpdateOne {
	if v != nil {
		_u.SetRoutePlatform(*v)
	}
	return _u
}

// SetInputPrice sets the "input_price" field.
func (_u *ModelCatalogEntryUpdateOne) SetInputPrice(v float64) *ModelCatalogEntryUpdateOne {
	_u.mutation.ResetInputPrice()
	_u.mutation.SetInputPrice(v)
	return _u
}

// SetNillableInputPrice sets the "input_price" field if the given value is not nil.
func (_u *ModelCatalogEntryUpdateOne) SetNillableInputPrice(v *float64) *ModelCatalogEntryUpdateOne {
	if v != nil {
		_u.SetInputPrice(*v)
	}
	return _u
}

// AddInputPrice adds value to the "input_price" field.
func (_u *ModelCatalogEntryUpdateOne) AddInputPrice(v float64) *ModelCatalogEntryUpdateOne {
	_u.mutation.AddInputPrice(v)
	return _u
}

// ClearInputPrice clears the value of the "input_price" field.
func (_u *ModelCatalogEntryUpdateOne) ClearInputPrice() *ModelCatalogEntryUpdateOne {
	_u.mutation.ClearInputPrice()
	return _u
}

// SetOutputPrice sets the "output_price" field.
func (_u *ModelCatalogEntryUpdateOne) SetOutputPrice(v float64) *ModelCatalogEntryUpdateOne {
	_u.mutation.ResetOutputPrice()
	_u.mutation.SetOutputPrice(v)
	return _u
}

// SetNillableOutputPrice sets the "output_price" field if the given value is not nil.
func (_u *ModelCatalogEntryUpdateOne) SetNillableOutputPrice(v *float64) *ModelCatalogEntryUpdateOne {
	if v != nil {
		_u.SetOutputPrice(*v)
	}
	return _u
}

// AddOutputPrice adds value to the "output_price" field.
func (_u *ModelCatalogEntryUpdateOne) AddOutputPrice(v float64) *ModelCatalogEntryUpdateOne {
	_u.mutation.AddOutputPrice(v)
	return _u
}

// ClearOutputPrice clears the value of the "output_price" field.
func (_u *ModelCatalogEntryUpdateOne) ClearOutputPrice() *ModelCatalogEntryUpdateOne {
	_u.mutation.ClearOutputPrice()
	return _u
}

// SetCacheWritePrice sets the "cache_write_price" field.
func (_u *ModelCatalogEntryUpdateOne) SetCacheWritePrice(v float64) *ModelCatalogEntryUpdateOne {
	_u.mutation.ResetCacheWritePrice()
	_u.mutation.SetCacheWritePrice(v)
	return _u
}

// SetNillableCacheWritePrice sets the "cache_write_price" field if the given value is not nil.
func (_u *ModelCatalogEntryUpdateOne) SetNillableCacheWritePrice(v *float64) *ModelCatalogEntryUpdateOne {
	if v != nil {
		_u.SetCacheWritePrice(*v)
	}
	return _u
}

// AddCacheWritePrice adds value to the "cache_write_price" field.
func (_u *ModelCatalogEntryUpdateOne) AddCacheWritePrice(v float64) *ModelCatalogEntryUpdateOne {
	_u.mutation.AddCacheWritePrice(v)
	return _u
}

// ClearCacheWritePrice clears the value of the "cache_write_price" field.
func (_u *ModelCatalogEntryUpdateOne) ClearCacheWritePrice() *ModelCatalogEntryUpdateOne {
	_u.mutation.ClearCacheWritePrice()
	return _u
}

// SetCacheWrite1hPrice sets the "cache_write_1h_price" field.
func (_u *ModelCatalogEntryUpdateOne) SetCacheWrite1hPrice(v float64) *ModelCatalogEntryUpdateOne {
	_u.mutation.ResetCacheWrite1hPrice()
	_u.mutation.SetCacheWrite1hPrice(v)
	return _u
}

// SetNillableCacheWrite1hPrice sets the "cache_write_1h_price" field if the given value is not nil.
func (_u *ModelCatalogEntryUpdateOne) SetNillableCacheWrite1hPrice(v *float64) *ModelCatalogEntryUpdateOne {
	if v != nil {
		_u.SetCacheWrite1hPrice(*v)
	}
	return _u
}

// AddCacheWrite1hPrice adds value to the "cache_write_1h_price" field.
func (_u *ModelCatalogEntryUpdateOne) AddCacheWrite1hPrice(v float64) *ModelCatalogEntryUpdateOne {
	_u.mutation.AddCacheWrite1hPrice(v)
	return _u
}

// ClearCacheWrite1hPrice clears the value of the "cache_write_1h_price" field.
func (_u *ModelCatalogEntryUpdateOne) ClearCacheWrite1hPrice() *ModelCatalogEntryUpdateOne {
	_u.mutation.ClearCacheWrite1hPrice()
	return _u
}

// SetCacheReadPrice sets the "cache_read_price" field.
func (_u *ModelCatalogEntryUpdateOne) SetCacheReadPrice(v float64) *ModelCatalogEntryUpdateOne {
	_u.mutation.ResetCacheReadPrice()
	_u.mutation.SetCacheReadPrice(v)
	return _u
}

// SetNillableCacheReadPrice sets the "cache_read_price" field if the given value is not nil.
func (_u *ModelCatalogEntryUpdateOne) SetNillableCacheReadPrice(v *float64) *ModelCatalogEntryUpdateOne {
	if v != nil {
		_u.SetCacheReadPrice(*v)
	}
	return _u
}

// AddCacheReadPrice adds value to the "cache_read_price" field.
func (_u *ModelCatalogEntryUpdateOne) AddCacheReadPrice(v float64) *ModelCatalogEntryUpdateOne {
	_u.mutation.AddCacheReadPrice(v)
	return _u
}

// ClearCacheReadPrice clears the value of the "cache_read_price" field.
func (_u *ModelCatalogEntryUpdateOne) ClearCacheReadPrice() *ModelCatalogEntryUpdateOne {
	_u.mutation.ClearCacheReadPrice()
	return _u
}

// SetImageInputPrice sets the "image_input_price" field.
func (_u *ModelCatalogEntryUpdateOne) SetImageInputPrice(v float64) *ModelCatalogEntryUpdateOne {
	_u.mutation.ResetImageInputPrice()
	_u.mutation.SetImageInputPrice(v)
	return _u
}

// SetNillableImageInputPrice sets the "image_input_price" field if the given value is not nil.
func (_u *ModelCatalogEntryUpdateOne) SetNillableImageInputPrice(v *float64) *ModelCatalogEntryUpdateOne {
	if v != nil {
		_u.SetImageInputPrice(*v)
	}
	return _u
}

// AddImageInputPrice adds value to the "image_input_price" field.
func (_u *ModelCatalogEntryUpdateOne) AddImageInputPrice(v float64) *ModelCatalogEntryUpdateOne {
	_u.mutation.AddImageInputPrice(v)
	return _u
}

// ClearImageInputPrice clears the value of the "image_input_price" field.
func (_u *ModelCatalogEntryUpdateOne) ClearImageInputPrice() *ModelCatalogEntryUpdateOne {
	_u.mutation.ClearImageInputPrice()
	return _u
}

// SetImageOutputPrice sets the "image_output_price" field.
func (_u *ModelCatalogEntryUpdateOne) SetImageOutputPrice(v float64) *ModelCatalogEntryUpdateOne {
	_u.mutation.ResetImageOutputPrice()
	_u.mutation.SetImageOutputPrice(v)
	return _u
}

// SetNillableImageOutputPrice sets the "image_output_price" field if the given value is not nil.
func (_u *ModelCatalogEntryUpdateOne) SetNillableImageOutputPrice(v *float64) *ModelCatalogEntryUpdateOne {
	if v != nil {
		_u.SetImageOutputPrice(*v)
	}
	return _u
}

// AddImageOutputPrice adds value to the "image_output_price" field.
func (_u *ModelCatalogEntryUpdateOne) AddImageOutputPrice(v float64) *ModelCatalogEntryUpdateOne {
	_u.mutation.AddImageOutputPrice(v)
	return _u
}

// ClearImageOutputPrice clears the value of the "image_output_price" field.
func (_u *ModelCatalogEntryUpdateOne) ClearImageOutputPrice() *ModelCatalogEntryUpdateOne {
	_u.mutation.ClearImageOutputPrice()
	return _u
}

// SetImageCacheReadPrice sets the "image_cache_read_price" field.
func (_u *ModelCatalogEntryUpdateOne) SetImageCacheReadPrice(v float64) *ModelCatalogEntryUpdateOne {
	_u.mutation.ResetImageCacheReadPrice()
	_u.mutation.SetImageCacheReadPrice(v)
	return _u
}

// SetNillableImageCacheReadPrice sets the "image_cache_read_price" field if the given value is not nil.
func (_u *ModelCatalogEntryUpdateOne) SetNillableImageCacheReadPrice(v *float64) *ModelCatalogEntryUpdateOne {
	if v != nil {
		_u.SetImageCacheReadPrice(*v)
	}
	return _u
}

// AddImageCacheReadPrice adds value to the "image_cache_read_price" field.
func (_u *ModelCatalogEntryUpdateOne) AddImageCacheReadPrice(v float64) *ModelCatalogEntryUpdateOne {
	_u.mutation.AddImageCacheReadPrice(v)
	return _u
}

// ClearImageCacheReadPrice clears the value of the "image_cache_read_price" field.
func (_u *ModelCatalogEntryUpdateOne) ClearImageCacheReadPrice() *ModelCatalogEntryUpdateOne {
	_u.mutation.ClearImageCacheReadPrice()
	return _u
}

// SetInputPricePriority sets the "input_price_priority" field.
func (_u *ModelCatalogEntryUpdateOne) SetInputPricePriority(v float64) *ModelCatalogEntryUpdateOne {
	_u.mutation.ResetInputPricePriority()
	_u.mutation.SetInputPricePriority(v)
	return _u
}

// SetNillableInputPricePriority sets the "input_price_priority" field if the given value is not nil.
func (_u *ModelCatalogEntryUpdateOne) SetNillableInputPricePriority(v *float64) *ModelCatalogEntryUpdateOne {
	if v != nil {
		_u.SetInputPricePriority(*v)
	}
	return _u
}

// AddInputPricePriority adds value to the "input_price_priority" field.
func (_u *ModelCatalogEntryUpdateOne) AddInputPricePriority(v float64) *ModelCatalogEntryUpdateOne {
	_u.mutation.AddInputPricePriority(v)
	return _u
}

// ClearInputPricePriority clears the value of the "input_price_priority" field.
func (_u *ModelCatalogEntryUpdateOne) ClearInputPricePriority() *ModelCatalogEntryUpdateOne {
	_u.mutation.ClearInputPricePriority()
	return _u
}

// SetOutputPricePriority sets the "output_price_priority" field.
func (_u *ModelCatalogEntryUpdateOne) SetOutputPricePriority(v float64) *ModelCatalogEntryUpdateOne {
	_u.mutation.ResetOutputPricePriority()
	_u.mutation.SetOutputPricePriority(v)
	return _u
}

// SetNillableOutputPricePriority sets the "output_price_priority" field if the given value is not nil.
func (_u *ModelCatalogEntryUpdateOne) SetNillableOutputPricePriority(v *float64) *ModelCatalogEntryUpdateOne {
	if v != nil {
		_u.SetOutputPricePriority(*v)
	}
	return _u
}

// AddOutputPricePriority adds value to the "output_price_priority" field.
func (_u *ModelCatalogEntryUpdateOne) AddOutputPricePriority(v float64) *ModelCatalogEntryUpdateOne {
	_u.mutation.AddOutputPricePriority(v)
	return _u
}

// ClearOutputPricePriority clears the value of the "output_price_priority" field.
func (_u *ModelCatalogEntryUpdateOne) ClearOutputPricePriority() *ModelCatalogEntryUpdateOne {
	_u.mutation.ClearOutputPricePriority()
	return _u
}

// SetCacheWritePricePriority sets the "cache_write_price_priority" field.
func (_u *ModelCatalogEntryUpdateOne) SetCacheWritePricePriority(v float64) *ModelCatalogEntryUpdateOne {
	_u.mutation.ResetCacheWritePricePriority()
	_u.mutation.SetCacheWritePricePriority(v)
	return _u
}

// SetNillableCacheWritePricePriority sets the "cache_write_price_priority" field if the given value is not nil.
func (_u *ModelCatalogEntryUpdateOne) SetNillableCacheWritePricePriority(v *float64) *ModelCatalogEntryUpdateOne {
	if v != nil {
		_u.SetCacheWritePricePriority(*v)
	}
	return _u
}

// AddCacheWritePricePriority adds value to the "cache_write_price_priority" field.
func (_u *ModelCatalogEntryUpdateOne) AddCacheWritePricePriority(v float64) *ModelCatalogEntryUpdateOne {
	_u.mutation.AddCacheWritePricePriority(v)
	return _u
}

// ClearCacheWritePricePriority clears the value of the "cache_write_price_priority" field.
func (_u *ModelCatalogEntryUpdateOne) ClearCacheWritePricePriority() *ModelCatalogEntryUpdateOne {
	_u.mutation.ClearCacheWritePricePriority()
	return _u
}

// SetCacheReadPricePriority sets the "cache_read_price_priority" field.
func (_u *ModelCatalogEntryUpdateOne) SetCacheReadPricePriority(v float64) *ModelCatalogEntryUpdateOne {
	_u.mutation.ResetCacheReadPricePriority()
	_u.mutation.SetCacheReadPricePriority(v)
	return _u
}

// SetNillableCacheReadPricePriority sets the "cache_read_price_priority" field if the given value is not nil.
func (_u *ModelCatalogEntryUpdateOne) SetNillableCacheReadPricePriority(v *float64) *ModelCatalogEntryUpdateOne {
	if v != nil {
		_u.SetCacheReadPricePriority(*v)
	}
	return _u
}

// AddCacheReadPricePriority adds value to the "cache_read_price_priority" field.
func (_u *ModelCatalogEntryUpdateOne) AddCacheReadPricePriority(v float64) *ModelCatalogEntryUpdateOne {
	_u.mutation.AddCacheReadPricePriority(v)
	return _u
}

// ClearCacheReadPricePriority clears the value of the "cache_read_price_priority" field.
func (_u *ModelCatalogEntryUpdateOne) ClearCacheReadPricePriority() *ModelCatalogEntryUpdateOne {
	_u.mutation.ClearCacheReadPricePriority()
	return _u
}

// SetPerRequestPrice sets the "per_request_price" field.
func (_u *ModelCatalogEntryUpdateOne) SetPerRequestPrice(v float64) *ModelCatalogEntryUpdateOne {
	_u.mutation.ResetPerRequestPrice()
	_u.mutation.SetPerRequestPrice(v)
	return _u
}

// SetNillablePerRequestPrice sets the "per_request_price" field if the given value is not nil.
func (_u *ModelCatalogEntryUpdateOne) SetNillablePerRequestPrice(v *float64) *ModelCatalogEntryUpdateOne {
	if v != nil {
		_u.SetPerRequestPrice(*v)
	}
	return _u
}

// AddPerRequestPrice adds value to the "per_request_price" field.
func (_u *ModelCatalogEntryUpdateOne) AddPerRequestPrice(v float64) *ModelCatalogEntryUpdateOne {
	_u.mutation.AddPerRequestPrice(v)
	return _u
}

// ClearPerRequestPrice clears the value of the "per_request_price" field.
func (_u *ModelCatalogEntryUpdateOne) ClearPerRequestPrice() *ModelCatalogEntryUpdateOne {
	_u.mutation.ClearPerRequestPrice()
	return _u
}

// SetLongContextInputThreshold sets the "long_context_input_threshold" field.
func (_u *ModelCatalogEntryUpdateOne) SetLongContextInputThreshold(v int) *ModelCatalogEntryUpdateOne {
	_u.mutation.ResetLongContextInputThreshold()
	_u.mutation.SetLongContextInputThreshold(v)
	return _u
}

// SetNillableLongContextInputThreshold sets the "long_context_input_threshold" field if the given value is not nil.
func (_u *ModelCatalogEntryUpdateOne) SetNillableLongContextInputThreshold(v *int) *ModelCatalogEntryUpdateOne {
	if v != nil {
		_u.SetLongContextInputThreshold(*v)
	}
	return _u
}

// AddLongContextInputThreshold adds value to the "long_context_input_threshold" field.
func (_u *ModelCatalogEntryUpdateOne) AddLongContextInputThreshold(v int) *ModelCatalogEntryUpdateOne {
	_u.mutation.AddLongContextInputThreshold(v)
	return _u
}

// ClearLongContextInputThreshold clears the value of the "long_context_input_threshold" field.
func (_u *ModelCatalogEntryUpdateOne) ClearLongContextInputThreshold() *ModelCatalogEntryUpdateOne {
	_u.mutation.ClearLongContextInputThreshold()
	return _u
}

// SetLongContextThresholdInclusive sets the "long_context_threshold_inclusive" field.
func (_u *ModelCatalogEntryUpdateOne) SetLongContextThresholdInclusive(v bool) *ModelCatalogEntryUpdateOne {
	_u.mutation.SetLongContextThresholdInclusive(v)
	return _u
}

// SetNillableLongContextThresholdInclusive sets the "long_context_threshold_inclusive" field if the given value is not nil.
func (_u *ModelCatalogEntryUpdateOne) SetNillableLongContextThresholdInclusive(v *bool) *ModelCatalogEntryUpdateOne {
	if v != nil {
		_u.SetLongContextThresholdInclusive(*v)
	}
	return _u
}

// SetLongContextInputMultiplier sets the "long_context_input_multiplier" field.
func (_u *ModelCatalogEntryUpdateOne) SetLongContextInputMultiplier(v float64) *ModelCatalogEntryUpdateOne {
	_u.mutation.ResetLongContextInputMultiplier()
	_u.mutation.SetLongContextInputMultiplier(v)
	return _u
}

// SetNillableLongContextInputMultiplier sets the "long_context_input_multiplier" field if the given value is not nil.
func (_u *ModelCatalogEntryUpdateOne) SetNillableLongContextInputMultiplier(v *float64) *ModelCatalogEntryUpdateOne {
	if v != nil {
		_u.SetLongContextInputMultiplier(*v)
	}
	return _u
}

// AddLongContextInputMultiplier adds value to the "long_context_input_multiplier" field.
func (_u *ModelCatalogEntryUpdateOne) AddLongContextInputMultiplier(v float64) *ModelCatalogEntryUpdateOne {
	_u.mutation.AddLongContextInputMultiplier(v)
	return _u
}

// ClearLongContextInputMultiplier clears the value of the "long_context_input_multiplier" field.
func (_u *ModelCatalogEntryUpdateOne) ClearLongContextInputMultiplier() *ModelCatalogEntryUpdateOne {
	_u.mutation.ClearLongContextInputMultiplier()
	return _u
}

// SetLongContextOutputMultiplier sets the "long_context_output_multiplier" field.
func (_u *ModelCatalogEntryUpdateOne) SetLongContextOutputMultiplier(v float64) *ModelCatalogEntryUpdateOne {
	_u.mutation.ResetLongContextOutputMultiplier()
	_u.mutation.SetLongContextOutputMultiplier(v)
	return _u
}

// SetNillableLongContextOutputMultiplier sets the "long_context_output_multiplier" field if the given value is not nil.
func (_u *ModelCatalogEntryUpdateOne) SetNillableLongContextOutputMultiplier(v *float64) *ModelCatalogEntryUpdateOne {
	if v != nil {
		_u.SetLongContextOutputMultiplier(*v)
	}
	return _u
}

// AddLongContextOutputMultiplier adds value to the "long_context_output_multiplier" field.
func (_u *ModelCatalogEntryUpdateOne) AddLongContextOutputMultiplier(v float64) *ModelCatalogEntryUpdateOne {
	_u.mutation.AddLongContextOutputMultiplier(v)
	return _u
}

// ClearLongContextOutputMultiplier clears the value of the "long_context_output_multiplier" field.
func (_u *ModelCatalogEntryUpdateOne) ClearLongContextOutputMultiplier() *ModelCatalogEntryUpdateOne {
	_u.mutation.ClearLongContextOutputMultiplier()
	return _u
}

// SetFastMultiplier sets the "fast_multiplier" field.
func (_u *ModelCatalogEntryUpdateOne) SetFastMultiplier(v float64) *ModelCatalogEntryUpdateOne {
	_u.mutation.ResetFastMultiplier()
	_u.mutation.SetFastMultiplier(v)
	return _u
}

// SetNillableFastMultiplier sets the "fast_multiplier" field if the given value is not nil.
func (_u *ModelCatalogEntryUpdateOne) SetNillableFastMultiplier(v *float64) *ModelCatalogEntryUpdateOne {
	if v != nil {
		_u.SetFastMultiplier(*v)
	}
	return _u
}

// AddFastMultiplier adds value to the "fast_multiplier" field.
func (_u *ModelCatalogEntryUpdateOne) AddFastMultiplier(v float64) *ModelCatalogEntryUpdateOne {
	_u.mutation.AddFastMultiplier(v)
	return _u
}

// ClearFastMultiplier clears the value of the "fast_multiplier" field.
func (_u *ModelCatalogEntryUpdateOne) ClearFastMultiplier() *ModelCatalogEntryUpdateOne {
	_u.mutation.ClearFastMultiplier()
	return _u
}

// SetFlexMultiplier sets the "flex_multiplier" field.
func (_u *ModelCatalogEntryUpdateOne) SetFlexMultiplier(v float64) *ModelCatalogEntryUpdateOne {
	_u.mutation.ResetFlexMultiplier()
	_u.mutation.SetFlexMultiplier(v)
	return _u
}

// SetNillableFlexMultiplier sets the "flex_multiplier" field if the given value is not nil.
func (_u *ModelCatalogEntryUpdateOne) SetNillableFlexMultiplier(v *float64) *ModelCatalogEntryUpdateOne {
	if v != nil {
		_u.SetFlexMultiplier(*v)
	}
	return _u
}

// AddFlexMultiplier adds value to the "flex_multiplier" field.
func (_u *ModelCatalogEntryUpdateOne) AddFlexMultiplier(v float64) *ModelCatalogEntryUpdateOne {
	_u.mutation.AddFlexMultiplier(v)
	return _u
}

// ClearFlexMultiplier clears the value of the "flex_multiplier" field.
func (_u *ModelCatalogEntryUpdateOne) ClearFlexMultiplier() *ModelCatalogEntryUpdateOne {
	_u.mutation.ClearFlexMultiplier()
	return _u
}

// SetMaxReasoningEffortMultiplier sets the "max_reasoning_effort_multiplier" field.
func (_u *ModelCatalogEntryUpdateOne) SetMaxReasoningEffortMultiplier(v float64) *ModelCatalogEntryUpdateOne {
	_u.mutation.ResetMaxReasoningEffortMultiplier()
	_u.mutation.SetMaxReasoningEffortMultiplier(v)
	return _u
}

// SetNillableMaxReasoningEffortMultiplier sets the "max_reasoning_effort_multiplier" field if the given value is not nil.
func (_u *ModelCatalogEntryUpdateOne) SetNillableMaxReasoningEffortMultiplier(v *float64) *ModelCatalogEntryUpdateOne {
	if v != nil {
		_u.SetMaxReasoningEffortMultiplier(*v)
	}
	return _u
}

// AddMaxReasoningEffortMultiplier adds value to the "max_reasoning_effort_multiplier" field.
func (_u *ModelCatalogEntryUpdateOne) AddMaxReasoningEffortMultiplier(v float64) *ModelCatalogEntryUpdateOne {
	_u.mutation.AddMaxReasoningEffortMultiplier(v)
	return _u
}

// ClearMaxReasoningEffortMultiplier clears the value of the "max_reasoning_effort_multiplier" field.
func (_u *ModelCatalogEntryUpdateOne) ClearMaxReasoningEffortMultiplier() *ModelCatalogEntryUpdateOne {
	_u.mutation.ClearMaxReasoningEffortMultiplier()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *ModelCatalogEntryUpdateOne) SetNotes(v string) *ModelCatalogEntryUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *ModelCatalogEntryUpdateOne) SetNillableNotes(v *string) *ModelCatalogEntryUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *ModelCatalogEntryUpdateOne) ClearNotes() *ModelCatalogEntryUpdateOne {
	_u.mutation.ClearNotes()
	return _u
}

// AddAccountIDs adds the "accounts" edge to the Account entity by IDs.
func (_u *ModelCatalogEntryUpdateOne) AddAccountIDs(ids ...int64) *ModelCatalogEntryUpdateOne {
	_u.mutation.AddAccountIDs(ids...)
	return _u
}

// AddAccounts adds the "accounts" edges to the Account entity.
func (_u *ModelCatalogEntryUpdateOne) AddAccounts(v ...*Account) *ModelCatalogEntryUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAccountIDs(ids...)
}

// Mutation returns the ModelCatalogEntryMutation object of the builder.
func (_u *ModelCatalogEntryUpdateOne) Mutation() *ModelCatalogEntryMutation {
	return _u.mutation
}

// ClearAccounts clears all "accounts" edges to the Account entity.
func (_u *ModelCatalogEntryUpdateOne) ClearAccounts() *ModelCatalogEntryUpdateOne {
	_u.mutation.ClearAccounts()
	return _u
}

// RemoveAccountIDs removes the "accounts" edge to Account entities by IDs.
func (_u *ModelCatalogEntryUpdateOne) RemoveAccountIDs(ids ...int64) *ModelCatalogEntryUpdateOne {
	_u.mutation.RemoveAccountIDs(ids...)
	return _u
}

// RemoveAccounts removes "accounts" edges to Account entities.
func (_u *ModelCatalogEntryUpdateOne) RemoveAccounts(v ...*Account) *ModelCatalogEntryUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAccountIDs(ids...)
}

// Where appends a list predicates to the ModelCatalogEntryUpdate builder.
func (_u *ModelCatalogEntryUpdateOne) Where(ps ...predicate.ModelCatalogEntry) *ModelCatalogEntryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ModelCatalogEntryUpdateOne) Select(field string, fields ...string) *ModelCatalogEntryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ModelCatalogEntry entity.
func (_u *ModelCatalogEntryUpdateOne) Save(ctx context.Context) (*ModelCatalogEntry, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ModelCatalogEntryUpdateOne) SaveX(ctx context.Context) *ModelCatalogEntry {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ModelCatalogEntryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ModelCatalogEntryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ModelCatalogEntryUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := modelcatalogentry.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ModelCatalogEntryUpdateOne) check() error {
	if v, ok := _u.mutation.ModelID(); ok {
		if err := modelcatalogentry.ModelIDValidator(v); err != nil {
			return &ValidationError{Name: "model_id", err: fmt.Errorf(`ent: validator failed for field "ModelCatalogEntry.model_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DisplayName(); ok {
		if err := modelcatalogentry.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "ModelCatalogEntry.display_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Vendor(); ok {
		if err := modelcatalogentry.VendorValidator(v); err != nil {
			return &ValidationError{Name: "vendor", err: fmt.Errorf(`ent: validator failed for field "ModelCatalogEntry.vendor": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BillingMode(); ok {
		if err := modelcatalogentry.BillingModeValidator(v); err != nil {
			return &ValidationError{Name: "billing_mode", err: fmt.Errorf(`ent: validator failed for field "ModelCatalogEntry.billing_mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := modelcatalogentry.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ModelCatalogEntry.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ManagedBy(); ok {
		if err := modelcatalogentry.ManagedByValidator(v); err != nil {
			return &ValidationError{Name: "managed_by", err: fmt.Errorf(`ent: validator failed for field "ModelCatalogEntry.managed_by": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RoutePlatform(); ok {
		if err := modelcatalogentry.RoutePlatformValidator(v); err != nil {
			return &ValidationError{Name: "route_platform", err: fmt.Errorf(`ent: validator failed for field "ModelCatalogEntry.route_platform": %w`, err)}
		}
	}
	return nil
}

func (_u *ModelCatalogEntryUpdateOne) sqlSave(ctx context.Context) (_node *ModelCatalogEntry, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(modelcatalogentry.Table, modelcatalogentry.Columns, sqlgraph.NewFieldSpec(modelcatalogentry.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ModelCatalogEntry.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, modelcatalogentry.FieldID)
		for _, f := range fields {
			if !modelcatalogentry.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != modelcatalogentry.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(modelcatalogentry.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ModelID(); ok {
		_spec.SetField(modelcatalogentry.FieldModelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(modelcatalogentry.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Vendor(); ok {
		_spec.SetField(modelcatalogentry.FieldVendor, field.TypeString, value)
	}
	if value, ok := _u.mutation.Protocols(); ok {
		_spec.SetField(modelcatalogentry.FieldProtocols, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedProtocols(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, modelcatalogentry.FieldProtocols, value)
		})
	}
	if _u.mutation.ProtocolsCleared() {
		_spec.ClearField(modelcatalogentry.FieldProtocols, field.TypeJSON)
	}
	if value, ok := _u.mutation.BillingMode(); ok {
		_spec.SetField(modelcatalogentry.FieldBillingMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(modelcatalogentry.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ManagedBy(); ok {
		_spec.SetField(modelcatalogentry.FieldManagedBy, field.TypeString, value)
	}
	if value, ok := _u.mutation.RoutePlatform(); ok {
		_spec.SetField(modelcatalogentry.FieldRoutePlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.InputPrice(); ok {
		_spec.SetField(modelcatalogentry.FieldInputPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedInputPrice(); ok {
		_spec.AddField(modelcatalogentry.FieldInputPrice, field.TypeFloat64, value)
	}
	if _u.mutation.InputPriceCleared() {
		_spec.ClearField(modelcatalogentry.FieldInputPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.OutputPrice(); ok {
		_spec.SetField(modelcatalogentry.FieldOutputPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOutputPrice(); ok {
		_spec.AddField(modelcatalogentry.FieldOutputPrice, field.TypeFloat64, value)
	}
	if _u.mutation.OutputPriceCleared() {
		_spec.ClearField(modelcatalogentry.FieldOutputPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.CacheWritePrice(); ok {
		_spec.SetField(modelcatalogentry.FieldCacheWritePrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCacheWritePrice(); ok {
		_spec.AddField(modelcatalogentry.FieldCacheWritePrice, field.TypeFloat64, value)
	}
	if _u.mutation.CacheWritePriceCleared() {
		_spec.ClearField(modelcatalogentry.FieldCacheWritePrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.CacheWrite1hPrice(); ok {
		_spec.SetField(modelcatalogentry.FieldCacheWrite1hPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCacheWrite1hPrice(); ok {
		_spec.AddField(modelcatalogentry.FieldCacheWrite1hPrice, field.TypeFloat64, value)
	}
	if _u.mutation.CacheWrite1hPriceCleared() {
		_spec.ClearField(modelcatalogentry.FieldCacheWrite1hPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.CacheReadPrice(); ok {
		_spec.SetField(modelcatalogentry.FieldCacheReadPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCacheReadPrice(); ok {
		_spec.AddField(modelcatalogentry.FieldCacheReadPrice, field.TypeFloat64, value)
	}
	if _u.mutation.CacheReadPriceCleared() {
		_spec.ClearField(modelcatalogentry.FieldCacheReadPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ImageInputPrice(); ok {
		_spec.SetField(modelcatalogentry.FieldImageInputPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedImageInputPrice(); ok {
		_spec.AddField(modelcatalogentry.FieldImageInputPrice, field.TypeFloat64, value)
	}
	if _u.mutation.ImageInputPriceCleared() {
		_spec.ClearField(modelcatalogentry.FieldImageInputPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ImageOutputPrice(); ok {
		_spec.SetField(modelcatalogentry.FieldImageOutputPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedImageOutputPrice(); ok {
		_spec.AddField(modelcatalogentry.FieldImageOutputPrice, field.TypeFloat64, value)
	}
	if _u.mutation.ImageOutputPriceCleared() {
		_spec.ClearField(modelcatalogentry.FieldImageOutputPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ImageCacheReadPrice(); ok {
		_spec.SetField(modelcatalogentry.FieldImageCacheReadPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedImageCacheReadPrice(); ok {
		_spec.AddField(modelcatalogentry.FieldImageCacheReadPrice, field.TypeFloat64, value)
	}
	if _u.mutation.ImageCacheReadPriceCleared() {
		_spec.ClearField(modelcatalogentry.FieldImageCacheReadPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.InputPricePriority(); ok {
		_spec.SetField(modelcatalogentry.FieldInputPricePriority, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedInputPricePriority(); ok {
		_spec.AddField(modelcatalogentry.FieldInputPricePriority, field.TypeFloat64, value)
	}
	if _u.mutation.InputPricePriorityCleared() {
		_spec.ClearField(modelcatalogentry.FieldInputPricePriority, field.TypeFloat64)
	}
	if value, ok := _u.mutation.OutputPricePriority(); ok {
		_spec.SetField(modelcatalogentry.FieldOutputPricePriority, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOutputPricePriority(); ok {
		_spec.AddField(modelcatalogentry.FieldOutputPricePriority, field.TypeFloat64, value)
	}
	if _u.mutation.OutputPricePriorityCleared() {
		_spec.ClearField(modelcatalogentry.FieldOutputPricePriority, field.TypeFloat64)
	}
	if value, ok := _u.mutation.CacheWritePricePriority(); ok {
		_spec.SetField(modelcatalogentry.FieldCacheWritePricePriority, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCacheWritePricePriority(); ok {
		_spec.AddField(modelcatalogentry.FieldCacheWritePricePriority, field.TypeFloat64, value)
	}
	if _u.mutation.CacheWritePricePriorityCleared() {
		_spec.ClearField(modelcatalogentry.FieldCacheWritePricePriority, field.TypeFloat64)
	}
	if value, ok := _u.mutation.CacheReadPricePriority(); ok {
		_spec.SetField(modelcatalogentry.FieldCacheReadPricePriority, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCacheReadPricePriority(); ok {
		_spec.AddField(modelcatalogentry.FieldCacheReadPricePriority, field.TypeFloat64, value)
	}
	if _u.mutation.CacheReadPricePriorityCleared() {
		_spec.ClearField(modelcatalogentry.FieldCacheReadPricePriority, field.TypeFloat64)
	}
	if value, ok := _u.mutation.PerRequestPrice(); ok {
		_spec.SetField(modelcatalogentry.FieldPerRequestPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPerRequestPrice(); ok {
		_spec.AddField(modelcatalogentry.FieldPerRequestPrice, field.TypeFloat64, value)
	}
	if _u.mutation.PerRequestPriceCleared() {
		_spec.ClearField(modelcatalogentry.FieldPerRequestPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.LongContextInputThreshold(); ok {
		_spec.SetField(modelcatalogentry.FieldLongContextInputThreshold, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLongContextInputThreshold(); ok {
		_spec.AddField(modelcatalogentry.FieldLongContextInputThreshold, field.TypeInt, value)
	}
	if _u.mutation.LongContextInputThresholdCleared() {
		_spec.ClearField(modelcatalogentry.FieldLongContextInputThreshold, field.TypeInt)
	}
	if value, ok := _u.mutation.LongContextThresholdInclusive(); ok {
		_spec.SetField(modelcatalogentry.FieldLongContextThresholdInclusive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LongContextInputMultiplier(); ok {
		_spec.SetField(modelcatalogentry.FieldLongContextInputMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLongContextInputMultiplier(); ok {
		_spec.AddField(modelcatalogentry.FieldLongContextInputMultiplier, field.TypeFloat64, value)
	}
	if _u.mutation.LongContextInputMultiplierCleared() {
		_spec.ClearField(modelcatalogentry.FieldLongContextInputMultiplier, field.TypeFloat64)
	}
	if value, ok := _u.mutation.LongContextOutputMultiplier(); ok {
		_spec.SetField(modelcatalogentry.FieldLongContextOutputMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLongContextOutputMultiplier(); ok {
		_spec.AddField(modelcatalogentry.FieldLongContextOutputMultiplier, field.TypeFloat64, value)
	}
	if _u.mutation.LongContextOutputMultiplierCleared() {
		_spec.ClearField(modelcatalogentry.FieldLongContextOutputMultiplier, field.TypeFloat64)
	}
	if value, ok := _u.mutation.FastMultiplier(); ok {
		_spec.SetField(modelcatalogentry.FieldFastMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedFastMultiplier(); ok {
		_spec.AddField(modelcatalogentry.FieldFastMultiplier, field.TypeFloat64, value)
	}
	if _u.mutation.FastMultiplierCleared() {
		_spec.ClearField(modelcatalogentry.FieldFastMultiplier, field.TypeFloat64)
	}
	if value, ok := _u.mutation.FlexMultiplier(); ok {
		_spec.SetField(modelcatalogentry.FieldFlexMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedFlexMultiplier(); ok {
		_spec.AddField(modelcatalogentry.FieldFlexMultiplier, field.TypeFloat64, value)
	}
	if _u.mutation.FlexMultiplierCleared() {
		_spec.ClearField(modelcatalogentry.FieldFlexMultiplier, field.TypeFloat64)
	}
	if value, ok := _u.mutation.MaxReasoningEffortMultiplier(); ok {
		_spec.SetField(modelcatalogentry.FieldMaxReasoningEffortMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMaxReasoningEffortMultiplier(); ok {
		_spec.AddField(modelcatalogentry.FieldMaxReasoningEffortMultiplier, field.TypeFloat64, value)
	}
	if _u.mutation.MaxReasoningEffortMultiplierCleared() {
		_spec.ClearField(modelcatalogentry.FieldMaxReasoningEffortMultiplier, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(modelcatalogentry.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(modelcatalogentry.FieldNotes, field.TypeString)
	}
	if _u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   modelcatalogentry.AccountsTable,
			Columns: modelcatalogentry.AccountsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		createE := &ModelCatalogBindingCreate{config: _u.config, mutation: newModelCatalogBindingMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAccountsIDs(); len(nodes) > 0 && !_u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   modelcatalogentry.AccountsTable,
			Columns: modelcatalogentry.AccountsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &ModelCatalogBindingCreate{config: _u.config, mutation: newModelCatalogBindingMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   modelcatalogentry.AccountsTable,
			Columns: modelcatalogentry.AccountsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &ModelCatalogBindingCreate{config: _u.config, mutation: newModelCatalogBindingMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ModelCatalogEntry{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{modelcatalogentry.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
