// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/modelcatalogpriceinterval"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ModelCatalogPriceIntervalUpdate is the builder for updating ModelCatalogPriceInterval entities.
type ModelCatalogPriceIntervalUpdate struct {
	config
	hooks    []Hook
	mutation *ModelCatalogPriceIntervalMutation
}

// Where appends a list predicates to the ModelCatalogPriceIntervalUpdate builder.
func (_u *ModelCatalogPriceIntervalUpdate) Where(ps ...predicate.ModelCatalogPriceInterval) *ModelCatalogPriceIntervalUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ModelCatalogPriceIntervalUpdate) SetUpdatedAt(v time.Time) *ModelCatalogPriceIntervalUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetEntryID sets the "entry_id" field.
func (_u *ModelCatalogPriceIntervalUpdate) SetEntryID(v int64) *ModelCatalogPriceIntervalUpdate {
	_u.mutation.ResetEntryID()
	_u.mutation.SetEntryID(v)
	return _u
}

// SetNillableEntryID sets the "entry_id" field if the given value is not nil.
func (_u *ModelCatalogPriceIntervalUpdate) SetNillableEntryID(v *int64) *ModelCatalogPriceIntervalUpdate {
	if v != nil {
		_u.SetEntryID(*v)
	}
	return _u
}

// AddEntryID adds value to the "entry_id" field.
func (_u *ModelCatalogPriceIntervalUpdate) AddEntryID(v int64) *ModelCatalogPriceIntervalUpdate {
	_u.mutation.AddEntryID(v)
	return _u
}

// SetMinTokens sets the "min_tokens" field.
func (_u *ModelCatalogPriceIntervalUpdate) SetMinTokens(v int) *ModelCatalogPriceIntervalUpdate {
	_u.mutation.ResetMinTokens()
	_u.mutation.SetMinTokens(v)
	return _u
}

// SetNillableMinTokens sets the "min_tokens" field if the given value is not nil.
func (_u *ModelCatalogPriceIntervalUpdate) SetNillableMinTokens(v *int) *ModelCatalogPriceIntervalUpdate {
	if v != nil {
		_u.SetMinTokens(*v)
	}
	return _u
}

// AddMinTokens adds value to the "min_tokens" field.
func (_u *ModelCatalogPriceIntervalUpdate) AddMinTokens(v int) *ModelCatalogPriceIntervalUpdate {
	_u.mutation.AddMinTokens(v)
	return _u
}

// SetMaxTokens sets the "max_tokens" field.
func (_u *ModelCatalogPriceIntervalUpdate) SetMaxTokens(v int) *ModelCatalogPriceIntervalUpdate {
	_u.mutation.ResetMaxTokens()
	_u.mutation.SetMaxTokens(v)
	return _u
}

// SetNillableMaxTokens sets the "max_tokens" field if the given value is not nil.
func (_u *ModelCatalogPriceIntervalUpdate) SetNillableMaxTokens(v *int) *ModelCatalogPriceIntervalUpdate {
	if v != nil {
		_u.SetMaxTokens(*v)
	}
	return _u
}

// AddMaxTokens adds value to the "max_tokens" field.
func (_u *ModelCatalogPriceIntervalUpdate) AddMaxTokens(v int) *ModelCatalogPriceIntervalUpdate {
	_u.mutation.AddMaxTokens(v)
	return _u
}

// ClearMaxTokens clears the value of the "max_tokens" field.
func (_u *ModelCatalogPriceIntervalUpdate) ClearMaxTokens() *ModelCatalogPriceIntervalUpdate {
	_u.mutation.ClearMaxTokens()
	return _u
}

// SetTierLabel sets the "tier_label" field.
func (_u *ModelCatalogPriceIntervalUpdate) SetTierLabel(v string) *ModelCatalogPriceIntervalUpdate {
	_u.mutation.SetTierLabel(v)
	return _u
}

// SetNillableTierLabel sets the "tier_label" field if the given value is not nil.
func (_u *ModelCatalogPriceIntervalUpdate) SetNillableTierLabel(v *string) *ModelCatalogPriceIntervalUpdate {
	if v != nil {
		_u.SetTierLabel(*v)
	}
	return _u
}

// SetInputPrice sets the "input_price" field.
func (_u *ModelCatalogPriceIntervalUpdate) SetInputPrice(v float64) *ModelCatalogPriceIntervalUpdate {
	_u.mutation.ResetInputPrice()
	_u.mutation.SetInputPrice(v)
	return _u
}

// SetNillableInputPrice sets the "input_price" field if the given value is not nil.
func (_u *ModelCatalogPriceIntervalUpdate) SetNillableInputPrice(v *float64) *ModelCatalogPriceIntervalUpdate {
	if v != nil {
		_u.SetInputPrice(*v)
	}
	return _u
}

// AddInputPrice adds value to the "input_price" field.
func (_u *ModelCatalogPriceIntervalUpdate) AddInputPrice(v float64) *ModelCatalogPriceIntervalUpdate {
	_u.mutation.AddInputPrice(v)
	return _u
}

// ClearInputPrice clears the value of the "input_price" field.
func (_u *ModelCatalogPriceIntervalUpdate) ClearInputPrice() *ModelCatalogPriceIntervalUpdate {
	_u.mutation.ClearInputPrice()
	return _u
}

// SetOutputPrice sets the "output_price" field.
func (_u *ModelCatalogPriceIntervalUpdate) SetOutputPrice(v float64) *ModelCatalogPriceIntervalUpdate {
	_u.mutation.ResetOutputPrice()
	_u.mutation.SetOutputPrice(v)
	return _u
}

// SetNillableOutputPrice sets the "output_price" field if the given value is not nil.
func (_u *ModelCatalogPriceIntervalUpdate) SetNillableOutputPrice(v *float64) *ModelCatalogPriceIntervalUpdate {
	if v != nil {
		_u.SetOutputPrice(*v)
	}
	return _u
}

// AddOutputPrice adds value to the "output_price" field.
func (_u *ModelCatalogPriceIntervalUpdate) AddOutputPrice(v float64) *ModelCatalogPriceIntervalUpdate {
	_u.mutation.AddOutputPrice(v)
	return _u
}

// ClearOutputPrice clears the value of the "output_price" field.
func (_u *ModelCatalogPriceIntervalUpdate) ClearOutputPrice() *ModelCatalogPriceIntervalUpdate {
	_u.mutation.ClearOutputPrice()
	return _u
}

// SetCacheWritePrice sets the "cache_write_price" field.
func (_u *ModelCatalogPriceIntervalUpdate) SetCacheWritePrice(v float64) *ModelCatalogPriceIntervalUpdate {
	_u.mutation.ResetCacheWritePrice()
	_u.mutation.SetCacheWritePrice(v)
	return _u
}

// SetNillableCacheWritePrice sets the "cache_write_price" field if the given value is not nil.
func (_u *ModelCatalogPriceIntervalUpdate) SetNillableCacheWritePrice(v *float64) *ModelCatalogPriceIntervalUpdate {
	if v != nil {
		_u.SetCacheWritePrice(*v)
	}
	return _u
}

// AddCacheWritePrice adds value to the "cache_write_price" field.
func (_u *ModelCatalogPriceIntervalUpdate) AddCacheWritePrice(v float64) *ModelCatalogPriceIntervalUpdate {
	_u.mutation.AddCacheWritePrice(v)
	return _u
}

// ClearCacheWritePrice clears the value of the "cache_write_price" field.
func (_u *ModelCatalogPriceIntervalUpdate) ClearCacheWritePrice() *ModelCatalogPriceIntervalUpdate {
	_u.mutation.ClearCacheWritePrice()
	return _u
}

// SetCacheWrite1hPrice sets the "cache_write_1h_price" field.
func (_u *ModelCatalogPriceIntervalUpdate) SetCacheWrite1hPrice(v float64) *ModelCatalogPriceIntervalUpdate {
	_u.mutation.ResetCacheWrite1hPrice()
	_u.mutation.SetCacheWrite1hPrice(v)
	return _u
}

// SetNillableCacheWrite1hPrice sets the "cache_write_1h_price" field if the given value is not nil.
func (_u *ModelCatalogPriceIntervalUpdate) SetNillableCacheWrite1hPrice(v *float64) *ModelCatalogPriceIntervalUpdate {
	if v != nil {
		_u.SetCacheWrite1hPrice(*v)
	}
	return _u
}

// AddCacheWrite1hPrice adds value to the "cache_write_1h_price" field.
func (_u *ModelCatalogPriceIntervalUpdate) AddCacheWrite1hPrice(v float64) *ModelCatalogPriceIntervalUpdate {
	_u.mutation.AddCacheWrite1hPrice(v)
	return _u
}

// ClearCacheWrite1hPrice clears the value of the "cache_write_1h_price" field.
func (_u *ModelCatalogPriceIntervalUpdate) ClearCacheWrite1hPrice() *ModelCatalogPriceIntervalUpdate {
	_u.mutation.ClearCacheWrite1hPrice()
	return _u
}

// SetCacheReadPrice sets the "cache_read_price" field.
func (_u *ModelCatalogPriceIntervalUpdate) SetCacheReadPrice(v float64) *ModelCatalogPriceIntervalUpdate {
	_u.mutation.ResetCacheReadPrice()
	_u.mutation.SetCacheReadPrice(v)
	return _u
}

// SetNillableCacheReadPrice sets the "cache_read_price" field if the given value is not nil.
func (_u *ModelCatalogPriceIntervalUpdate) SetNillableCacheReadPrice(v *float64) *ModelCatalogPriceIntervalUpdate {
	if v != nil {
		_u.SetCacheReadPrice(*v)
	}
	return _u
}

// AddCacheReadPrice adds value to the "cache_read_price" field.
func (_u *ModelCatalogPriceIntervalUpdate) AddCacheReadPrice(v float64) *ModelCatalogPriceIntervalUpdate {
	_u.mutation.AddCacheReadPrice(v)
	return _u
}

// ClearCacheReadPrice clears the value of the "cache_read_price" field.
func (_u *ModelCatalogPriceIntervalUpdate) ClearCacheReadPrice() *ModelCatalogPriceIntervalUpdate {
	_u.mutation.ClearCacheReadPrice()
	return _u
}

// SetPerRequestPrice sets the "per_request_price" field.
func (_u *ModelCatalogPriceIntervalUpdate) SetPerRequestPrice(v float64) *ModelCatalogPriceIntervalUpdate {
	_u.mutation.ResetPerRequestPrice()
	_u.mutation.SetPerRequestPrice(v)
	return _u
}

// SetNillablePerRequestPrice sets the "per_request_price" field if the given value is not nil.
func (_u *ModelCatalogPriceIntervalUpdate) SetNillablePerRequestPrice(v *float64) *ModelCatalogPriceIntervalUpdate {
	if v != nil {
		_u.SetPerRequestPrice(*v)
	}
	return _u
}

// AddPerRequestPrice adds value to the "per_request_price" field.
func (_u *ModelCatalogPriceIntervalUpdate) AddPerRequestPrice(v float64) *ModelCatalogPriceIntervalUpdate {
	_u.mutation.AddPerRequestPrice(v)
	return _u
}

// ClearPerRequestPrice clears the value of the "per_request_price" field.
func (_u *ModelCatalogPriceIntervalUpdate) ClearPerRequestPrice() *ModelCatalogPriceIntervalUpdate {
	_u.mutation.ClearPerRequestPrice()
	return _u
}

// SetInputMultiplier sets the "input_multiplier" field.
func (_u *ModelCatalogPriceIntervalUpdate) SetInputMultiplier(v float64) *ModelCatalogPriceIntervalUpdate {
	_u.mutation.ResetInputMultiplier()
	_u.mutation.SetInputMultiplier(v)
	return _u
}

// SetNillableInputMultiplier sets the "input_multiplier" field if the given value is not nil.
func (_u *ModelCatalogPriceIntervalUpdate) SetNillableInputMultiplier(v *float64) *ModelCatalogPriceIntervalUpdate {
	if v != nil {
		_u.SetInputMultiplier(*v)
	}
	return _u
}

// AddInputMultiplier adds value to the "input_multiplier" field.
func (_u *ModelCatalogPriceIntervalUpdate) AddInputMultiplier(v float64) *ModelCatalogPriceIntervalUpdate {
	_u.mutation.AddInputMultiplier(v)
	return _u
}

// ClearInputMultiplier clears the value of the "input_multiplier" field.
func (_u *ModelCatalogPriceIntervalUpdate) ClearInputMultiplier() *ModelCatalogPriceIntervalUpdate {
	_u.mutation.ClearInputMultiplier()
	return _u
}

// SetOutputMultiplier sets the "output_multiplier" field.
func (_u *ModelCatalogPriceIntervalUpdate) SetOutputMultiplier(v float64) *ModelCatalogPriceIntervalUpdate {
	_u.mutation.ResetOutputMultiplier()
	_u.mutation.SetOutputMultiplier(v)
	return _u
}

// SetNillableOutputMultiplier sets the "output_multiplier" field if the given value is not nil.
func (_u *ModelCatalogPriceIntervalUpdate) SetNillableOutputMultiplier(v *float64) *ModelCatalogPriceIntervalUpdate {
	if v != nil {
		_u.SetOutputMultiplier(*v)
	}
	return _u
}

// AddOutputMultiplier adds value to the "output_multiplier" field.
func (_u *ModelCatalogPriceIntervalUpdate) AddOutputMultiplier(v float64) *ModelCatalogPriceIntervalUpdate {
	_u.mutation.AddOutputMultiplier(v)
	return _u
}

// ClearOutputMultiplier clears the value of the "output_multiplier" field.
func (_u *ModelCatalogPriceIntervalUpdate) ClearOutputMultiplier() *ModelCatalogPriceIntervalUpdate {
	_u.mutation.ClearOutputMultiplier()
	return _u
}

// SetCacheWriteMultiplier sets the "cache_write_multiplier" field.
func (_u *ModelCatalogPriceIntervalUpdate) SetCacheWriteMultiplier(v float64) *ModelCatalogPriceIntervalUpdate {
	_u.mutation.ResetCacheWriteMultiplier()
	_u.mutation.SetCacheWriteMultiplier(v)
	return _u
}

// SetNillableCacheWriteMultiplier sets the "cache_write_multiplier" field if the given value is not nil.
func (_u *ModelCatalogPriceIntervalUpdate) SetNillableCacheWriteMultiplier(v *float64) *ModelCatalogPriceIntervalUpdate {
	if v != nil {
		_u.SetCacheWriteMultiplier(*v)
	}
	return _u
}

// AddCacheWriteMultiplier adds value to the "cache_write_multiplier" field.
func (_u *ModelCatalogPriceIntervalUpdate) AddCacheWriteMultiplier(v float64) *ModelCatalogPriceIntervalUpdate {
	_u.mutation.AddCacheWriteMultiplier(v)
	return _u
}

// ClearCacheWriteMultiplier clears the value of the "cache_write_multiplier" field.
func (_u *ModelCatalogPriceIntervalUpdate) ClearCacheWriteMultiplier() *ModelCatalogPriceIntervalUpdate {
	_u.mutation.ClearCacheWriteMultiplier()
	return _u
}

// SetCacheReadMultiplier sets the "cache_read_multiplier" field.
func (_u *ModelCatalogPriceIntervalUpdate) SetCacheReadMultiplier(v float64) *ModelCatalogPriceIntervalUpdate {
	_u.mutation.ResetCacheReadMultiplier()
	_u.mutation.SetCacheReadMultiplier(v)
	return _u
}

// SetNillableCacheReadMultiplier sets the "cache_read_multiplier" field if the given value is not nil.
func (_u *ModelCatalogPriceIntervalUpdate) SetNillableCacheReadMultiplier(v *float64) *ModelCatalogPriceIntervalUpdate {
	if v != nil {
		_u.SetCacheReadMultiplier(*v)
	}
	return _u
}

// AddCacheReadMultiplier adds value to the "cache_read_multiplier" field.
func (_u *ModelCatalogPriceIntervalUpdate) AddCacheReadMultiplier(v float64) *ModelCatalogPriceIntervalUpdate {
	_u.mutation.AddCacheReadMultiplier(v)
	return _u
}

// ClearCacheReadMultiplier clears the value of the "cache_read_multiplier" field.
func (_u *ModelCatalogPriceIntervalUpdate) ClearCacheReadMultiplier() *ModelCatalogPriceIntervalUpdate {
	_u.mutation.ClearCacheReadMultiplier()
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *ModelCatalogPriceIntervalUpdate) SetSortOrder(v int) *ModelCatalogPriceIntervalUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *ModelCatalogPriceIntervalUpdate) SetNillableSortOrder(v *int) *ModelCatalogPriceIntervalUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *ModelCatalogPriceIntervalUpdate) AddSortOrder(v int) *ModelCatalogPriceIntervalUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// Mutation returns the ModelCatalogPriceIntervalMutation object of the builder.
func (_u *ModelCatalogPriceIntervalUpdate) Mutation() *ModelCatalogPriceIntervalMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ModelCatalogPriceIntervalUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ModelCatalogPriceIntervalUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ModelCatalogPriceIntervalUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ModelCatalogPriceIntervalUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ModelCatalogPriceIntervalUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := modelcatalogpriceinterval.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ModelCatalogPriceIntervalUpdate) check() error {
	if v, ok := _u.mutation.TierLabel(); ok {
		if err := modelcatalogpriceinterval.TierLabelValidator(v); err != nil {
			return &ValidationError{Name: "tier_label", err: fmt.Errorf(`ent: validator failed for field "ModelCatalogPriceInterval.tier_label": %w`, err)}
		}
	}
	return nil
}

func (_u *ModelCatalogPriceIntervalUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(modelcatalogpriceinterval.Table, modelcatalogpriceinterval.Columns, sqlgraph.NewFieldSpec(modelcatalogpriceinterval.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(modelcatalogpriceinterval.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EntryID(); ok {
		_spec.SetField(modelcatalogpriceinterval.FieldEntryID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedEntryID(); ok {
		_spec.AddField(modelcatalogpriceinterval.FieldEntryID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.MinTokens(); ok {
		_spec.SetField(modelcatalogpriceinterval.FieldMinTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMinTokens(); ok {
		_spec.AddField(modelcatalogpriceinterval.FieldMinTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MaxTokens(); ok {
		_spec.SetField(modelcatalogpriceinterval.FieldMaxTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxTokens(); ok {
		_spec.AddField(modelcatalogpriceinterval.FieldMaxTokens, field.TypeInt, value)
	}
	if _u.mutation.MaxTokensCleared() {
		_spec.ClearField(modelcatalogpriceinterval.FieldMaxTokens, field.TypeInt)
	}
	if value, ok := _u.mutation.TierLabel(); ok {
		_spec.SetField(modelcatalogpriceinterval.FieldTierLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.InputPrice(); ok {
		_spec.SetField(modelcatalogpriceinterval.FieldInputPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedInputPrice(); ok {
		_spec.AddField(modelcatalogpriceinterval.FieldInputPrice, field.TypeFloat64, value)
	}
	if _u.mutation.InputPriceCleared() {
		_spec.ClearField(modelcatalogpriceinterval.FieldInputPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.OutputPrice(); ok {
		_spec.SetField(modelcatalogpriceinterval.FieldOutputPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOutputPrice(); ok {
		_spec.AddField(modelcatalogpriceinterval.FieldOutputPrice, field.TypeFloat64, value)
	}
	if _u.mutation.OutputPriceCleared() {
		_spec.ClearField(modelcatalogpriceinterval.FieldOutputPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.CacheWritePrice(); ok {
		_spec.SetField(modelcatalogpriceinterval.FieldCacheWritePrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCacheWritePrice(); ok {
		_spec.AddField(modelcatalogpriceinterval.FieldCacheWritePrice, field.TypeFloat64, value)
	}
	if _u.mutation.CacheWritePriceCleared() {
		_spec.ClearField(modelcatalogpriceinterval.FieldCacheWritePrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.CacheWrite1hPrice(); ok {
		_spec.SetField(modelcatalogpriceinterval.FieldCacheWrite1hPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCacheWrite1hPrice(); ok {
		_spec.AddField(modelcatalogpriceinterval.FieldCacheWrite1hPrice, field.TypeFloat64, value)
	}
	if _u.mutation.CacheWrite1hPriceCleared() {
		_spec.ClearField(modelcatalogpriceinterval.FieldCacheWrite1hPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.CacheReadPrice(); ok {
		_spec.SetField(modelcatalogpriceinterval.FieldCacheReadPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCacheReadPrice(); ok {
		_spec.AddField(modelcatalogpriceinterval.FieldCacheReadPrice, field.TypeFloat64, value)
	}
	if _u.mutation.CacheReadPriceCleared() {
		_spec.ClearField(modelcatalogpriceinterval.FieldCacheReadPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.PerRequestPrice(); ok {
		_spec.SetField(modelcatalogpriceinterval.FieldPerRequestPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPerRequestPrice(); ok {
		_spec.AddField(modelcatalogpriceinterval.FieldPerRequestPrice, field.TypeFloat64, value)
	}
	if _u.mutation.PerRequestPriceCleared() {
		_spec.ClearField(modelcatalogpriceinterval.FieldPerRequestPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.InputMultiplier(); ok {
		_spec.SetField(modelcatalogpriceinterval.FieldInputMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedInputMultiplier(); ok {
		_spec.AddField(modelcatalogpriceinterval.FieldInputMultiplier, field.TypeFloat64, value)
	}
	if _u.mutation.InputMultiplierCleared() {
		_spec.ClearField(modelcatalogpriceinterval.FieldInputMultiplier, field.TypeFloat64)
	}
	if value, ok := _u.mutation.OutputMultiplier(); ok {
		_spec.SetField(modelcatalogpriceinterval.FieldOutputMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOutputMultiplier(); ok {
		_spec.AddField(modelcatalogpriceinterval.FieldOutputMultiplier, field.TypeFloat64, value)
	}
	if _u.mutation.OutputMultiplierCleared() {
		_spec.ClearField(modelcatalogpriceinterval.FieldOutputMultiplier, field.TypeFloat64)
	}
	if value, ok := _u.mutation.CacheWriteMultiplier(); ok {
		_spec.SetField(modelcatalogpriceinterval.FieldCacheWriteMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCacheWriteMultiplier(); ok {
		_spec.AddField(modelcatalogpriceinterval.FieldCacheWriteMultiplier, field.TypeFloat64, value)
	}
	if _u.mutation.CacheWriteMultiplierCleared() {
		_spec.ClearField(modelcatalogpriceinterval.FieldCacheWriteMultiplier, field.TypeFloat64)
	}
	if value, ok := _u.mutation.CacheReadMultiplier(); ok {
		_spec.SetField(modelcatalogpriceinterval.FieldCacheReadMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCacheReadMultiplier(); ok {
		_spec.AddField(modelcatalogpriceinterval.FieldCacheReadMultiplier, field.TypeFloat64, value)
	}
	if _u.mutation.CacheReadMultiplierCleared() {
		_spec.ClearField(modelcatalogpriceinterval.FieldCacheReadMultiplier, field.TypeFloat64)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(modelcatalogpriceinterval.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(modelcatalogpriceinterval.FieldSortOrder, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{modelcatalogpriceinterval.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ModelCatalogPriceIntervalUpdateOne is the builder for updating a single ModelCatalogPriceInterval entity.
type ModelCatalogPriceIntervalUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ModelCatalogPriceIntervalMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ModelCatalogPriceIntervalUpdateOne) SetUpdatedAt(v time.Time) *ModelCatalogPriceIntervalUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetEntryID sets the "entry_id" field.
func (_u *ModelCatalogPriceIntervalUpdateOne) SetEntryID(v int64) *ModelCatalogPriceIntervalUpdateOne {
	_u.mutation.ResetEntryID()
	_u.mutation.SetEntryID(v)
	return _u
}

// SetNillableEntryID sets the "entry_id" field if the given value is not nil.
func (_u *ModelCatalogPriceIntervalUpdateOne) SetNillableEntryID(v *int64) *ModelCatalogPriceIntervalUpdateOne {
	if v != nil {
		_u.SetEntryID(*v)
	}
	return _u
}

// AddEntryID adds value to the "entry_id" field.
func (_u *ModelCatalogPriceIntervalUpdateOne) AddEntryID(v int64) *ModelCatalogPriceIntervalUpdateOne {
	_u.mutation.AddEntryID(v)
	return _u
}

// SetMinTokens sets the "min_tokens" field.
func (_u *ModelCatalogPriceIntervalUpdateOne) SetMinTokens(v int) *ModelCatalogPriceIntervalUpdateOne {
	_u.mutation.ResetMinTokens()
	_u.mutation.SetMinTokens(v)
	return _u
}

// SetNillableMinTokens sets the "min_tokens" field if the given value is not nil.
func (_u *ModelCatalogPriceIntervalUpdateOne) SetNillableMinTokens(v *int) *ModelCatalogPriceIntervalUpdateOne {
	if v != nil {
		_u.SetMinTokens(*v)
	}
	return _u
}

// AddMinTokens adds value to the "min_tokens" field.
func (_u *ModelCatalogPriceIntervalUpdateOne) AddMinTokens(v int) *ModelCatalogPriceIntervalUpdateOne {
	_u.mutation.AddMinTokens(v)
	return _u
}

// SetMaxTokens sets the "max_tokens" field.
func (_u *ModelCatalogPriceIntervalUpdateOne) SetMaxTokens(v int) *ModelCatalogPriceIntervalUpdateOne {
	_u.mutation.ResetMaxTokens()
	_u.mutation.SetMaxTokens(v)
	return _u
}

// SetNillableMaxTokens sets the "max_tokens" field if the given value is not nil.
func (_u *ModelCatalogPriceIntervalUpdateOne) SetNillableMaxTokens(v *int) *ModelCatalogPriceIntervalUpdateOne {
	if v != nil {
		_u.SetMaxTokens(*v)
	}
	return _u
}

// AddMaxTokens adds value to the "max_tokens" field.
func (_u *ModelCatalogPriceIntervalUpdateOne) AddMaxTokens(v int) *ModelCatalogPriceIntervalUpdateOne {
	_u.mutation.AddMaxTokens(v)
	return _u
}

// ClearMaxTokens clears the value of the "max_tokens" field.
func (_u *ModelCatalogPriceIntervalUpdateOne) ClearMaxTokens() *ModelCatalogPriceIntervalUpdateOne {
	_u.mutation.ClearMaxTokens()
	return _u
}

// SetTierLabel sets the "tier_label" field.
func (_u *ModelCatalogPriceIntervalUpdateOne) SetTierLabel(v string) *ModelCatalogPriceIntervalUpdateOne {
	_u.mutation.SetTierLabel(v)
	return _u
}

// SetNillableTierLabel sets the "tier_label" field if the given value is not nil.
func (_u *ModelCatalogPriceIntervalUpdateOne) SetNillableTierLabel(v *string) *ModelCatalogPriceIntervalUpdateOne {
	if v != nil {
		_u.SetTierLabel(*v)
	}
	return _u
}

// SetInputPrice sets the "input_price" field.
func (_u *ModelCatalogPriceIntervalUpdateOne) SetInputPrice(v float64) *ModelCatalogPriceIntervalUpdateOne {
	_u.mutation.ResetInputPrice()
	_u.mutation.SetInputPrice(v)
	return _u
}

// SetNillableInputPrice sets the "input_price" field if the given value is not nil.
func (_u *ModelCatalogPriceIntervalUpdateOne) SetNillableInputPrice(v *float64) *ModelCatalogPriceIntervalUpdateOne {
	if v != nil {
		_u.SetInputPrice(*v)
	}
	return _u
}

// AddInputPrice adds value to the "input_price" field.
func (_u *ModelCatalogPriceIntervalUpdateOne) AddInputPrice(v float64) *ModelCatalogPriceIntervalUpdateOne {
	_u.mutation.AddInputPrice(v)
	return _u
}

// ClearInputPrice clears the value of the "input_price" field.
func (_u *ModelCatalogPriceIntervalUpdateOne) ClearInputPrice() *ModelCatalogPriceIntervalUpdateOne {
	_u.mutation.ClearInputPrice()
	return _u
}

// SetOutputPrice sets the "output_price" field.
func (_u *ModelCatalogPriceIntervalUpdateOne) SetOutputPrice(v float64) *ModelCatalogPriceIntervalUpdateOne {
	_u.mutation.ResetOutputPrice()
	_u.mutation.SetOutputPrice(v)
	return _u
}

// SetNillableOutputPrice sets the "output_price" field if the given value is not nil.
func (_u *ModelCatalogPriceIntervalUpdateOne) SetNillableOutputPrice(v *float64) *ModelCatalogPriceIntervalUpdateOne {
	if v != nil {
		_u.SetOutputPrice(*v)
	}
	return _u
}

// AddOutputPrice adds value to the "output_price" field.
func (_u *ModelCatalogPriceIntervalUpdateOne) AddOutputPrice(v float64) *ModelCatalogPriceIntervalUpdateOne {
	_u.mutation.AddOutputPrice(v)
	return _u
}

// ClearOutputPrice clears the value of the "output_price" field.
func (_u *ModelCatalogPriceIntervalUpdateOne) ClearOutputPrice() *ModelCatalogPriceIntervalUpdateOne {
	_u.mutation.ClearOutputPrice()
	return _u
}

// SetCacheWritePrice sets the "cache_write_price" field.
func (_u *ModelCatalogPriceIntervalUpdateOne) SetCacheWritePrice(v float64) *ModelCatalogPriceIntervalUpdateOne {
	_u.mutation.ResetCacheWritePrice()
	_u.mutation.SetCacheWritePrice(v)
	return _u
}

// SetNillableCacheWritePrice sets the "cache_write_price" field if the given value is not nil.
func (_u *ModelCatalogPriceIntervalUpdateOne) SetNillableCacheWritePrice(v *float64) *ModelCatalogPriceIntervalUpdateOne {
	if v != nil {
		_u.SetCacheWritePrice(*v)
	}
	return _u
}

// AddCacheWritePrice adds value to the "cache_write_price" field.
func (_u *ModelCatalogPriceIntervalUpdateOne) AddCacheWritePrice(v float64) *ModelCatalogPriceIntervalUpdateOne {
	_u.mutation.AddCacheWritePrice(v)
	return _u
}

// ClearCacheWritePrice clears the value of the "cache_write_price" field.
func (_u *ModelCatalogPriceIntervalUpdateOne) ClearCacheWritePrice() *ModelCatalogPriceIntervalUpdateOne {
	_u.mutation.ClearCacheWritePrice()
	return _u
}

// SetCacheWrite1hPrice sets the "cache_write_1h_price" field.
func (_u *ModelCatalogPriceIntervalUpdateOne) SetCacheWrite1hPrice(v float64) *ModelCatalogPriceIntervalUpdateOne {
	_u.mutation.ResetCacheWrite1hPrice()
	_u.mutation.SetCacheWrite1hPrice(v)
	return _u
}

// SetNillableCacheWrite1hPrice sets the "cache_write_1h_price" field if the given value is not nil.
func (_u *ModelCatalogPriceIntervalUpdateOne) SetNillableCacheWrite1hPrice(v *float64) *ModelCatalogPriceIntervalUpdateOne {
	if v != nil {
		_u.SetCacheWrite1hPrice(*v)
	}
	return _u
}

// AddCacheWrite1hPrice adds value to the "cache_write_1h_price" field.
func (_u *ModelCatalogPriceIntervalUpdateOne) AddCacheWrite1hPrice(v float64) *ModelCatalogPriceIntervalUpdateOne {
	_u.mutation.AddCacheWrite1hPrice(v)
	return _u
}

// ClearCacheWrite1hPrice clears the value of the "cache_write_1h_price" field.
func (_u *ModelCatalogPriceIntervalUpdateOne) ClearCacheWrite1hPrice() *ModelCatalogPriceIntervalUpdateOne {
	_u.mutation.ClearCacheWrite1hPrice()
	return _u
}

// SetCacheReadPrice sets the "cache_read_price" field.
func (_u *ModelCatalogPriceIntervalUpdateOne) SetCacheReadPrice(v float64) *ModelCatalogPriceIntervalUpdateOne {
	_u.mutation.ResetCacheReadPrice()
	_u.mutation.SetCacheReadPrice(v)
	return _u
}

// SetNillableCacheReadPrice sets the "cache_read_price" field if the given value is not nil.
func (_u *ModelCatalogPriceIntervalUpdateOne) SetNillableCacheReadPrice(v *float64) *ModelCatalogPriceIntervalUpdateOne {
	if v != nil {
		_u.SetCacheReadPrice(*v)
	}
	return _u
}

// AddCacheReadPrice adds value to the "cache_read_price" field.
func (_u *ModelCatalogPriceIntervalUpdateOne) AddCacheReadPrice(v float64) *ModelCatalogPriceIntervalUpdateOne {
	_u.mutation.AddCacheReadPrice(v)
	return _u
}

// ClearCacheReadPrice clears the value of the "cache_read_price" field.
func (_u *ModelCatalogPriceIntervalUpdateOne) ClearCacheReadPrice() *ModelCatalogPriceIntervalUpdateOne {
	_u.mutation.ClearCacheReadPrice()
	return _u
}

// SetPerRequestPrice sets the "per_request_price" field.
func (_u *ModelCatalogPriceIntervalUpdateOne) SetPerRequestPrice(v float64) *ModelCatalogPriceIntervalUpdateOne {
	_u.mutation.ResetPerRequestPrice()
	_u.mutation.SetPerRequestPrice(v)
	return _u
}

// SetNillablePerRequestPrice sets the "per_request_price" field if the given value is not nil.
func (_u *ModelCatalogPriceIntervalUpdateOne) SetNillablePerRequestPrice(v *float64) *ModelCatalogPriceIntervalUpdateOne {
	if v != nil {
		_u.SetPerRequestPrice(*v)
	}
	return _u
}

// AddPerRequestPrice adds value to the "per_request_price" field.
func (_u *ModelCatalogPriceIntervalUpdateOne) AddPerRequestPrice(v float64) *ModelCatalogPriceIntervalUpdateOne {
	_u.mutation.AddPerRequestPrice(v)
	return _u
}

// ClearPerRequestPrice clears the value of the "per_request_price" field.
func (_u *ModelCatalogPriceIntervalUpdateOne) ClearPerRequestPrice() *ModelCatalogPriceIntervalUpdateOne {
	_u.mutation.ClearPerRequestPrice()
	return _u
}

// SetInputMultiplier sets the "input_multiplier" field.
func (_u *ModelCatalogPriceIntervalUpdateOne) SetInputMultiplier(v float64) *ModelCatalogPriceIntervalUpdateOne {
	_u.mutation.ResetInputMultiplier()
	_u.mutation.SetInputMultiplier(v)
	return _u
}

// SetNillableInputMultiplier sets the "input_multiplier" field if the given value is not nil.
func (_u *ModelCatalogPriceIntervalUpdateOne) SetNillableInputMultiplier(v *float64) *ModelCatalogPriceIntervalUpdateOne {
	if v != nil {
		_u.SetInputMultiplier(*v)
	}
	return _u
}

// AddInputMultiplier adds value to the "input_multiplier" field.
func (_u *ModelCatalogPriceIntervalUpdateOne) AddInputMultiplier(v float64) *ModelCatalogPriceIntervalUpdateOne {
	_u.mutation.AddInputMultiplier(v)
	return _u
}

// ClearInputMultiplier clears the value of the "input_multiplier" field.
func (_u *ModelCatalogPriceIntervalUpdateOne) ClearInputMultiplier() *ModelCatalogPriceIntervalUpdateOne {
	_u.mutation.ClearInputMultiplier()
	return _u
}

// SetOutputMultiplier sets the "output_multiplier" field.
func (_u *ModelCatalogPriceIntervalUpdateOne) SetOutputMultiplier(v float64) *ModelCatalogPriceIntervalUpdateOne {
	_u.mutation.ResetOutputMultiplier()
	_u.mutation.SetOutputMultiplier(v)
	return _u
}

// SetNillableOutputMultiplier sets the "output_multiplier" field if the given value is not nil.
func (_u *ModelCatalogPriceIntervalUpdateOne) SetNillableOutputMultiplier(v *float64) *ModelCatalogPriceIntervalUpdateOne {
	if v != nil {
		_u.SetOutputMultiplier(*v)
	}
	return _u
}

// AddOutputMultiplier adds value to the "output_multiplier" field.
func (_u *ModelCatalogPriceIntervalUpdateOne) AddOutputMultiplier(v float64) *ModelCatalogPriceIntervalUpdateOne {
	_u.mutation.AddOutputMultiplier(v)
	return _u
}

// ClearOutputMultiplier clears the value of the "output_multiplier" field.
func (_u *ModelCatalogPriceIntervalUpdateOne) ClearOutputMultiplier() *ModelCatalogPriceIntervalUpdateOne {
	_u.mutation.ClearOutputMultiplier()
	return _u
}

// SetCacheWriteMultiplier sets the "cache_write_multiplier" field.
func (_u *ModelCatalogPriceIntervalUpdateOne) SetCacheWriteMultiplier(v float64) *ModelCatalogPriceIntervalUpdateOne {
	_u.mutation.ResetCacheWriteMultiplier()
	_u.mutation.SetCacheWriteMultiplier(v)
	return _u
}

// SetNillableCacheWriteMultiplier sets the "cache_write_multiplier" field if the given value is not nil.
func (_u *ModelCatalogPriceIntervalUpdateOne) SetNillableCacheWriteMultiplier(v *float64) *ModelCatalogPriceIntervalUpdateOne {
	if v != nil {
		_u.SetCacheWriteMultiplier(*v)
	}
	return _u
}

// AddCacheWriteMultiplier adds value to the "cache_write_multiplier" field.
func (_u *ModelCatalogPriceIntervalUpdateOne) AddCacheWriteMultiplier(v float64) *ModelCatalogPriceIntervalUpdateOne {
	_u.mutation.AddCacheWriteMultiplier(v)
	return _u
}

// ClearCacheWriteMultiplier clears the value of the "cache_write_multiplier" field.
func (_u *ModelCatalogPriceIntervalUpdateOne) ClearCacheWriteMultiplier() *ModelCatalogPriceIntervalUpdateOne {
	_u.mutation.ClearCacheWriteMultiplier()
	return _u
}

// SetCacheReadMultiplier sets the "cache_read_multiplier" field.
func (_u *ModelCatalogPriceIntervalUpdateOne) SetCacheReadMultiplier(v float64) *ModelCatalogPriceIntervalUpdateOne {
	_u.mutation.ResetCacheReadMultiplier()
	_u.mutation.SetCacheReadMultiplier(v)
	return _u
}

// SetNillableCacheReadMultiplier sets the "cache_read_multiplier" field if the given value is not nil.
func (_u *ModelCatalogPriceIntervalUpdateOne) SetNillableCacheReadMultiplier(v *float64) *ModelCatalogPriceIntervalUpdateOne {
	if v != nil {
		_u.SetCacheReadMultiplier(*v)
	}
	return _u
}

// AddCacheReadMultiplier adds value to the "cache_read_multiplier" field.
func (_u *ModelCatalogPriceIntervalUpdateOne) AddCacheReadMultiplier(v float64) *ModelCatalogPriceIntervalUpdateOne {
	_u.mutation.AddCacheReadMultiplier(v)
	return _u
}

// ClearCacheReadMultiplier clears the value of the "cache_read_multiplier" field.
func (_u *ModelCatalogPriceIntervalUpdateOne) ClearCacheReadMultiplier() *ModelCatalogPriceIntervalUpdateOne {
	_u.mutation.ClearCacheReadMultiplier()
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *ModelCatalogPriceIntervalUpdateOne) SetSortOrder(v int) *ModelCatalogPriceIntervalUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *ModelCatalogPriceIntervalUpdateOne) SetNillableSortOrder(v *int) *ModelCatalogPriceIntervalUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *ModelCatalogPriceIntervalUpdateOne) AddSortOrder(v int) *ModelCatalogPriceIntervalUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// Mutation returns the ModelCatalogPriceIntervalMutation object of the builder.
func (_u *ModelCatalogPriceIntervalUpdateOne) Mutation() *ModelCatalogPriceIntervalMutation {
	return _u.mutation
}

// Where appends a list predicates to the ModelCatalogPriceIntervalUpdate builder.
func (_u *ModelCatalogPriceIntervalUpdateOne) Where(ps ...predicate.ModelCatalogPriceInterval) *ModelCatalogPriceIntervalUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ModelCatalogPriceIntervalUpdateOne) Select(field string, fields ...string) *ModelCatalogPriceIntervalUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ModelCatalogPriceInterval entity.
func (_u *ModelCatalogPriceIntervalUpdateOne) Save(ctx context.Context) (*ModelCatalogPriceInterval, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ModelCatalogPriceIntervalUpdateOne) SaveX(ctx context.Context) *ModelCatalogPriceInterval {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ModelCatalogPriceIntervalUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ModelCatalogPriceIntervalUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ModelCatalogPriceIntervalUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := modelcatalogpriceinterval.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ModelCatalogPriceIntervalUpdateOne) check() error {
	if v, ok := _u.mutation.TierLabel(); ok {
		if err := modelcatalogpriceinterval.TierLabelValidator(v); err != nil {
			return &ValidationError{Name: "tier_label", err: fmt.Errorf(`ent: validator failed for field "ModelCatalogPriceInterval.tier_label": %w`, err)}
		}
	}
	return nil
}

func (_u *ModelCatalogPriceIntervalUpdateOne) sqlSave(ctx context.Context) (_node *ModelCatalogPriceInterval, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(modelcatalogpriceinterval.Table, modelcatalogpriceinterval.Columns, sqlgraph.NewFieldSpec(modelcatalogpriceinterval.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ModelCatalogPriceInterval.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, modelcatalogpriceinterval.FieldID)
		for _, f := range fields {
			if !modelcatalogpriceinterval.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != modelcatalogpriceinterval.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(modelcatalogpriceinterval.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EntryID(); ok {
		_spec.SetField(modelcatalogpriceinterval.FieldEntryID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedEntryID(); ok {
		_spec.AddField(modelcatalogpriceinterval.FieldEntryID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.MinTokens(); ok {
		_spec.SetField(modelcatalogpriceinterval.FieldMinTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMinTokens(); ok {
		_spec.AddField(modelcatalogpriceinterval.FieldMinTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MaxTokens(); ok {
		_spec.SetField(modelcatalogpriceinterval.FieldMaxTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxTokens(); ok {
		_spec.AddField(modelcatalogpriceinterval.FieldMaxTokens, field.TypeInt, value)
	}
	if _u.mutation.MaxTokensCleared() {
		_spec.ClearField(modelcatalogpriceinterval.FieldMaxTokens, field.TypeInt)
	}
	if value, ok := _u.mutation.TierLabel(); ok {
		_spec.SetField(modelcatalogpriceinterval.FieldTierLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.InputPrice(); ok {
		_spec.SetField(modelcatalogpriceinterval.FieldInputPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedInputPrice(); ok {
		_spec.AddField(modelcatalogpriceinterval.FieldInputPrice, field.TypeFloat64, value)
	}
	if _u.mutation.InputPriceCleared() {
		_spec.ClearField(modelcatalogpriceinterval.FieldInputPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.OutputPrice(); ok {
		_spec.SetField(modelcatalogpriceinterval.FieldOutputPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOutputPrice(); ok {
		_spec.AddField(modelcatalogpriceinterval.FieldOutputPrice, field.TypeFloat64, value)
	}
	if _u.mutation.OutputPriceCleared() {
		_spec.ClearField(modelcatalogpriceinterval.FieldOutputPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.CacheWritePrice(); ok {
		_spec.SetField(modelcatalogpriceinterval.FieldCacheWritePrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCacheWritePrice(); ok {
		_spec.AddField(modelcatalogpriceinterval.FieldCacheWritePrice, field.TypeFloat64, value)
	}
	if _u.mutation.CacheWritePriceCleared() {
		_spec.ClearField(modelcatalogpriceinterval.FieldCacheWritePrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.CacheWrite1hPrice(); ok {
		_spec.SetField(modelcatalogpriceinterval.FieldCacheWrite1hPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCacheWrite1hPrice(); ok {
		_spec.AddField(modelcatalogpriceinterval.FieldCacheWrite1hPrice, field.TypeFloat64, value)
	}
	if _u.mutation.CacheWrite1hPriceCleared() {
		_spec.ClearField(modelcatalogpriceinterval.FieldCacheWrite1hPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.CacheReadPrice(); ok {
		_spec.SetField(modelcatalogpriceinterval.FieldCacheReadPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCacheReadPrice(); ok {
		_spec.AddField(modelcatalogpriceinterval.FieldCacheReadPrice, field.TypeFloat64, value)
	}
	if _u.mutation.CacheReadPriceCleared() {
		_spec.ClearField(modelcatalogpriceinterval.FieldCacheReadPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.PerRequestPrice(); ok {
		_spec.SetField(modelcatalogpriceinterval.FieldPerRequestPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPerRequestPrice(); ok {
		_spec.AddField(modelcatalogpriceinterval.FieldPerRequestPrice, field.TypeFloat64, value)
	}
	if _u.mutation.PerRequestPriceCleared() {
		_spec.ClearField(modelcatalogpriceinterval.FieldPerRequestPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.InputMultiplier(); ok {
		_spec.SetField(modelcatalogpriceinterval.FieldInputMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedInputMultiplier(); ok {
		_spec.AddField(modelcatalogpriceinterval.FieldInputMultiplier, field.TypeFloat64, value)
	}
	if _u.mutation.InputMultiplierCleared() {
		_spec.ClearField(modelcatalogpriceinterval.FieldInputMultiplier, field.TypeFloat64)
	}
	if value, ok := _u.mutation.OutputMultiplier(); ok {
		_spec.SetField(modelcatalogpriceinterval.FieldOutputMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOutputMultiplier(); ok {
		_spec.AddField(modelcatalogpriceinterval.FieldOutputMultiplier, field.TypeFloat64, value)
	}
	if _u.mutation.OutputMultiplierCleared() {
		_spec.ClearField(modelcatalogpriceinterval.FieldOutputMultiplier, field.TypeFloat64)
	}
	if value, ok := _u.mutation.CacheWriteMultiplier(); ok {
		_spec.SetField(modelcatalogpriceinterval.FieldCacheWriteMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCacheWriteMultiplier(); ok {
		_spec.AddField(modelcatalogpriceinterval.FieldCacheWriteMultiplier, field.TypeFloat64, value)
	}
	if _u.mutation.CacheWriteMultiplierCleared() {
		_spec.ClearField(modelcatalogpriceinterval.FieldCacheWriteMultiplier, field.TypeFloat64)
	}
	if value, ok := _u.mutation.CacheReadMultiplier(); ok {
		_spec.SetField(modelcatalogpriceinterval.FieldCacheReadMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCacheReadMultiplier(); ok {
		_spec.AddField(modelcatalogpriceinterval.FieldCacheReadMultiplier, field.TypeFloat64, value)
	}
	if _u.mutation.CacheReadMultiplierCleared() {
		_spec.ClearField(modelcatalogpriceinterval.FieldCacheReadMultiplier, field.TypeFloat64)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(modelcatalogpriceinterval.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(modelcatalogpriceinterval.FieldSortOrder, field.TypeInt, value)
	}
	_node = &ModelCatalogPriceInterval{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{modelcatalogpriceinterval.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
