// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/modelcatalogentry"
)

// ModelCatalogEntry is the model entity for the ModelCatalogEntry schema.
type ModelCatalogEntry struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Canonical model identifier; unique case-insensitively.
	ModelID string `json:"model_id,omitempty"`
	// Human-facing name; empty means show model_id.
	DisplayName string `json:"display_name,omitempty"`
	// Vendor that owns the model (anthropic/openai/gemini/xai/...); empty means unknown.
	Vendor string `json:"vendor,omitempty"`
	// Upstream protocols the model speaks: anthropic/chat_completions/responses/gemini.
	Protocols []string `json:"protocols,omitempty"`
	// token / per_request / image / video.
	BillingMode string `json:"billing_mode,omitempty"`
	// listed = 上架（用户可见且可调用）; unlisted = 下架。
	Status string `json:"status,omitempty"`
	// seed = 播种器维护，可被重新播种刷新; admin = 管理员维护，播种器不再覆盖。
	ManagedBy string `json:"managed_by,omitempty"`
	// 条目走哪条网关族（anthropic/openai/gemini/...）；空表示按 vendor 推导。
	RoutePlatform string `json:"route_platform,omitempty"`
	// InputPrice holds the value of the "input_price" field.
	InputPrice *float64 `json:"input_price,omitempty"`
	// OutputPrice holds the value of the "output_price" field.
	OutputPrice *float64 `json:"output_price,omitempty"`
	// CacheWritePrice holds the value of the "cache_write_price" field.
	CacheWritePrice *float64 `json:"cache_write_price,omitempty"`
	// CacheWrite1hPrice holds the value of the "cache_write_1h_price" field.
	CacheWrite1hPrice *float64 `json:"cache_write_1h_price,omitempty"`
	// CacheReadPrice holds the value of the "cache_read_price" field.
	CacheReadPrice *float64 `json:"cache_read_price,omitempty"`
	// ImageInputPrice holds the value of the "image_input_price" field.
	ImageInputPrice *float64 `json:"image_input_price,omitempty"`
	// ImageOutputPrice holds the value of the "image_output_price" field.
	ImageOutputPrice *float64 `json:"image_output_price,omitempty"`
	// ImageCacheReadPrice holds the value of the "image_cache_read_price" field.
	ImageCacheReadPrice *float64 `json:"image_cache_read_price,omitempty"`
	// InputPricePriority holds the value of the "input_price_priority" field.
	InputPricePriority *float64 `json:"input_price_priority,omitempty"`
	// OutputPricePriority holds the value of the "output_price_priority" field.
	OutputPricePriority *float64 `json:"output_price_priority,omitempty"`
	// CacheWritePricePriority holds the value of the "cache_write_price_priority" field.
	CacheWritePricePriority *float64 `json:"cache_write_price_priority,omitempty"`
	// CacheReadPricePriority holds the value of the "cache_read_price_priority" field.
	CacheReadPricePriority *float64 `json:"cache_read_price_priority,omitempty"`
	// PerRequestPrice holds the value of the "per_request_price" field.
	PerRequestPrice *float64 `json:"per_request_price,omitempty"`
	// 超过该 context token 数后整次会话换用长上下文价；nil 表示无长上下文阶梯。
	LongContextInputThreshold *int `json:"long_context_input_threshold,omitempty"`
	// true = 达到阈值即生效（xAI 口径）；false = 严格大于。
	LongContextThresholdInclusive bool `json:"long_context_threshold_inclusive,omitempty"`
	// LongContextInputMultiplier holds the value of the "long_context_input_multiplier" field.
	LongContextInputMultiplier *float64 `json:"long_context_input_multiplier,omitempty"`
	// LongContextOutputMultiplier holds the value of the "long_context_output_multiplier" field.
	LongContextOutputMultiplier *float64 `json:"long_context_output_multiplier,omitempty"`
	// FastMultiplier holds the value of the "fast_multiplier" field.
	FastMultiplier *float64 `json:"fast_multiplier,omitempty"`
	// FlexMultiplier holds the value of the "flex_multiplier" field.
	FlexMultiplier *float64 `json:"flex_multiplier,omitempty"`
	// MaxReasoningEffortMultiplier holds the value of the "max_reasoning_effort_multiplier" field.
	MaxReasoningEffortMultiplier *float64 `json:"max_reasoning_effort_multiplier,omitempty"`
	// Notes holds the value of the "notes" field.
	Notes *string `json:"notes,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ModelCatalogEntryQuery when eager-loading is set.
	Edges        ModelCatalogEntryEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ModelCatalogEntryEdges holds the relations/edges for other nodes in the graph.
type ModelCatalogEntryEdges struct {
	// Accounts holds the value of the accounts edge.
	Accounts []*Account `json:"accounts,omitempty"`
	// Bindings holds the value of the bindings edge.
	Bindings []*ModelCatalogBinding `json:"bindings,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// AccountsOrErr returns the Accounts value or an error if the edge
// was not loaded in eager-loading.
func (e ModelCatalogEntryEdges) AccountsOrErr() ([]*Account, error) {
	if e.loadedTypes[0] {
		return e.Accounts, nil
	}
	return nil, &NotLoadedError{edge: "accounts"}
}

// BindingsOrErr returns the Bindings value or an error if the edge
// was not loaded in eager-loading.
func (e ModelCatalogEntryEdges) BindingsOrErr() ([]*ModelCatalogBinding, error) {
	if e.loadedTypes[1] {
		return e.Bindings, nil
	}
	return nil, &NotLoadedError{edge: "bindings"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ModelCatalogEntry) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case modelcatalogentry.FieldProtocols:
			values[i] = new([]byte)
		case modelcatalogentry.FieldLongContextThresholdInclusive:
			values[i] = new(sql.NullBool)
		case modelcatalogentry.FieldInputPrice, modelcatalogentry.FieldOutputPrice, modelcatalogentry.FieldCacheWritePrice, modelcatalogentry.FieldCacheWrite1hPrice, modelcatalogentry.FieldCacheReadPrice, modelcatalogentry.FieldImageInputPrice, modelcatalogentry.FieldImageOutputPrice, modelcatalogentry.FieldImageCacheReadPrice, modelcatalogentry.FieldInputPricePriority, modelcatalogentry.FieldOutputPricePriority, modelcatalogentry.FieldCacheWritePricePriority, modelcatalogentry.FieldCacheReadPricePriority, modelcatalogentry.FieldPerRequestPrice, modelcatalogentry.FieldLongContextInputMultiplier, modelcatalogentry.FieldLongContextOutputMultiplier, modelcatalogentry.FieldFastMultiplier, modelcatalogentry.FieldFlexMultiplier, modelcatalogentry.FieldMaxReasoningEffortMultiplier:
			values[i] = new(sql.NullFloat64)
		case modelcatalogentry.FieldID, modelcatalogentry.FieldLongContextInputThreshold:
			values[i] = new(sql.NullInt64)
		case modelcatalogentry.FieldModelID, modelcatalogentry.FieldDisplayName, modelcatalogentry.FieldVendor, modelcatalogentry.FieldBillingMode, modelcatalogentry.FieldStatus, modelcatalogentry.FieldManagedBy, modelcatalogentry.FieldRoutePlatform, modelcatalogentry.FieldNotes:
			values[i] = new(sql.NullString)
		case modelcatalogentry.FieldCreatedAt, modelcatalogentry.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ModelCatalogEntry fields.
func (_m *ModelCatalogEntry) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case modelcatalogentry.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case modelcatalogentry.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case modelcatalogentry.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case modelcatalogentry.FieldModelID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model_id", values[i])
			} else if value.Valid {
				_m.ModelID = value.String
			}
		case modelcatalogentry.FieldDisplayName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field display_name", values[i])
			} else if value.Valid {
				_m.DisplayName = value.String
			}
		case modelcatalogentry.FieldVendor:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field vendor", values[i])
			} else if value.Valid {
				_m.Vendor = value.String
			}
		case modelcatalogentry.FieldProtocols:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field protocols", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Protocols); err != nil {
					return fmt.Errorf("unmarshal field protocols: %w", err)
				}
			}
		case modelcatalogentry.FieldBillingMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field billing_mode", values[i])
			} else if value.Valid {
				_m.BillingMode = value.String
			}
		case modelcatalogentry.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case modelcatalogentry.FieldManagedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field managed_by", values[i])
			} else if value.Valid {
				_m.ManagedBy = value.String
			}
		case modelcatalogentry.FieldRoutePlatform:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field route_platform", values[i])
			} else if value.Valid {
				_m.RoutePlatform = value.String
			}
		case modelcatalogentry.FieldInputPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field input_price", values[i])
			} else if value.Valid {
				_m.InputPrice = new(float64)
				*_m.InputPrice = value.Float64
			}
		case modelcatalogentry.FieldOutputPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field output_price", values[i])
			} else if value.Valid {
				_m.OutputPrice = new(float64)
				*_m.OutputPrice = value.Float64
			}
		case modelcatalogentry.FieldCacheWritePrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field cache_write_price", values[i])
			} else if value.Valid {
				_m.CacheWritePrice = new(float64)
				*_m.CacheWritePrice = value.Float64
			}
		case modelcatalogentry.FieldCacheWrite1hPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field cache_write_1h_price", values[i])
			} else if value.Valid {
				_m.CacheWrite1hPrice = new(float64)
				*_m.CacheWrite1hPrice = value.Float64
			}
		case modelcatalogentry.FieldCacheReadPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field cache_read_price", values[i])
			} else if value.Valid {
				_m.CacheReadPrice = new(float64)
				*_m.CacheReadPrice = value.Float64
			}
		case modelcatalogentry.FieldImageInputPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field image_input_price", values[i])
			} else if value.Valid {
				_m.ImageInputPrice = new(float64)
				*_m.ImageInputPrice = value.Float64
			}
		case modelcatalogentry.FieldImageOutputPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field image_output_price", values[i])
			} else if value.Valid {
				_m.ImageOutputPrice = new(float64)
				*_m.ImageOutputPrice = value.Float64
			}
		case modelcatalogentry.FieldImageCacheReadPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field image_cache_read_price", values[i])
			} else if value.Valid {
				_m.ImageCacheReadPrice = new(float64)
				*_m.ImageCacheReadPrice = value.Float64
			}
		case modelcatalogentry.FieldInputPricePriority:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field input_price_priority", values[i])
			} else if value.Valid {
				_m.InputPricePriority = new(float64)
				*_m.InputPricePriority = value.Float64
			}
		case modelcatalogentry.FieldOutputPricePriority:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field output_price_priority", values[i])
			} else if value.Valid {
				_m.OutputPricePriority = new(float64)
				*_m.OutputPricePriority = value.Float64
			}
		case modelcatalogentry.FieldCacheWritePricePriority:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field cache_write_price_priority", values[i])
			} else if value.Valid {
				_m.CacheWritePricePriority = new(float64)
				*_m.CacheWritePricePriority = value.Float64
			}
		case modelcatalogentry.FieldCacheReadPricePriority:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field cache_read_price_priority", values[i])
			} else if value.Valid {
				_m.CacheReadPricePriority = new(float64)
				*_m.CacheReadPricePriority = value.Float64
			}
		case modelcatalogentry.FieldPerRequestPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field per_request_price", values[i])
			} else if value.Valid {
				_m.PerRequestPrice = new(float64)
				*_m.PerRequestPrice = value.Float64
			}
		case modelcatalogentry.FieldLongContextInputThreshold:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field long_context_input_threshold", values[i])
			} else if value.Valid {
				_m.LongContextInputThreshold = new(int)
				*_m.LongContextInputThreshold = int(value.Int64)
			}
		case modelcatalogentry.FieldLongContextThresholdInclusive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field long_context_threshold_inclusive", values[i])
			} else if value.Valid {
				_m.LongContextThresholdInclusive = value.Bool
			}
		case modelcatalogentry.FieldLongContextInputMultiplier:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field long_context_input_multiplier", values[i])
			} else if value.Valid {
				_m.LongContextInputMultiplier = new(float64)
				*_m.LongContextInputMultiplier = value.Float64
			}
		case modelcatalogentry.FieldLongContextOutputMultiplier:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field long_context_output_multiplier", values[i])
			} else if value.Valid {
				_m.LongContextOutputMultiplier = new(float64)
				*_m.LongContextOutputMultiplier = value.Float64
			}
		case modelcatalogentry.FieldFastMultiplier:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field fast_multiplier", values[i])
			} else if value.Valid {
				_m.FastMultiplier = new(float64)
				*_m.FastMultiplier = value.Float64
			}
		case modelcatalogentry.FieldFlexMultiplier:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field flex_multiplier", values[i])
			} else if value.Valid {
				_m.FlexMultiplier = new(float64)
				*_m.FlexMultiplier = value.Float64
			}
		case modelcatalogentry.FieldMaxReasoningEffortMultiplier:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field max_reasoning_effort_multiplier", values[i])
			} else if value.Valid {
				_m.MaxReasoningEffortMultiplier = new(float64)
				*_m.MaxReasoningEffortMultiplier = value.Float64
			}
		case modelcatalogentry.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = new(string)
				*_m.Notes = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ModelCatalogEntry.
// This includes values selected through modifiers, order, etc.
func (_m *ModelCatalogEntry) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAccounts queries the "accounts" edge of the ModelCatalogEntry entity.
func (_m *ModelCatalogEntry) QueryAccounts() *AccountQuery {
	return NewModelCatalogEntryClient(_m.config).QueryAccounts(_m)
}

// QueryBindings queries the "bindings" edge of the ModelCatalogEntry entity.
func (_m *ModelCatalogEntry) QueryBindings() *ModelCatalogBindingQuery {
	return NewModelCatalogEntryClient(_m.config).QueryBindings(_m)
}

// Update returns a builder for updating this ModelCatalogEntry.
// Note that you need to call ModelCatalogEntry.Unwrap() before calling this method if this ModelCatalogEntry
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ModelCatalogEntry) Update() *ModelCatalogEntryUpdateOne {
	return NewModelCatalogEntryClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ModelCatalogEntry entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ModelCatalogEntry) Unwrap() *ModelCatalogEntry {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ModelCatalogEntry is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ModelCatalogEntry) String() string {
	var builder strings.Builder
	builder.WriteString("ModelCatalogEntry(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("model_id=")
	builder.WriteString(_m.ModelID)
	builder.WriteString(", ")
	builder.WriteString("display_name=")
	builder.WriteString(_m.DisplayName)
	builder.WriteString(", ")
	builder.WriteString("vendor=")
	builder.WriteString(_m.Vendor)
	builder.WriteString(", ")
	builder.WriteString("protocols=")
	builder.WriteString(fmt.Sprintf("%v", _m.Protocols))
	builder.WriteString(", ")
	builder.WriteString("billing_mode=")
	builder.WriteString(_m.BillingMode)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("managed_by=")
	builder.WriteString(_m.ManagedBy)
	builder.WriteString(", ")
	builder.WriteString("route_platform=")
	builder.WriteString(_m.RoutePlatform)
	builder.WriteString(", ")
	if v := _m.InputPrice; v != nil {
		builder.WriteString("input_price=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.OutputPrice; v != nil {
		builder.WriteString("output_price=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.CacheWritePrice; v != nil {
		builder.WriteString("cache_write_price=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.CacheWrite1hPrice; v != nil {
		builder.WriteString("cache_write_1h_price=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.CacheReadPrice; v != nil {
		builder.WriteString("cache_read_price=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ImageInputPrice; v != nil {
		builder.WriteString("image_input_price=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ImageOutputPrice; v != nil {
		builder.WriteString("image_output_price=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ImageCacheReadPrice; v != nil {
		builder.WriteString("image_cache_read_price=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.InputPricePriority; v != nil {
		builder.WriteString("input_price_priority=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.OutputPricePriority; v != nil {
		builder.WriteString("output_price_priority=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.CacheWritePricePriority; v != nil {
		builder.WriteString("cache_write_price_priority=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.CacheReadPricePriority; v != nil {
		builder.WriteString("cache_read_price_priority=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.PerRequestPrice; v != nil {
		builder.WriteString("per_request_price=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.LongContextInputThreshold; v != nil {
		builder.WriteString("long_context_input_threshold=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("long_context_threshold_inclusive=")
	builder.WriteString(fmt.Sprintf("%v", _m.LongContextThresholdInclusive))
	builder.WriteString(", ")
	if v := _m.LongContextInputMultiplier; v != nil {
		builder.WriteString("long_context_input_multiplier=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.LongContextOutputMultiplier; v != nil {
		builder.WriteString("long_context_output_multiplier=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.FastMultiplier; v != nil {
		builder.WriteString("fast_multiplier=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.FlexMultiplier; v != nil {
		builder.WriteString("flex_multiplier=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.MaxReasoningEffortMultiplier; v != nil {
		builder.WriteString("max_reasoning_effort_multiplier=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Notes; v != nil {
		builder.WriteString("notes=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// ModelCatalogEntries is a parsable slice of ModelCatalogEntry.
type ModelCatalogEntries []*ModelCatalogEntry
