// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/modelcatalogbinding"
	"github.com/Wei-Shaw/sub2api/ent/modelcatalogentry"
	"github.com/Wei-Shaw/sub2api/internal/domain"
)

// ModelCatalogBindingCreate is the builder for creating a ModelCatalogBinding entity.
type ModelCatalogBindingCreate struct {
	config
	mutation *ModelCatalogBindingMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetEntryID sets the "entry_id" field.
func (_c *ModelCatalogBindingCreate) SetEntryID(v int64) *ModelCatalogBindingCreate {
	_c.mutation.SetEntryID(v)
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *ModelCatalogBindingCreate) SetAccountID(v int64) *ModelCatalogBindingCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetInputPrice sets the "input_price" field.
func (_c *ModelCatalogBindingCreate) SetInputPrice(v float64) *ModelCatalogBindingCreate {
	_c.mutation.SetInputPrice(v)
	return _c
}

// SetOutputPrice sets the "output_price" field.
func (_c *ModelCatalogBindingCreate) SetOutputPrice(v float64) *ModelCatalogBindingCreate {
	_c.mutation.SetOutputPrice(v)
	return _c
}

// SetCacheWritePrice sets the "cache_write_price" field.
func (_c *ModelCatalogBindingCreate) SetCacheWritePrice(v float64) *ModelCatalogBindingCreate {
	_c.mutation.SetCacheWritePrice(v)
	return _c
}

// SetNillableCacheWritePrice sets the "cache_write_price" field if the given value is not nil.
func (_c *ModelCatalogBindingCreate) SetNillableCacheWritePrice(v *float64) *ModelCatalogBindingCreate {
	if v != nil {
		_c.SetCacheWritePrice(*v)
	}
	return _c
}

// SetCacheWrite1hPrice sets the "cache_write_1h_price" field.
func (_c *ModelCatalogBindingCreate) SetCacheWrite1hPrice(v float64) *ModelCatalogBindingCreate {
	_c.mutation.SetCacheWrite1hPrice(v)
	return _c
}

// SetNillableCacheWrite1hPrice sets the "cache_write_1h_price" field if the given value is not nil.
func (_c *ModelCatalogBindingCreate) SetNillableCacheWrite1hPrice(v *float64) *ModelCatalogBindingCreate {
	if v != nil {
		_c.SetCacheWrite1hPrice(*v)
	}
	return _c
}

// SetCacheReadPrice sets the "cache_read_price" field.
func (_c *ModelCatalogBindingCreate) SetCacheReadPrice(v float64) *ModelCatalogBindingCreate {
	_c.mutation.SetCacheReadPrice(v)
	return _c
}

// SetNillableCacheReadPrice sets the "cache_read_price" field if the given value is not nil.
func (_c *ModelCatalogBindingCreate) SetNillableCacheReadPrice(v *float64) *ModelCatalogBindingCreate {
	if v != nil {
		_c.SetCacheReadPrice(*v)
	}
	return _c
}

// SetSearchPricePerCall sets the "search_price_per_call" field.
func (_c *ModelCatalogBindingCreate) SetSearchPricePerCall(v float64) *ModelCatalogBindingCreate {
	_c.mutation.SetSearchPricePerCall(v)
	return _c
}

// SetNillableSearchPricePerCall sets the "search_price_per_call" field if the given value is not nil.
func (_c *ModelCatalogBindingCreate) SetNillableSearchPricePerCall(v *float64) *ModelCatalogBindingCreate {
	if v != nil {
		_c.SetSearchPricePerCall(*v)
	}
	return _c
}

// SetXPostPrice sets the "x_post_price" field.
func (_c *ModelCatalogBindingCreate) SetXPostPrice(v float64) *ModelCatalogBindingCreate {
	_c.mutation.SetXPostPrice(v)
	return _c
}

// SetNillableXPostPrice sets the "x_post_price" field if the given value is not nil.
func (_c *ModelCatalogBindingCreate) SetNillableXPostPrice(v *float64) *ModelCatalogBindingCreate {
	if v != nil {
		_c.SetXPostPrice(*v)
	}
	return _c
}

// SetXUserPrice sets the "x_user_price" field.
func (_c *ModelCatalogBindingCreate) SetXUserPrice(v float64) *ModelCatalogBindingCreate {
	_c.mutation.SetXUserPrice(v)
	return _c
}

// SetNillableXUserPrice sets the "x_user_price" field if the given value is not nil.
func (_c *ModelCatalogBindingCreate) SetNillableXUserPrice(v *float64) *ModelCatalogBindingCreate {
	if v != nil {
		_c.SetXUserPrice(*v)
	}
	return _c
}

// SetUpstreamModel sets the "upstream_model" field.
func (_c *ModelCatalogBindingCreate) SetUpstreamModel(v string) *ModelCatalogBindingCreate {
	_c.mutation.SetUpstreamModel(v)
	return _c
}

// SetNillableUpstreamModel sets the "upstream_model" field if the given value is not nil.
func (_c *ModelCatalogBindingCreate) SetNillableUpstreamModel(v *string) *ModelCatalogBindingCreate {
	if v != nil {
		_c.SetUpstreamModel(*v)
	}
	return _c
}

// SetPriceIntervals sets the "price_intervals" field.
func (_c *ModelCatalogBindingCreate) SetPriceIntervals(v []domain.PriceSegment) *ModelCatalogBindingCreate {
	_c.mutation.SetPriceIntervals(v)
	return _c
}

// SetTimePricing sets the "time_pricing" field.
func (_c *ModelCatalogBindingCreate) SetTimePricing(v *domain.TimePricingSpec) *ModelCatalogBindingCreate {
	_c.mutation.SetTimePricing(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ModelCatalogBindingCreate) SetCreatedAt(v time.Time) *ModelCatalogBindingCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ModelCatalogBindingCreate) SetNillableCreatedAt(v *time.Time) *ModelCatalogBindingCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ModelCatalogBindingCreate) SetUpdatedAt(v time.Time) *ModelCatalogBindingCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ModelCatalogBindingCreate) SetNillableUpdatedAt(v *time.Time) *ModelCatalogBindingCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetEntry sets the "entry" edge to the ModelCatalogEntry entity.
func (_c *ModelCatalogBindingCreate) SetEntry(v *ModelCatalogEntry) *ModelCatalogBindingCreate {
	return _c.SetEntryID(v.ID)
}

// SetAccount sets the "account" edge to the Account entity.
func (_c *ModelCatalogBindingCreate) SetAccount(v *Account) *ModelCatalogBindingCreate {
	return _c.SetAccountID(v.ID)
}

// Mutation returns the ModelCatalogBindingMutation object of the builder.
func (_c *ModelCatalogBindingCreate) Mutation() *ModelCatalogBindingMutation {
	return _c.mutation
}

// Save creates the ModelCatalogBinding in the database.
func (_c *ModelCatalogBindingCreate) Save(ctx context.Context) (*ModelCatalogBinding, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ModelCatalogBindingCreate) SaveX(ctx context.Context) *ModelCatalogBinding {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ModelCatalogBindingCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ModelCatalogBindingCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ModelCatalogBindingCreate) defaults() {
	if _, ok := _c.mutation.UpstreamModel(); !ok {
		v := modelcatalogbinding.DefaultUpstreamModel
		_c.mutation.SetUpstreamModel(v)
	}
	if _, ok := _c.mutation.PriceIntervals(); !ok {
		v := modelcatalogbinding.DefaultPriceIntervals
		_c.mutation.SetPriceIntervals(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := modelcatalogbinding.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := modelcatalogbinding.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ModelCatalogBindingCreate) check() error {
	if _, ok := _c.mutation.EntryID(); !ok {
		return &ValidationError{Name: "entry_id", err: errors.New(`ent: missing required field "ModelCatalogBinding.entry_id"`)}
	}
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "ModelCatalogBinding.account_id"`)}
	}
	if _, ok := _c.mutation.InputPrice(); !ok {
		return &ValidationError{Name: "input_price", err: errors.New(`ent: missing required field "ModelCatalogBinding.input_price"`)}
	}
	if _, ok := _c.mutation.OutputPrice(); !ok {
		return &ValidationError{Name: "output_price", err: errors.New(`ent: missing required field "ModelCatalogBinding.output_price"`)}
	}
	if _, ok := _c.mutation.UpstreamModel(); !ok {
		return &ValidationError{Name: "upstream_model", err: errors.New(`ent: missing required field "ModelCatalogBinding.upstream_model"`)}
	}
	if v, ok := _c.mutation.UpstreamModel(); ok {
		if err := modelcatalogbinding.UpstreamModelValidator(v); err != nil {
			return &ValidationError{Name: "upstream_model", err: fmt.Errorf(`ent: validator failed for field "ModelCatalogBinding.upstream_model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PriceIntervals(); !ok {
		return &ValidationError{Name: "price_intervals", err: errors.New(`ent: missing required field "ModelCatalogBinding.price_intervals"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ModelCatalogBinding.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ModelCatalogBinding.updated_at"`)}
	}
	if len(_c.mutation.EntryIDs()) == 0 {
		return &ValidationError{Name: "entry", err: errors.New(`ent: missing required edge "ModelCatalogBinding.entry"`)}
	}
	if len(_c.mutation.AccountIDs()) == 0 {
		return &ValidationError{Name: "account", err: errors.New(`ent: missing required edge "ModelCatalogBinding.account"`)}
	}
	return nil
}

func (_c *ModelCatalogBindingCreate) sqlSave(ctx context.Context) (*ModelCatalogBinding, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}

func (_c *ModelCatalogBindingCreate) createSpec() (*ModelCatalogBinding, *sqlgraph.CreateSpec) {
	var (
		_node = &ModelCatalogBinding{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(modelcatalogbinding.Table, nil)
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.InputPrice(); ok {
		_spec.SetField(modelcatalogbinding.FieldInputPrice, field.TypeFloat64, value)
		_node.InputPrice = value
	}
	if value, ok := _c.mutation.OutputPrice(); ok {
		_spec.SetField(modelcatalogbinding.FieldOutputPrice, field.TypeFloat64, value)
		_node.OutputPrice = value
	}
	if value, ok := _c.mutation.CacheWritePrice(); ok {
		_spec.SetField(modelcatalogbinding.FieldCacheWritePrice, field.TypeFloat64, value)
		_node.CacheWritePrice = &value
	}
	if value, ok := _c.mutation.CacheWrite1hPrice(); ok {
		_spec.SetField(modelcatalogbinding.FieldCacheWrite1hPrice, field.TypeFloat64, value)
		_node.CacheWrite1hPrice = &value
	}
	if value, ok := _c.mutation.CacheReadPrice(); ok {
		_spec.SetField(modelcatalogbinding.FieldCacheReadPrice, field.TypeFloat64, value)
		_node.CacheReadPrice = &value
	}
	if value, ok := _c.mutation.SearchPricePerCall(); ok {
		_spec.SetField(modelcatalogbinding.FieldSearchPricePerCall, field.TypeFloat64, value)
		_node.SearchPricePerCall = &value
	}
	if value, ok := _c.mutation.XPostPrice(); ok {
		_spec.SetField(modelcatalogbinding.FieldXPostPrice, field.TypeFloat64, value)
		_node.XPostPrice = &value
	}
	if value, ok := _c.mutation.XUserPrice(); ok {
		_spec.SetField(modelcatalogbinding.FieldXUserPrice, field.TypeFloat64, value)
		_node.XUserPrice = &value
	}
	if value, ok := _c.mutation.UpstreamModel(); ok {
		_spec.SetField(modelcatalogbinding.FieldUpstreamModel, field.TypeString, value)
		_node.UpstreamModel = value
	}
	if value, ok := _c.mutation.PriceIntervals(); ok {
		_spec.SetField(modelcatalogbinding.FieldPriceIntervals, field.TypeJSON, value)
		_node.PriceIntervals = value
	}
	if value, ok := _c.mutation.TimePricing(); ok {
		_spec.SetField(modelcatalogbinding.FieldTimePricing, field.TypeJSON, value)
		_node.TimePricing = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(modelcatalogbinding.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(modelcatalogbinding.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.EntryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   modelcatalogbinding.EntryTable,
			Columns: []string{modelcatalogbinding.EntryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelcatalogentry.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.EntryID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   modelcatalogbinding.AccountTable,
			Columns: []string{modelcatalogbinding.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AccountID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ModelCatalogBinding.Create().
//		SetEntryID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ModelCatalogBindingUpsert) {
//			SetEntryID(v+v).
//		}).
//		Exec(ctx)
func (_c *ModelCatalogBindingCreate) OnConflict(opts ...sql.ConflictOption) *ModelCatalogBindingUpsertOne {
	_c.conflict = opts
	return &ModelCatalogBindingUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ModelCatalogBinding.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ModelCatalogBindingCreate) OnConflictColumns(columns ...string) *ModelCatalogBindingUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ModelCatalogBindingUpsertOne{
		create: _c,
	}
}

type (
	// ModelCatalogBindingUpsertOne is the builder for "upsert"-ing
	//  one ModelCatalogBinding node.
	ModelCatalogBindingUpsertOne struct {
		create *ModelCatalogBindingCreate
	}

	// ModelCatalogBindingUpsert is the "OnConflict" setter.
	ModelCatalogBindingUpsert struct {
		*sql.UpdateSet
	}
)

// SetEntryID sets the "entry_id" field.
func (u *ModelCatalogBindingUpsert) SetEntryID(v int64) *ModelCatalogBindingUpsert {
	u.Set(modelcatalogbinding.FieldEntryID, v)
	return u
}

// UpdateEntryID sets the "entry_id" field to the value that was provided on create.
func (u *ModelCatalogBindingUpsert) UpdateEntryID() *ModelCatalogBindingUpsert {
	u.SetExcluded(modelcatalogbinding.FieldEntryID)
	return u
}

// SetAccountID sets the "account_id" field.
func (u *ModelCatalogBindingUpsert) SetAccountID(v int64) *ModelCatalogBindingUpsert {
	u.Set(modelcatalogbinding.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *ModelCatalogBindingUpsert) UpdateAccountID() *ModelCatalogBindingUpsert {
	u.SetExcluded(modelcatalogbinding.FieldAccountID)
	return u
}

// SetInputPrice sets the "input_price" field.
func (u *ModelCatalogBindingUpsert) SetInputPrice(v float64) *ModelCatalogBindingUpsert {
	u.Set(modelcatalogbinding.FieldInputPrice, v)
	return u
}

// UpdateInputPrice sets the "input_price" field to the value that was provided on create.
func (u *ModelCatalogBindingUpsert) UpdateInputPrice() *ModelCatalogBindingUpsert {
	u.SetExcluded(modelcatalogbinding.FieldInputPrice)
	return u
}

// AddInputPrice adds v to the "input_price" field.
func (u *ModelCatalogBindingUpsert) AddInputPrice(v float64) *ModelCatalogBindingUpsert {
	u.Add(modelcatalogbinding.FieldInputPrice, v)
	return u
}

// SetOutputPrice sets the "output_price" field.
func (u *ModelCatalogBindingUpsert) SetOutputPrice(v float64) *ModelCatalogBindingUpsert {
	u.Set(modelcatalogbinding.FieldOutputPrice, v)
	return u
}

// UpdateOutputPrice sets the "output_price" field to the value that was provided on create.
func (u *ModelCatalogBindingUpsert) UpdateOutputPrice() *ModelCatalogBindingUpsert {
	u.SetExcluded(modelcatalogbinding.FieldOutputPrice)
	return u
}

// AddOutputPrice adds v to the "output_price" field.
func (u *ModelCatalogBindingUpsert) AddOutputPrice(v float64) *ModelCatalogBindingUpsert {
	u.Add(modelcatalogbinding.FieldOutputPrice, v)
	return u
}

// SetCacheWritePrice sets the "cache_write_price" field.
func (u *ModelCatalogBindingUpsert) SetCacheWritePrice(v float64) *ModelCatalogBindingUpsert {
	u.Set(modelcatalogbinding.FieldCacheWritePrice, v)
	return u
}

// UpdateCacheWritePrice sets the "cache_write_price" field to the value that was provided on create.
func (u *ModelCatalogBindingUpsert) UpdateCacheWritePrice() *ModelCatalogBindingUpsert {
	u.SetExcluded(modelcatalogbinding.FieldCacheWritePrice)
	return u
}

// AddCacheWritePrice adds v to the "cache_write_price" field.
func (u *ModelCatalogBindingUpsert) AddCacheWritePrice(v float64) *ModelCatalogBindingUpsert {
	u.Add(modelcatalogbinding.FieldCacheWritePrice, v)
	return u
}

// ClearCacheWritePrice clears the value of the "cache_write_price" field.
func (u *ModelCatalogBindingUpsert) ClearCacheWritePrice() *ModelCatalogBindingUpsert {
	u.SetNull(modelcatalogbinding.FieldCacheWritePrice)
	return u
}

// SetCacheWrite1hPrice sets the "cache_write_1h_price" field.
func (u *ModelCatalogBindingUpsert) SetCacheWrite1hPrice(v float64) *ModelCatalogBindingUpsert {
	u.Set(modelcatalogbinding.FieldCacheWrite1hPrice, v)
	return u
}

// UpdateCacheWrite1hPrice sets the "cache_write_1h_price" field to the value that was provided on create.
func (u *ModelCatalogBindingUpsert) UpdateCacheWrite1hPrice() *ModelCatalogBindingUpsert {
	u.SetExcluded(modelcatalogbinding.FieldCacheWrite1hPrice)
	return u
}

// AddCacheWrite1hPrice adds v to the "cache_write_1h_price" field.
func (u *ModelCatalogBindingUpsert) AddCacheWrite1hPrice(v float64) *ModelCatalogBindingUpsert {
	u.Add(modelcatalogbinding.FieldCacheWrite1hPrice, v)
	return u
}

// ClearCacheWrite1hPrice clears the value of the "cache_write_1h_price" field.
func (u *ModelCatalogBindingUpsert) ClearCacheWrite1hPrice() *ModelCatalogBindingUpsert {
	u.SetNull(modelcatalogbinding.FieldCacheWrite1hPrice)
	return u
}

// SetCacheReadPrice sets the "cache_read_price" field.
func (u *ModelCatalogBindingUpsert) SetCacheReadPrice(v float64) *ModelCatalogBindingUpsert {
	u.Set(modelcatalogbinding.FieldCacheReadPrice, v)
	return u
}

// UpdateCacheReadPrice sets the "cache_read_price" field to the value that was provided on create.
func (u *ModelCatalogBindingUpsert) UpdateCacheReadPrice() *ModelCatalogBindingUpsert {
	u.SetExcluded(modelcatalogbinding.FieldCacheReadPrice)
	return u
}

// AddCacheReadPrice adds v to the "cache_read_price" field.
func (u *ModelCatalogBindingUpsert) AddCacheReadPrice(v float64) *ModelCatalogBindingUpsert {
	u.Add(modelcatalogbinding.FieldCacheReadPrice, v)
	return u
}

// ClearCacheReadPrice clears the value of the "cache_read_price" field.
func (u *ModelCatalogBindingUpsert) ClearCacheReadPrice() *ModelCatalogBindingUpsert {
	u.SetNull(modelcatalogbinding.FieldCacheReadPrice)
	return u
}

// SetSearchPricePerCall sets the "search_price_per_call" field.
func (u *ModelCatalogBindingUpsert) SetSearchPricePerCall(v float64) *ModelCatalogBindingUpsert {
	u.Set(modelcatalogbinding.FieldSearchPricePerCall, v)
	return u
}

// UpdateSearchPricePerCall sets the "search_price_per_call" field to the value that was provided on create.
func (u *ModelCatalogBindingUpsert) UpdateSearchPricePerCall() *ModelCatalogBindingUpsert {
	u.SetExcluded(modelcatalogbinding.FieldSearchPricePerCall)
	return u
}

// AddSearchPricePerCall adds v to the "search_price_per_call" field.
func (u *ModelCatalogBindingUpsert) AddSearchPricePerCall(v float64) *ModelCatalogBindingUpsert {
	u.Add(modelcatalogbinding.FieldSearchPricePerCall, v)
	return u
}

// ClearSearchPricePerCall clears the value of the "search_price_per_call" field.
func (u *ModelCatalogBindingUpsert) ClearSearchPricePerCall() *ModelCatalogBindingUpsert {
	u.SetNull(modelcatalogbinding.FieldSearchPricePerCall)
	return u
}

// SetXPostPrice sets the "x_post_price" field.
func (u *ModelCatalogBindingUpsert) SetXPostPrice(v float64) *ModelCatalogBindingUpsert {
	u.Set(modelcatalogbinding.FieldXPostPrice, v)
	return u
}

// UpdateXPostPrice sets the "x_post_price" field to the value that was provided on create.
func (u *ModelCatalogBindingUpsert) UpdateXPostPrice() *ModelCatalogBindingUpsert {
	u.SetExcluded(modelcatalogbinding.FieldXPostPrice)
	return u
}

// AddXPostPrice adds v to the "x_post_price" field.
func (u *ModelCatalogBindingUpsert) AddXPostPrice(v float64) *ModelCatalogBindingUpsert {
	u.Add(modelcatalogbinding.FieldXPostPrice, v)
	return u
}

// ClearXPostPrice clears the value of the "x_post_price" field.
func (u *ModelCatalogBindingUpsert) ClearXPostPrice() *ModelCatalogBindingUpsert {
	u.SetNull(modelcatalogbinding.FieldXPostPrice)
	return u
}

// SetXUserPrice sets the "x_user_price" field.
func (u *ModelCatalogBindingUpsert) SetXUserPrice(v float64) *ModelCatalogBindingUpsert {
	u.Set(modelcatalogbinding.FieldXUserPrice, v)
	return u
}

// UpdateXUserPrice sets the "x_user_price" field to the value that was provided on create.
func (u *ModelCatalogBindingUpsert) UpdateXUserPrice() *ModelCatalogBindingUpsert {
	u.SetExcluded(modelcatalogbinding.FieldXUserPrice)
	return u
}

// AddXUserPrice adds v to the "x_user_price" field.
func (u *ModelCatalogBindingUpsert) AddXUserPrice(v float64) *ModelCatalogBindingUpsert {
	u.Add(modelcatalogbinding.FieldXUserPrice, v)
	return u
}

// ClearXUserPrice clears the value of the "x_user_price" field.
func (u *ModelCatalogBindingUpsert) ClearXUserPrice() *ModelCatalogBindingUpsert {
	u.SetNull(modelcatalogbinding.FieldXUserPrice)
	return u
}

// SetUpstreamModel sets the "upstream_model" field.
func (u *ModelCatalogBindingUpsert) SetUpstreamModel(v string) *ModelCatalogBindingUpsert {
	u.Set(modelcatalogbinding.FieldUpstreamModel, v)
	return u
}

// UpdateUpstreamModel sets the "upstream_model" field to the value that was provided on create.
func (u *ModelCatalogBindingUpsert) UpdateUpstreamModel() *ModelCatalogBindingUpsert {
	u.SetExcluded(modelcatalogbinding.FieldUpstreamModel)
	return u
}

// SetPriceIntervals sets the "price_intervals" field.
func (u *ModelCatalogBindingUpsert) SetPriceIntervals(v []domain.PriceSegment) *ModelCatalogBindingUpsert {
	u.Set(modelcatalogbinding.FieldPriceIntervals, v)
	return u
}

// UpdatePriceIntervals sets the "price_intervals" field to the value that was provided on create.
func (u *ModelCatalogBindingUpsert) UpdatePriceIntervals() *ModelCatalogBindingUpsert {
	u.SetExcluded(modelcatalogbinding.FieldPriceIntervals)
	return u
}

// SetTimePricing sets the "time_pricing" field.
func (u *ModelCatalogBindingUpsert) SetTimePricing(v *domain.TimePricingSpec) *ModelCatalogBindingUpsert {
	u.Set(modelcatalogbinding.FieldTimePricing, v)
	return u
}

// UpdateTimePricing sets the "time_pricing" field to the value that was provided on create.
func (u *ModelCatalogBindingUpsert) UpdateTimePricing() *ModelCatalogBindingUpsert {
	u.SetExcluded(modelcatalogbinding.FieldTimePricing)
	return u
}

// ClearTimePricing clears the value of the "time_pricing" field.
func (u *ModelCatalogBindingUpsert) ClearTimePricing() *ModelCatalogBindingUpsert {
	u.SetNull(modelcatalogbinding.FieldTimePricing)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ModelCatalogBindingUpsert) SetUpdatedAt(v time.Time) *ModelCatalogBindingUpsert {
	u.Set(modelcatalogbinding.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ModelCatalogBindingUpsert) UpdateUpdatedAt() *ModelCatalogBindingUpsert {
	u.SetExcluded(modelcatalogbinding.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ModelCatalogBinding.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ModelCatalogBindingUpsertOne) UpdateNewValues() *ModelCatalogBindingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(modelcatalogbinding.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ModelCatalogBinding.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ModelCatalogBindingUpsertOne) Ignore() *ModelCatalogBindingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ModelCatalogBindingUpsertOne) DoNothing() *ModelCatalogBindingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ModelCatalogBindingCreate.OnConflict
// documentation for more info.
func (u *ModelCatalogBindingUpsertOne) Update(set func(*ModelCatalogBindingUpsert)) *ModelCatalogBindingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ModelCatalogBindingUpsert{UpdateSet: update})
	}))
	return u
}

// SetEntryID sets the "entry_id" field.
func (u *ModelCatalogBindingUpsertOne) SetEntryID(v int64) *ModelCatalogBindingUpsertOne {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.SetEntryID(v)
	})
}

// UpdateEntryID sets the "entry_id" field to the value that was provided on create.
func (u *ModelCatalogBindingUpsertOne) UpdateEntryID() *ModelCatalogBindingUpsertOne {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.UpdateEntryID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *ModelCatalogBindingUpsertOne) SetAccountID(v int64) *ModelCatalogBindingUpsertOne {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *ModelCatalogBindingUpsertOne) UpdateAccountID() *ModelCatalogBindingUpsertOne {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.UpdateAccountID()
	})
}

// SetInputPrice sets the "input_price" field.
func (u *ModelCatalogBindingUpsertOne) SetInputPrice(v float64) *ModelCatalogBindingUpsertOne {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.SetInputPrice(v)
	})
}

// AddInputPrice adds v to the "input_price" field.
func (u *ModelCatalogBindingUpsertOne) AddInputPrice(v float64) *ModelCatalogBindingUpsertOne {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.AddInputPrice(v)
	})
}

// UpdateInputPrice sets the "input_price" field to the value that was provided on create.
func (u *ModelCatalogBindingUpsertOne) UpdateInputPrice() *ModelCatalogBindingUpsertOne {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.UpdateInputPrice()
	})
}

// SetOutputPrice sets the "output_price" field.
func (u *ModelCatalogBindingUpsertOne) SetOutputPrice(v float64) *ModelCatalogBindingUpsertOne {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.SetOutputPrice(v)
	})
}

// AddOutputPrice adds v to the "output_price" field.
func (u *ModelCatalogBindingUpsertOne) AddOutputPrice(v float64) *ModelCatalogBindingUpsertOne {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.AddOutputPrice(v)
	})
}

// UpdateOutputPrice sets the "output_price" field to the value that was provided on create.
func (u *ModelCatalogBindingUpsertOne) UpdateOutputPrice() *ModelCatalogBindingUpsertOne {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.UpdateOutputPrice()
	})
}

// SetCacheWritePrice sets the "cache_write_price" field.
func (u *ModelCatalogBindingUpsertOne) SetCacheWritePrice(v float64) *ModelCatalogBindingUpsertOne {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.SetCacheWritePrice(v)
	})
}

// AddCacheWritePrice adds v to the "cache_write_price" field.
func (u *ModelCatalogBindingUpsertOne) AddCacheWritePrice(v float64) *ModelCatalogBindingUpsertOne {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.AddCacheWritePrice(v)
	})
}

// UpdateCacheWritePrice sets the "cache_write_price" field to the value that was provided on create.
func (u *ModelCatalogBindingUpsertOne) UpdateCacheWritePrice() *ModelCatalogBindingUpsertOne {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.UpdateCacheWritePrice()
	})
}

// ClearCacheWritePrice clears the value of the "cache_write_price" field.
func (u *ModelCatalogBindingUpsertOne) ClearCacheWritePrice() *ModelCatalogBindingUpsertOne {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.ClearCacheWritePrice()
	})
}

// SetCacheWrite1hPrice sets the "cache_write_1h_price" field.
func (u *ModelCatalogBindingUpsertOne) SetCacheWrite1hPrice(v float64) *ModelCatalogBindingUpsertOne {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.SetCacheWrite1hPrice(v)
	})
}

// AddCacheWrite1hPrice adds v to the "cache_write_1h_price" field.
func (u *ModelCatalogBindingUpsertOne) AddCacheWrite1hPrice(v float64) *ModelCatalogBindingUpsertOne {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.AddCacheWrite1hPrice(v)
	})
}

// UpdateCacheWrite1hPrice sets the "cache_write_1h_price" field to the value that was provided on create.
func (u *ModelCatalogBindingUpsertOne) UpdateCacheWrite1hPrice() *ModelCatalogBindingUpsertOne {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.UpdateCacheWrite1hPrice()
	})
}

// ClearCacheWrite1hPrice clears the value of the "cache_write_1h_price" field.
func (u *ModelCatalogBindingUpsertOne) ClearCacheWrite1hPrice() *ModelCatalogBindingUpsertOne {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.ClearCacheWrite1hPrice()
	})
}

// SetCacheReadPrice sets the "cache_read_price" field.
func (u *ModelCatalogBindingUpsertOne) SetCacheReadPrice(v float64) *ModelCatalogBindingUpsertOne {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.SetCacheReadPrice(v)
	})
}

// AddCacheReadPrice adds v to the "cache_read_price" field.
func (u *ModelCatalogBindingUpsertOne) AddCacheReadPrice(v float64) *ModelCatalogBindingUpsertOne {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.AddCacheReadPrice(v)
	})
}

// UpdateCacheReadPrice sets the "cache_read_price" field to the value that was provided on create.
func (u *ModelCatalogBindingUpsertOne) UpdateCacheReadPrice() *ModelCatalogBindingUpsertOne {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.UpdateCacheReadPrice()
	})
}

// ClearCacheReadPrice clears the value of the "cache_read_price" field.
func (u *ModelCatalogBindingUpsertOne) ClearCacheReadPrice() *ModelCatalogBindingUpsertOne {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.ClearCacheReadPrice()
	})
}

// SetSearchPricePerCall sets the "search_price_per_call" field.
func (u *ModelCatalogBindingUpsertOne) SetSearchPricePerCall(v float64) *ModelCatalogBindingUpsertOne {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.SetSearchPricePerCall(v)
	})
}

// AddSearchPricePerCall adds v to the "search_price_per_call" field.
func (u *ModelCatalogBindingUpsertOne) AddSearchPricePerCall(v float64) *ModelCatalogBindingUpsertOne {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.AddSearchPricePerCall(v)
	})
}

// UpdateSearchPricePerCall sets the "search_price_per_call" field to the value that was provided on create.
func (u *ModelCatalogBindingUpsertOne) UpdateSearchPricePerCall() *ModelCatalogBindingUpsertOne {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.UpdateSearchPricePerCall()
	})
}

// ClearSearchPricePerCall clears the value of the "search_price_per_call" field.
func (u *ModelCatalogBindingUpsertOne) ClearSearchPricePerCall() *ModelCatalogBindingUpsertOne {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.ClearSearchPricePerCall()
	})
}

// SetXPostPrice sets the "x_post_price" field.
func (u *ModelCatalogBindingUpsertOne) SetXPostPrice(v float64) *ModelCatalogBindingUpsertOne {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.SetXPostPrice(v)
	})
}

// AddXPostPrice adds v to the "x_post_price" field.
func (u *ModelCatalogBindingUpsertOne) AddXPostPrice(v float64) *ModelCatalogBindingUpsertOne {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.AddXPostPrice(v)
	})
}

// UpdateXPostPrice sets the "x_post_price" field to the value that was provided on create.
func (u *ModelCatalogBindingUpsertOne) UpdateXPostPrice() *ModelCatalogBindingUpsertOne {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.UpdateXPostPrice()
	})
}

// ClearXPostPrice clears the value of the "x_post_price" field.
func (u *ModelCatalogBindingUpsertOne) ClearXPostPrice() *ModelCatalogBindingUpsertOne {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.ClearXPostPrice()
	})
}

// SetXUserPrice sets the "x_user_price" field.
func (u *ModelCatalogBindingUpsertOne) SetXUserPrice(v float64) *ModelCatalogBindingUpsertOne {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.SetXUserPrice(v)
	})
}

// AddXUserPrice adds v to the "x_user_price" field.
func (u *ModelCatalogBindingUpsertOne) AddXUserPrice(v float64) *ModelCatalogBindingUpsertOne {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.AddXUserPrice(v)
	})
}

// UpdateXUserPrice sets the "x_user_price" field to the value that was provided on create.
func (u *ModelCatalogBindingUpsertOne) UpdateXUserPrice() *ModelCatalogBindingUpsertOne {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.UpdateXUserPrice()
	})
}

// ClearXUserPrice clears the value of the "x_user_price" field.
func (u *ModelCatalogBindingUpsertOne) ClearXUserPrice() *ModelCatalogBindingUpsertOne {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.ClearXUserPrice()
	})
}

// SetUpstreamModel sets the "upstream_model" field.
func (u *ModelCatalogBindingUpsertOne) SetUpstreamModel(v string) *ModelCatalogBindingUpsertOne {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.SetUpstreamModel(v)
	})
}

// UpdateUpstreamModel sets the "upstream_model" field to the value that was provided on create.
func (u *ModelCatalogBindingUpsertOne) UpdateUpstreamModel() *ModelCatalogBindingUpsertOne {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.UpdateUpstreamModel()
	})
}

// SetPriceIntervals sets the "price_intervals" field.
func (u *ModelCatalogBindingUpsertOne) SetPriceIntervals(v []domain.PriceSegment) *ModelCatalogBindingUpsertOne {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.SetPriceIntervals(v)
	})
}

// UpdatePriceIntervals sets the "price_intervals" field to the value that was provided on create.
func (u *ModelCatalogBindingUpsertOne) UpdatePriceIntervals() *ModelCatalogBindingUpsertOne {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.UpdatePriceIntervals()
	})
}

// SetTimePricing sets the "time_pricing" field.
func (u *ModelCatalogBindingUpsertOne) SetTimePricing(v *domain.TimePricingSpec) *ModelCatalogBindingUpsertOne {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.SetTimePricing(v)
	})
}

// UpdateTimePricing sets the "time_pricing" field to the value that was provided on create.
func (u *ModelCatalogBindingUpsertOne) UpdateTimePricing() *ModelCatalogBindingUpsertOne {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.UpdateTimePricing()
	})
}

// ClearTimePricing clears the value of the "time_pricing" field.
func (u *ModelCatalogBindingUpsertOne) ClearTimePricing() *ModelCatalogBindingUpsertOne {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.ClearTimePricing()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ModelCatalogBindingUpsertOne) SetUpdatedAt(v time.Time) *ModelCatalogBindingUpsertOne {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ModelCatalogBindingUpsertOne) UpdateUpdatedAt() *ModelCatalogBindingUpsertOne {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ModelCatalogBindingUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ModelCatalogBindingCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ModelCatalogBindingUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// ModelCatalogBindingCreateBulk is the builder for creating many ModelCatalogBinding entities in bulk.
type ModelCatalogBindingCreateBulk struct {
	config
	err      error
	builders []*ModelCatalogBindingCreate
	conflict []sql.ConflictOption
}

// Save creates the ModelCatalogBinding entities in the database.
func (_c *ModelCatalogBindingCreateBulk) Save(ctx context.Context) ([]*ModelCatalogBinding, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ModelCatalogBinding, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ModelCatalogBindingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ModelCatalogBindingCreateBulk) SaveX(ctx context.Context) []*ModelCatalogBinding {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ModelCatalogBindingCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ModelCatalogBindingCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ModelCatalogBinding.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ModelCatalogBindingUpsert) {
//			SetEntryID(v+v).
//		}).
//		Exec(ctx)
func (_c *ModelCatalogBindingCreateBulk) OnConflict(opts ...sql.ConflictOption) *ModelCatalogBindingUpsertBulk {
	_c.conflict = opts
	return &ModelCatalogBindingUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ModelCatalogBinding.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ModelCatalogBindingCreateBulk) OnConflictColumns(columns ...string) *ModelCatalogBindingUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ModelCatalogBindingUpsertBulk{
		create: _c,
	}
}

// ModelCatalogBindingUpsertBulk is the builder for "upsert"-ing
// a bulk of ModelCatalogBinding nodes.
type ModelCatalogBindingUpsertBulk struct {
	create *ModelCatalogBindingCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ModelCatalogBinding.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ModelCatalogBindingUpsertBulk) UpdateNewValues() *ModelCatalogBindingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(modelcatalogbinding.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ModelCatalogBinding.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ModelCatalogBindingUpsertBulk) Ignore() *ModelCatalogBindingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ModelCatalogBindingUpsertBulk) DoNothing() *ModelCatalogBindingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ModelCatalogBindingCreateBulk.OnConflict
// documentation for more info.
func (u *ModelCatalogBindingUpsertBulk) Update(set func(*ModelCatalogBindingUpsert)) *ModelCatalogBindingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ModelCatalogBindingUpsert{UpdateSet: update})
	}))
	return u
}

// SetEntryID sets the "entry_id" field.
func (u *ModelCatalogBindingUpsertBulk) SetEntryID(v int64) *ModelCatalogBindingUpsertBulk {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.SetEntryID(v)
	})
}

// UpdateEntryID sets the "entry_id" field to the value that was provided on create.
func (u *ModelCatalogBindingUpsertBulk) UpdateEntryID() *ModelCatalogBindingUpsertBulk {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.UpdateEntryID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *ModelCatalogBindingUpsertBulk) SetAccountID(v int64) *ModelCatalogBindingUpsertBulk {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *ModelCatalogBindingUpsertBulk) UpdateAccountID() *ModelCatalogBindingUpsertBulk {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.UpdateAccountID()
	})
}

// SetInputPrice sets the "input_price" field.
func (u *ModelCatalogBindingUpsertBulk) SetInputPrice(v float64) *ModelCatalogBindingUpsertBulk {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.SetInputPrice(v)
	})
}

// AddInputPrice adds v to the "input_price" field.
func (u *ModelCatalogBindingUpsertBulk) AddInputPrice(v float64) *ModelCatalogBindingUpsertBulk {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.AddInputPrice(v)
	})
}

// UpdateInputPrice sets the "input_price" field to the value that was provided on create.
func (u *ModelCatalogBindingUpsertBulk) UpdateInputPrice() *ModelCatalogBindingUpsertBulk {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.UpdateInputPrice()
	})
}

// SetOutputPrice sets the "output_price" field.
func (u *ModelCatalogBindingUpsertBulk) SetOutputPrice(v float64) *ModelCatalogBindingUpsertBulk {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.SetOutputPrice(v)
	})
}

// AddOutputPrice adds v to the "output_price" field.
func (u *ModelCatalogBindingUpsertBulk) AddOutputPrice(v float64) *ModelCatalogBindingUpsertBulk {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.AddOutputPrice(v)
	})
}

// UpdateOutputPrice sets the "output_price" field to the value that was provided on create.
func (u *ModelCatalogBindingUpsertBulk) UpdateOutputPrice() *ModelCatalogBindingUpsertBulk {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.UpdateOutputPrice()
	})
}

// SetCacheWritePrice sets the "cache_write_price" field.
func (u *ModelCatalogBindingUpsertBulk) SetCacheWritePrice(v float64) *ModelCatalogBindingUpsertBulk {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.SetCacheWritePrice(v)
	})
}

// AddCacheWritePrice adds v to the "cache_write_price" field.
func (u *ModelCatalogBindingUpsertBulk) AddCacheWritePrice(v float64) *ModelCatalogBindingUpsertBulk {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.AddCacheWritePrice(v)
	})
}

// UpdateCacheWritePrice sets the "cache_write_price" field to the value that was provided on create.
func (u *ModelCatalogBindingUpsertBulk) UpdateCacheWritePrice() *ModelCatalogBindingUpsertBulk {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.UpdateCacheWritePrice()
	})
}

// ClearCacheWritePrice clears the value of the "cache_write_price" field.
func (u *ModelCatalogBindingUpsertBulk) ClearCacheWritePrice() *ModelCatalogBindingUpsertBulk {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.ClearCacheWritePrice()
	})
}

// SetCacheWrite1hPrice sets the "cache_write_1h_price" field.
func (u *ModelCatalogBindingUpsertBulk) SetCacheWrite1hPrice(v float64) *ModelCatalogBindingUpsertBulk {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.SetCacheWrite1hPrice(v)
	})
}

// AddCacheWrite1hPrice adds v to the "cache_write_1h_price" field.
func (u *ModelCatalogBindingUpsertBulk) AddCacheWrite1hPrice(v float64) *ModelCatalogBindingUpsertBulk {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.AddCacheWrite1hPrice(v)
	})
}

// UpdateCacheWrite1hPrice sets the "cache_write_1h_price" field to the value that was provided on create.
func (u *ModelCatalogBindingUpsertBulk) UpdateCacheWrite1hPrice() *ModelCatalogBindingUpsertBulk {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.UpdateCacheWrite1hPrice()
	})
}

// ClearCacheWrite1hPrice clears the value of the "cache_write_1h_price" field.
func (u *ModelCatalogBindingUpsertBulk) ClearCacheWrite1hPrice() *ModelCatalogBindingUpsertBulk {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.ClearCacheWrite1hPrice()
	})
}

// SetCacheReadPrice sets the "cache_read_price" field.
func (u *ModelCatalogBindingUpsertBulk) SetCacheReadPrice(v float64) *ModelCatalogBindingUpsertBulk {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.SetCacheReadPrice(v)
	})
}

// AddCacheReadPrice adds v to the "cache_read_price" field.
func (u *ModelCatalogBindingUpsertBulk) AddCacheReadPrice(v float64) *ModelCatalogBindingUpsertBulk {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.AddCacheReadPrice(v)
	})
}

// UpdateCacheReadPrice sets the "cache_read_price" field to the value that was provided on create.
func (u *ModelCatalogBindingUpsertBulk) UpdateCacheReadPrice() *ModelCatalogBindingUpsertBulk {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.UpdateCacheReadPrice()
	})
}

// ClearCacheReadPrice clears the value of the "cache_read_price" field.
func (u *ModelCatalogBindingUpsertBulk) ClearCacheReadPrice() *ModelCatalogBindingUpsertBulk {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.ClearCacheReadPrice()
	})
}

// SetSearchPricePerCall sets the "search_price_per_call" field.
func (u *ModelCatalogBindingUpsertBulk) SetSearchPricePerCall(v float64) *ModelCatalogBindingUpsertBulk {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.SetSearchPricePerCall(v)
	})
}

// AddSearchPricePerCall adds v to the "search_price_per_call" field.
func (u *ModelCatalogBindingUpsertBulk) AddSearchPricePerCall(v float64) *ModelCatalogBindingUpsertBulk {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.AddSearchPricePerCall(v)
	})
}

// UpdateSearchPricePerCall sets the "search_price_per_call" field to the value that was provided on create.
func (u *ModelCatalogBindingUpsertBulk) UpdateSearchPricePerCall() *ModelCatalogBindingUpsertBulk {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.UpdateSearchPricePerCall()
	})
}

// ClearSearchPricePerCall clears the value of the "search_price_per_call" field.
func (u *ModelCatalogBindingUpsertBulk) ClearSearchPricePerCall() *ModelCatalogBindingUpsertBulk {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.ClearSearchPricePerCall()
	})
}

// SetXPostPrice sets the "x_post_price" field.
func (u *ModelCatalogBindingUpsertBulk) SetXPostPrice(v float64) *ModelCatalogBindingUpsertBulk {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.SetXPostPrice(v)
	})
}

// AddXPostPrice adds v to the "x_post_price" field.
func (u *ModelCatalogBindingUpsertBulk) AddXPostPrice(v float64) *ModelCatalogBindingUpsertBulk {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.AddXPostPrice(v)
	})
}

// UpdateXPostPrice sets the "x_post_price" field to the value that was provided on create.
func (u *ModelCatalogBindingUpsertBulk) UpdateXPostPrice() *ModelCatalogBindingUpsertBulk {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.UpdateXPostPrice()
	})
}

// ClearXPostPrice clears the value of the "x_post_price" field.
func (u *ModelCatalogBindingUpsertBulk) ClearXPostPrice() *ModelCatalogBindingUpsertBulk {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.ClearXPostPrice()
	})
}

// SetXUserPrice sets the "x_user_price" field.
func (u *ModelCatalogBindingUpsertBulk) SetXUserPrice(v float64) *ModelCatalogBindingUpsertBulk {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.SetXUserPrice(v)
	})
}

// AddXUserPrice adds v to the "x_user_price" field.
func (u *ModelCatalogBindingUpsertBulk) AddXUserPrice(v float64) *ModelCatalogBindingUpsertBulk {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.AddXUserPrice(v)
	})
}

// UpdateXUserPrice sets the "x_user_price" field to the value that was provided on create.
func (u *ModelCatalogBindingUpsertBulk) UpdateXUserPrice() *ModelCatalogBindingUpsertBulk {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.UpdateXUserPrice()
	})
}

// ClearXUserPrice clears the value of the "x_user_price" field.
func (u *ModelCatalogBindingUpsertBulk) ClearXUserPrice() *ModelCatalogBindingUpsertBulk {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.ClearXUserPrice()
	})
}

// SetUpstreamModel sets the "upstream_model" field.
func (u *ModelCatalogBindingUpsertBulk) SetUpstreamModel(v string) *ModelCatalogBindingUpsertBulk {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.SetUpstreamModel(v)
	})
}

// UpdateUpstreamModel sets the "upstream_model" field to the value that was provided on create.
func (u *ModelCatalogBindingUpsertBulk) UpdateUpstreamModel() *ModelCatalogBindingUpsertBulk {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.UpdateUpstreamModel()
	})
}

// SetPriceIntervals sets the "price_intervals" field.
func (u *ModelCatalogBindingUpsertBulk) SetPriceIntervals(v []domain.PriceSegment) *ModelCatalogBindingUpsertBulk {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.SetPriceIntervals(v)
	})
}

// UpdatePriceIntervals sets the "price_intervals" field to the value that was provided on create.
func (u *ModelCatalogBindingUpsertBulk) UpdatePriceIntervals() *ModelCatalogBindingUpsertBulk {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.UpdatePriceIntervals()
	})
}

// SetTimePricing sets the "time_pricing" field.
func (u *ModelCatalogBindingUpsertBulk) SetTimePricing(v *domain.TimePricingSpec) *ModelCatalogBindingUpsertBulk {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.SetTimePricing(v)
	})
}

// UpdateTimePricing sets the "time_pricing" field to the value that was provided on create.
func (u *ModelCatalogBindingUpsertBulk) UpdateTimePricing() *ModelCatalogBindingUpsertBulk {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.UpdateTimePricing()
	})
}

// ClearTimePricing clears the value of the "time_pricing" field.
func (u *ModelCatalogBindingUpsertBulk) ClearTimePricing() *ModelCatalogBindingUpsertBulk {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.ClearTimePricing()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ModelCatalogBindingUpsertBulk) SetUpdatedAt(v time.Time) *ModelCatalogBindingUpsertBulk {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ModelCatalogBindingUpsertBulk) UpdateUpdatedAt() *ModelCatalogBindingUpsertBulk {
	return u.Update(func(s *ModelCatalogBindingUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ModelCatalogBindingUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ModelCatalogBindingCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ModelCatalogBindingCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ModelCatalogBindingUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
