// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/modelcatalogentry"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionplan"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionplanmodel"
)

// SubscriptionPlanModelCreate is the builder for creating a SubscriptionPlanModel entity.
type SubscriptionPlanModelCreate struct {
	config
	mutation *SubscriptionPlanModelMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetPlanID sets the "plan_id" field.
func (_c *SubscriptionPlanModelCreate) SetPlanID(v int64) *SubscriptionPlanModelCreate {
	_c.mutation.SetPlanID(v)
	return _c
}

// SetEntryID sets the "entry_id" field.
func (_c *SubscriptionPlanModelCreate) SetEntryID(v int64) *SubscriptionPlanModelCreate {
	_c.mutation.SetEntryID(v)
	return _c
}

// SetPlan sets the "plan" edge to the SubscriptionPlan entity.
func (_c *SubscriptionPlanModelCreate) SetPlan(v *SubscriptionPlan) *SubscriptionPlanModelCreate {
	return _c.SetPlanID(v.ID)
}

// SetEntry sets the "entry" edge to the ModelCatalogEntry entity.
func (_c *SubscriptionPlanModelCreate) SetEntry(v *ModelCatalogEntry) *SubscriptionPlanModelCreate {
	return _c.SetEntryID(v.ID)
}

// Mutation returns the SubscriptionPlanModelMutation object of the builder.
func (_c *SubscriptionPlanModelCreate) Mutation() *SubscriptionPlanModelMutation {
	return _c.mutation
}

// Save creates the SubscriptionPlanModel in the database.
func (_c *SubscriptionPlanModelCreate) Save(ctx context.Context) (*SubscriptionPlanModel, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SubscriptionPlanModelCreate) SaveX(ctx context.Context) *SubscriptionPlanModel {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubscriptionPlanModelCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubscriptionPlanModelCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SubscriptionPlanModelCreate) check() error {
	if _, ok := _c.mutation.PlanID(); !ok {
		return &ValidationError{Name: "plan_id", err: errors.New(`ent: missing required field "SubscriptionPlanModel.plan_id"`)}
	}
	if _, ok := _c.mutation.EntryID(); !ok {
		return &ValidationError{Name: "entry_id", err: errors.New(`ent: missing required field "SubscriptionPlanModel.entry_id"`)}
	}
	if len(_c.mutation.PlanIDs()) == 0 {
		return &ValidationError{Name: "plan", err: errors.New(`ent: missing required edge "SubscriptionPlanModel.plan"`)}
	}
	if len(_c.mutation.EntryIDs()) == 0 {
		return &ValidationError{Name: "entry", err: errors.New(`ent: missing required edge "SubscriptionPlanModel.entry"`)}
	}
	return nil
}

func (_c *SubscriptionPlanModelCreate) sqlSave(ctx context.Context) (*SubscriptionPlanModel, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}

func (_c *SubscriptionPlanModelCreate) createSpec() (*SubscriptionPlanModel, *sqlgraph.CreateSpec) {
	var (
		_node = &SubscriptionPlanModel{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(subscriptionplanmodel.Table, nil)
	)
	_spec.OnConflict = _c.conflict
	if nodes := _c.mutation.PlanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   subscriptionplanmodel.PlanTable,
			Columns: []string{subscriptionplanmodel.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionplan.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PlanID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.EntryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   subscriptionplanmodel.EntryTable,
			Columns: []string{subscriptionplanmodel.EntryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelcatalogentry.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.EntryID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SubscriptionPlanModel.Create().
//		SetPlanID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SubscriptionPlanModelUpsert) {
//			SetPlanID(v+v).
//		}).
//		Exec(ctx)
func (_c *SubscriptionPlanModelCreate) OnConflict(opts ...sql.ConflictOption) *SubscriptionPlanModelUpsertOne {
	_c.conflict = opts
	return &SubscriptionPlanModelUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SubscriptionPlanModel.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SubscriptionPlanModelCreate) OnConflictColumns(columns ...string) *SubscriptionPlanModelUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SubscriptionPlanModelUpsertOne{
		create: _c,
	}
}

type (
	// SubscriptionPlanModelUpsertOne is the builder for "upsert"-ing
	//  one SubscriptionPlanModel node.
	SubscriptionPlanModelUpsertOne struct {
		create *SubscriptionPlanModelCreate
	}

	// SubscriptionPlanModelUpsert is the "OnConflict" setter.
	SubscriptionPlanModelUpsert struct {
		*sql.UpdateSet
	}
)

// SetPlanID sets the "plan_id" field.
func (u *SubscriptionPlanModelUpsert) SetPlanID(v int64) *SubscriptionPlanModelUpsert {
	u.Set(subscriptionplanmodel.FieldPlanID, v)
	return u
}

// UpdatePlanID sets the "plan_id" field to the value that was provided on create.
func (u *SubscriptionPlanModelUpsert) UpdatePlanID() *SubscriptionPlanModelUpsert {
	u.SetExcluded(subscriptionplanmodel.FieldPlanID)
	return u
}

// SetEntryID sets the "entry_id" field.
func (u *SubscriptionPlanModelUpsert) SetEntryID(v int64) *SubscriptionPlanModelUpsert {
	u.Set(subscriptionplanmodel.FieldEntryID, v)
	return u
}

// UpdateEntryID sets the "entry_id" field to the value that was provided on create.
func (u *SubscriptionPlanModelUpsert) UpdateEntryID() *SubscriptionPlanModelUpsert {
	u.SetExcluded(subscriptionplanmodel.FieldEntryID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.SubscriptionPlanModel.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SubscriptionPlanModelUpsertOne) UpdateNewValues() *SubscriptionPlanModelUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SubscriptionPlanModel.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SubscriptionPlanModelUpsertOne) Ignore() *SubscriptionPlanModelUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SubscriptionPlanModelUpsertOne) DoNothing() *SubscriptionPlanModelUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SubscriptionPlanModelCreate.OnConflict
// documentation for more info.
func (u *SubscriptionPlanModelUpsertOne) Update(set func(*SubscriptionPlanModelUpsert)) *SubscriptionPlanModelUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SubscriptionPlanModelUpsert{UpdateSet: update})
	}))
	return u
}

// SetPlanID sets the "plan_id" field.
func (u *SubscriptionPlanModelUpsertOne) SetPlanID(v int64) *SubscriptionPlanModelUpsertOne {
	return u.Update(func(s *SubscriptionPlanModelUpsert) {
		s.SetPlanID(v)
	})
}

// UpdatePlanID sets the "plan_id" field to the value that was provided on create.
func (u *SubscriptionPlanModelUpsertOne) UpdatePlanID() *SubscriptionPlanModelUpsertOne {
	return u.Update(func(s *SubscriptionPlanModelUpsert) {
		s.UpdatePlanID()
	})
}

// SetEntryID sets the "entry_id" field.
func (u *SubscriptionPlanModelUpsertOne) SetEntryID(v int64) *SubscriptionPlanModelUpsertOne {
	return u.Update(func(s *SubscriptionPlanModelUpsert) {
		s.SetEntryID(v)
	})
}

// UpdateEntryID sets the "entry_id" field to the value that was provided on create.
func (u *SubscriptionPlanModelUpsertOne) UpdateEntryID() *SubscriptionPlanModelUpsertOne {
	return u.Update(func(s *SubscriptionPlanModelUpsert) {
		s.UpdateEntryID()
	})
}

// Exec executes the query.
func (u *SubscriptionPlanModelUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SubscriptionPlanModelCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SubscriptionPlanModelUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// SubscriptionPlanModelCreateBulk is the builder for creating many SubscriptionPlanModel entities in bulk.
type SubscriptionPlanModelCreateBulk struct {
	config
	err      error
	builders []*SubscriptionPlanModelCreate
	conflict []sql.ConflictOption
}

// Save creates the SubscriptionPlanModel entities in the database.
func (_c *SubscriptionPlanModelCreateBulk) Save(ctx context.Context) ([]*SubscriptionPlanModel, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SubscriptionPlanModel, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SubscriptionPlanModelMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SubscriptionPlanModelCreateBulk) SaveX(ctx context.Context) []*SubscriptionPlanModel {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubscriptionPlanModelCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubscriptionPlanModelCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SubscriptionPlanModel.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SubscriptionPlanModelUpsert) {
//			SetPlanID(v+v).
//		}).
//		Exec(ctx)
func (_c *SubscriptionPlanModelCreateBulk) OnConflict(opts ...sql.ConflictOption) *SubscriptionPlanModelUpsertBulk {
	_c.conflict = opts
	return &SubscriptionPlanModelUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SubscriptionPlanModel.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SubscriptionPlanModelCreateBulk) OnConflictColumns(columns ...string) *SubscriptionPlanModelUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SubscriptionPlanModelUpsertBulk{
		create: _c,
	}
}

// SubscriptionPlanModelUpsertBulk is the builder for "upsert"-ing
// a bulk of SubscriptionPlanModel nodes.
type SubscriptionPlanModelUpsertBulk struct {
	create *SubscriptionPlanModelCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SubscriptionPlanModel.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SubscriptionPlanModelUpsertBulk) UpdateNewValues() *SubscriptionPlanModelUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SubscriptionPlanModel.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SubscriptionPlanModelUpsertBulk) Ignore() *SubscriptionPlanModelUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SubscriptionPlanModelUpsertBulk) DoNothing() *SubscriptionPlanModelUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SubscriptionPlanModelCreateBulk.OnConflict
// documentation for more info.
func (u *SubscriptionPlanModelUpsertBulk) Update(set func(*SubscriptionPlanModelUpsert)) *SubscriptionPlanModelUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SubscriptionPlanModelUpsert{UpdateSet: update})
	}))
	return u
}

// SetPlanID sets the "plan_id" field.
func (u *SubscriptionPlanModelUpsertBulk) SetPlanID(v int64) *SubscriptionPlanModelUpsertBulk {
	return u.Update(func(s *SubscriptionPlanModelUpsert) {
		s.SetPlanID(v)
	})
}

// UpdatePlanID sets the "plan_id" field to the value that was provided on create.
func (u *SubscriptionPlanModelUpsertBulk) UpdatePlanID() *SubscriptionPlanModelUpsertBulk {
	return u.Update(func(s *SubscriptionPlanModelUpsert) {
		s.UpdatePlanID()
	})
}

// SetEntryID sets the "entry_id" field.
func (u *SubscriptionPlanModelUpsertBulk) SetEntryID(v int64) *SubscriptionPlanModelUpsertBulk {
	return u.Update(func(s *SubscriptionPlanModelUpsert) {
		s.SetEntryID(v)
	})
}

// UpdateEntryID sets the "entry_id" field to the value that was provided on create.
func (u *SubscriptionPlanModelUpsertBulk) UpdateEntryID() *SubscriptionPlanModelUpsertBulk {
	return u.Update(func(s *SubscriptionPlanModelUpsert) {
		s.UpdateEntryID()
	})
}

// Exec executes the query.
func (u *SubscriptionPlanModelUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SubscriptionPlanModelCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SubscriptionPlanModelCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SubscriptionPlanModelUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
