// Code generated by ent, DO NOT EDIT.

package modelcatalogentry

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldEQ(FieldUpdatedAt, v))
}

// ModelID applies equality check predicate on the "model_id" field. It's identical to ModelIDEQ.
func ModelID(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldEQ(FieldModelID, v))
}

// DisplayName applies equality check predicate on the "display_name" field. It's identical to DisplayNameEQ.
func DisplayName(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldEQ(FieldDisplayName, v))
}

// Vendor applies equality check predicate on the "vendor" field. It's identical to VendorEQ.
func Vendor(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldEQ(FieldVendor, v))
}

// BillingMode applies equality check predicate on the "billing_mode" field. It's identical to BillingModeEQ.
func BillingMode(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldEQ(FieldBillingMode, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldEQ(FieldStatus, v))
}

// ManagedBy applies equality check predicate on the "managed_by" field. It's identical to ManagedByEQ.
func ManagedBy(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldEQ(FieldManagedBy, v))
}

// InputPrice applies equality check predicate on the "input_price" field. It's identical to InputPriceEQ.
func InputPrice(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldEQ(FieldInputPrice, v))
}

// OutputPrice applies equality check predicate on the "output_price" field. It's identical to OutputPriceEQ.
func OutputPrice(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldEQ(FieldOutputPrice, v))
}

// CacheWritePrice applies equality check predicate on the "cache_write_price" field. It's identical to CacheWritePriceEQ.
func CacheWritePrice(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldEQ(FieldCacheWritePrice, v))
}

// CacheWrite1hPrice applies equality check predicate on the "cache_write_1h_price" field. It's identical to CacheWrite1hPriceEQ.
func CacheWrite1hPrice(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldEQ(FieldCacheWrite1hPrice, v))
}

// CacheReadPrice applies equality check predicate on the "cache_read_price" field. It's identical to CacheReadPriceEQ.
func CacheReadPrice(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldEQ(FieldCacheReadPrice, v))
}

// ImageInputPrice applies equality check predicate on the "image_input_price" field. It's identical to ImageInputPriceEQ.
func ImageInputPrice(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldEQ(FieldImageInputPrice, v))
}

// ImageOutputPrice applies equality check predicate on the "image_output_price" field. It's identical to ImageOutputPriceEQ.
func ImageOutputPrice(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldEQ(FieldImageOutputPrice, v))
}

// ImageCacheReadPrice applies equality check predicate on the "image_cache_read_price" field. It's identical to ImageCacheReadPriceEQ.
func ImageCacheReadPrice(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldEQ(FieldImageCacheReadPrice, v))
}

// InputPricePriority applies equality check predicate on the "input_price_priority" field. It's identical to InputPricePriorityEQ.
func InputPricePriority(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldEQ(FieldInputPricePriority, v))
}

// OutputPricePriority applies equality check predicate on the "output_price_priority" field. It's identical to OutputPricePriorityEQ.
func OutputPricePriority(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldEQ(FieldOutputPricePriority, v))
}

// CacheWritePricePriority applies equality check predicate on the "cache_write_price_priority" field. It's identical to CacheWritePricePriorityEQ.
func CacheWritePricePriority(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldEQ(FieldCacheWritePricePriority, v))
}

// CacheReadPricePriority applies equality check predicate on the "cache_read_price_priority" field. It's identical to CacheReadPricePriorityEQ.
func CacheReadPricePriority(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldEQ(FieldCacheReadPricePriority, v))
}

// PerRequestPrice applies equality check predicate on the "per_request_price" field. It's identical to PerRequestPriceEQ.
func PerRequestPrice(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldEQ(FieldPerRequestPrice, v))
}

// LongContextInputThreshold applies equality check predicate on the "long_context_input_threshold" field. It's identical to LongContextInputThresholdEQ.
func LongContextInputThreshold(v int) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldEQ(FieldLongContextInputThreshold, v))
}

// LongContextThresholdInclusive applies equality check predicate on the "long_context_threshold_inclusive" field. It's identical to LongContextThresholdInclusiveEQ.
func LongContextThresholdInclusive(v bool) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldEQ(FieldLongContextThresholdInclusive, v))
}

// LongContextInputMultiplier applies equality check predicate on the "long_context_input_multiplier" field. It's identical to LongContextInputMultiplierEQ.
func LongContextInputMultiplier(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldEQ(FieldLongContextInputMultiplier, v))
}

// LongContextOutputMultiplier applies equality check predicate on the "long_context_output_multiplier" field. It's identical to LongContextOutputMultiplierEQ.
func LongContextOutputMultiplier(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldEQ(FieldLongContextOutputMultiplier, v))
}

// FastMultiplier applies equality check predicate on the "fast_multiplier" field. It's identical to FastMultiplierEQ.
func FastMultiplier(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldEQ(FieldFastMultiplier, v))
}

// FlexMultiplier applies equality check predicate on the "flex_multiplier" field. It's identical to FlexMultiplierEQ.
func FlexMultiplier(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldEQ(FieldFlexMultiplier, v))
}

// MaxReasoningEffortMultiplier applies equality check predicate on the "max_reasoning_effort_multiplier" field. It's identical to MaxReasoningEffortMultiplierEQ.
func MaxReasoningEffortMultiplier(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldEQ(FieldMaxReasoningEffortMultiplier, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldEQ(FieldNotes, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldLTE(FieldUpdatedAt, v))
}

// ModelIDEQ applies the EQ predicate on the "model_id" field.
func ModelIDEQ(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldEQ(FieldModelID, v))
}

// ModelIDNEQ applies the NEQ predicate on the "model_id" field.
func ModelIDNEQ(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNEQ(FieldModelID, v))
}

// ModelIDIn applies the In predicate on the "model_id" field.
func ModelIDIn(vs ...string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldIn(FieldModelID, vs...))
}

// ModelIDNotIn applies the NotIn predicate on the "model_id" field.
func ModelIDNotIn(vs ...string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNotIn(FieldModelID, vs...))
}

// ModelIDGT applies the GT predicate on the "model_id" field.
func ModelIDGT(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldGT(FieldModelID, v))
}

// ModelIDGTE applies the GTE predicate on the "model_id" field.
func ModelIDGTE(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldGTE(FieldModelID, v))
}

// ModelIDLT applies the LT predicate on the "model_id" field.
func ModelIDLT(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldLT(FieldModelID, v))
}

// ModelIDLTE applies the LTE predicate on the "model_id" field.
func ModelIDLTE(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldLTE(FieldModelID, v))
}

// ModelIDContains applies the Contains predicate on the "model_id" field.
func ModelIDContains(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldContains(FieldModelID, v))
}

// ModelIDHasPrefix applies the HasPrefix predicate on the "model_id" field.
func ModelIDHasPrefix(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldHasPrefix(FieldModelID, v))
}

// ModelIDHasSuffix applies the HasSuffix predicate on the "model_id" field.
func ModelIDHasSuffix(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldHasSuffix(FieldModelID, v))
}

// ModelIDEqualFold applies the EqualFold predicate on the "model_id" field.
func ModelIDEqualFold(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldEqualFold(FieldModelID, v))
}

// ModelIDContainsFold applies the ContainsFold predicate on the "model_id" field.
func ModelIDContainsFold(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldContainsFold(FieldModelID, v))
}

// DisplayNameEQ applies the EQ predicate on the "display_name" field.
func DisplayNameEQ(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldEQ(FieldDisplayName, v))
}

// DisplayNameNEQ applies the NEQ predicate on the "display_name" field.
func DisplayNameNEQ(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNEQ(FieldDisplayName, v))
}

// DisplayNameIn applies the In predicate on the "display_name" field.
func DisplayNameIn(vs ...string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldIn(FieldDisplayName, vs...))
}

// DisplayNameNotIn applies the NotIn predicate on the "display_name" field.
func DisplayNameNotIn(vs ...string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNotIn(FieldDisplayName, vs...))
}

// DisplayNameGT applies the GT predicate on the "display_name" field.
func DisplayNameGT(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldGT(FieldDisplayName, v))
}

// DisplayNameGTE applies the GTE predicate on the "display_name" field.
func DisplayNameGTE(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldGTE(FieldDisplayName, v))
}

// DisplayNameLT applies the LT predicate on the "display_name" field.
func DisplayNameLT(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldLT(FieldDisplayName, v))
}

// DisplayNameLTE applies the LTE predicate on the "display_name" field.
func DisplayNameLTE(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldLTE(FieldDisplayName, v))
}

// DisplayNameContains applies the Contains predicate on the "display_name" field.
func DisplayNameContains(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldContains(FieldDisplayName, v))
}

// DisplayNameHasPrefix applies the HasPrefix predicate on the "display_name" field.
func DisplayNameHasPrefix(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldHasPrefix(FieldDisplayName, v))
}

// DisplayNameHasSuffix applies the HasSuffix predicate on the "display_name" field.
func DisplayNameHasSuffix(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldHasSuffix(FieldDisplayName, v))
}

// DisplayNameEqualFold applies the EqualFold predicate on the "display_name" field.
func DisplayNameEqualFold(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldEqualFold(FieldDisplayName, v))
}

// DisplayNameContainsFold applies the ContainsFold predicate on the "display_name" field.
func DisplayNameContainsFold(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldContainsFold(FieldDisplayName, v))
}

// VendorEQ applies the EQ predicate on the "vendor" field.
func VendorEQ(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldEQ(FieldVendor, v))
}

// VendorNEQ applies the NEQ predicate on the "vendor" field.
func VendorNEQ(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNEQ(FieldVendor, v))
}

// VendorIn applies the In predicate on the "vendor" field.
func VendorIn(vs ...string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldIn(FieldVendor, vs...))
}

// VendorNotIn applies the NotIn predicate on the "vendor" field.
func VendorNotIn(vs ...string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNotIn(FieldVendor, vs...))
}

// VendorGT applies the GT predicate on the "vendor" field.
func VendorGT(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldGT(FieldVendor, v))
}

// VendorGTE applies the GTE predicate on the "vendor" field.
func VendorGTE(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldGTE(FieldVendor, v))
}

// VendorLT applies the LT predicate on the "vendor" field.
func VendorLT(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldLT(FieldVendor, v))
}

// VendorLTE applies the LTE predicate on the "vendor" field.
func VendorLTE(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldLTE(FieldVendor, v))
}

// VendorContains applies the Contains predicate on the "vendor" field.
func VendorContains(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldContains(FieldVendor, v))
}

// VendorHasPrefix applies the HasPrefix predicate on the "vendor" field.
func VendorHasPrefix(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldHasPrefix(FieldVendor, v))
}

// VendorHasSuffix applies the HasSuffix predicate on the "vendor" field.
func VendorHasSuffix(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldHasSuffix(FieldVendor, v))
}

// VendorEqualFold applies the EqualFold predicate on the "vendor" field.
func VendorEqualFold(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldEqualFold(FieldVendor, v))
}

// VendorContainsFold applies the ContainsFold predicate on the "vendor" field.
func VendorContainsFold(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldContainsFold(FieldVendor, v))
}

// ProtocolsIsNil applies the IsNil predicate on the "protocols" field.
func ProtocolsIsNil() predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldIsNull(FieldProtocols))
}

// ProtocolsNotNil applies the NotNil predicate on the "protocols" field.
func ProtocolsNotNil() predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNotNull(FieldProtocols))
}

// BillingModeEQ applies the EQ predicate on the "billing_mode" field.
func BillingModeEQ(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldEQ(FieldBillingMode, v))
}

// BillingModeNEQ applies the NEQ predicate on the "billing_mode" field.
func BillingModeNEQ(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNEQ(FieldBillingMode, v))
}

// BillingModeIn applies the In predicate on the "billing_mode" field.
func BillingModeIn(vs ...string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldIn(FieldBillingMode, vs...))
}

// BillingModeNotIn applies the NotIn predicate on the "billing_mode" field.
func BillingModeNotIn(vs ...string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNotIn(FieldBillingMode, vs...))
}

// BillingModeGT applies the GT predicate on the "billing_mode" field.
func BillingModeGT(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldGT(FieldBillingMode, v))
}

// BillingModeGTE applies the GTE predicate on the "billing_mode" field.
func BillingModeGTE(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldGTE(FieldBillingMode, v))
}

// BillingModeLT applies the LT predicate on the "billing_mode" field.
func BillingModeLT(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldLT(FieldBillingMode, v))
}

// BillingModeLTE applies the LTE predicate on the "billing_mode" field.
func BillingModeLTE(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldLTE(FieldBillingMode, v))
}

// BillingModeContains applies the Contains predicate on the "billing_mode" field.
func BillingModeContains(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldContains(FieldBillingMode, v))
}

// BillingModeHasPrefix applies the HasPrefix predicate on the "billing_mode" field.
func BillingModeHasPrefix(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldHasPrefix(FieldBillingMode, v))
}

// BillingModeHasSuffix applies the HasSuffix predicate on the "billing_mode" field.
func BillingModeHasSuffix(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldHasSuffix(FieldBillingMode, v))
}

// BillingModeEqualFold applies the EqualFold predicate on the "billing_mode" field.
func BillingModeEqualFold(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldEqualFold(FieldBillingMode, v))
}

// BillingModeContainsFold applies the ContainsFold predicate on the "billing_mode" field.
func BillingModeContainsFold(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldContainsFold(FieldBillingMode, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldContainsFold(FieldStatus, v))
}

// ManagedByEQ applies the EQ predicate on the "managed_by" field.
func ManagedByEQ(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldEQ(FieldManagedBy, v))
}

// ManagedByNEQ applies the NEQ predicate on the "managed_by" field.
func ManagedByNEQ(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNEQ(FieldManagedBy, v))
}

// ManagedByIn applies the In predicate on the "managed_by" field.
func ManagedByIn(vs ...string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldIn(FieldManagedBy, vs...))
}

// ManagedByNotIn applies the NotIn predicate on the "managed_by" field.
func ManagedByNotIn(vs ...string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNotIn(FieldManagedBy, vs...))
}

// ManagedByGT applies the GT predicate on the "managed_by" field.
func ManagedByGT(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldGT(FieldManagedBy, v))
}

// ManagedByGTE applies the GTE predicate on the "managed_by" field.
func ManagedByGTE(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldGTE(FieldManagedBy, v))
}

// ManagedByLT applies the LT predicate on the "managed_by" field.
func ManagedByLT(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldLT(FieldManagedBy, v))
}

// ManagedByLTE applies the LTE predicate on the "managed_by" field.
func ManagedByLTE(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldLTE(FieldManagedBy, v))
}

// ManagedByContains applies the Contains predicate on the "managed_by" field.
func ManagedByContains(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldContains(FieldManagedBy, v))
}

// ManagedByHasPrefix applies the HasPrefix predicate on the "managed_by" field.
func ManagedByHasPrefix(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldHasPrefix(FieldManagedBy, v))
}

// ManagedByHasSuffix applies the HasSuffix predicate on the "managed_by" field.
func ManagedByHasSuffix(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldHasSuffix(FieldManagedBy, v))
}

// ManagedByEqualFold applies the EqualFold predicate on the "managed_by" field.
func ManagedByEqualFold(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldEqualFold(FieldManagedBy, v))
}

// ManagedByContainsFold applies the ContainsFold predicate on the "managed_by" field.
func ManagedByContainsFold(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldContainsFold(FieldManagedBy, v))
}

// InputPriceEQ applies the EQ predicate on the "input_price" field.
func InputPriceEQ(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldEQ(FieldInputPrice, v))
}

// InputPriceNEQ applies the NEQ predicate on the "input_price" field.
func InputPriceNEQ(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNEQ(FieldInputPrice, v))
}

// InputPriceIn applies the In predicate on the "input_price" field.
func InputPriceIn(vs ...float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldIn(FieldInputPrice, vs...))
}

// InputPriceNotIn applies the NotIn predicate on the "input_price" field.
func InputPriceNotIn(vs ...float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNotIn(FieldInputPrice, vs...))
}

// InputPriceGT applies the GT predicate on the "input_price" field.
func InputPriceGT(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldGT(FieldInputPrice, v))
}

// InputPriceGTE applies the GTE predicate on the "input_price" field.
func InputPriceGTE(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldGTE(FieldInputPrice, v))
}

// InputPriceLT applies the LT predicate on the "input_price" field.
func InputPriceLT(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldLT(FieldInputPrice, v))
}

// InputPriceLTE applies the LTE predicate on the "input_price" field.
func InputPriceLTE(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldLTE(FieldInputPrice, v))
}

// InputPriceIsNil applies the IsNil predicate on the "input_price" field.
func InputPriceIsNil() predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldIsNull(FieldInputPrice))
}

// InputPriceNotNil applies the NotNil predicate on the "input_price" field.
func InputPriceNotNil() predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNotNull(FieldInputPrice))
}

// OutputPriceEQ applies the EQ predicate on the "output_price" field.
func OutputPriceEQ(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldEQ(FieldOutputPrice, v))
}

// OutputPriceNEQ applies the NEQ predicate on the "output_price" field.
func OutputPriceNEQ(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNEQ(FieldOutputPrice, v))
}

// OutputPriceIn applies the In predicate on the "output_price" field.
func OutputPriceIn(vs ...float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldIn(FieldOutputPrice, vs...))
}

// OutputPriceNotIn applies the NotIn predicate on the "output_price" field.
func OutputPriceNotIn(vs ...float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNotIn(FieldOutputPrice, vs...))
}

// OutputPriceGT applies the GT predicate on the "output_price" field.
func OutputPriceGT(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldGT(FieldOutputPrice, v))
}

// OutputPriceGTE applies the GTE predicate on the "output_price" field.
func OutputPriceGTE(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldGTE(FieldOutputPrice, v))
}

// OutputPriceLT applies the LT predicate on the "output_price" field.
func OutputPriceLT(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldLT(FieldOutputPrice, v))
}

// OutputPriceLTE applies the LTE predicate on the "output_price" field.
func OutputPriceLTE(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldLTE(FieldOutputPrice, v))
}

// OutputPriceIsNil applies the IsNil predicate on the "output_price" field.
func OutputPriceIsNil() predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldIsNull(FieldOutputPrice))
}

// OutputPriceNotNil applies the NotNil predicate on the "output_price" field.
func OutputPriceNotNil() predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNotNull(FieldOutputPrice))
}

// CacheWritePriceEQ applies the EQ predicate on the "cache_write_price" field.
func CacheWritePriceEQ(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldEQ(FieldCacheWritePrice, v))
}

// CacheWritePriceNEQ applies the NEQ predicate on the "cache_write_price" field.
func CacheWritePriceNEQ(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNEQ(FieldCacheWritePrice, v))
}

// CacheWritePriceIn applies the In predicate on the "cache_write_price" field.
func CacheWritePriceIn(vs ...float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldIn(FieldCacheWritePrice, vs...))
}

// CacheWritePriceNotIn applies the NotIn predicate on the "cache_write_price" field.
func CacheWritePriceNotIn(vs ...float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNotIn(FieldCacheWritePrice, vs...))
}

// CacheWritePriceGT applies the GT predicate on the "cache_write_price" field.
func CacheWritePriceGT(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldGT(FieldCacheWritePrice, v))
}

// CacheWritePriceGTE applies the GTE predicate on the "cache_write_price" field.
func CacheWritePriceGTE(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldGTE(FieldCacheWritePrice, v))
}

// CacheWritePriceLT applies the LT predicate on the "cache_write_price" field.
func CacheWritePriceLT(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldLT(FieldCacheWritePrice, v))
}

// CacheWritePriceLTE applies the LTE predicate on the "cache_write_price" field.
func CacheWritePriceLTE(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldLTE(FieldCacheWritePrice, v))
}

// CacheWritePriceIsNil applies the IsNil predicate on the "cache_write_price" field.
func CacheWritePriceIsNil() predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldIsNull(FieldCacheWritePrice))
}

// CacheWritePriceNotNil applies the NotNil predicate on the "cache_write_price" field.
func CacheWritePriceNotNil() predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNotNull(FieldCacheWritePrice))
}

// CacheWrite1hPriceEQ applies the EQ predicate on the "cache_write_1h_price" field.
func CacheWrite1hPriceEQ(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldEQ(FieldCacheWrite1hPrice, v))
}

// CacheWrite1hPriceNEQ applies the NEQ predicate on the "cache_write_1h_price" field.
func CacheWrite1hPriceNEQ(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNEQ(FieldCacheWrite1hPrice, v))
}

// CacheWrite1hPriceIn applies the In predicate on the "cache_write_1h_price" field.
func CacheWrite1hPriceIn(vs ...float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldIn(FieldCacheWrite1hPrice, vs...))
}

// CacheWrite1hPriceNotIn applies the NotIn predicate on the "cache_write_1h_price" field.
func CacheWrite1hPriceNotIn(vs ...float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNotIn(FieldCacheWrite1hPrice, vs...))
}

// CacheWrite1hPriceGT applies the GT predicate on the "cache_write_1h_price" field.
func CacheWrite1hPriceGT(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldGT(FieldCacheWrite1hPrice, v))
}

// CacheWrite1hPriceGTE applies the GTE predicate on the "cache_write_1h_price" field.
func CacheWrite1hPriceGTE(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldGTE(FieldCacheWrite1hPrice, v))
}

// CacheWrite1hPriceLT applies the LT predicate on the "cache_write_1h_price" field.
func CacheWrite1hPriceLT(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldLT(FieldCacheWrite1hPrice, v))
}

// CacheWrite1hPriceLTE applies the LTE predicate on the "cache_write_1h_price" field.
func CacheWrite1hPriceLTE(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldLTE(FieldCacheWrite1hPrice, v))
}

// CacheWrite1hPriceIsNil applies the IsNil predicate on the "cache_write_1h_price" field.
func CacheWrite1hPriceIsNil() predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldIsNull(FieldCacheWrite1hPrice))
}

// CacheWrite1hPriceNotNil applies the NotNil predicate on the "cache_write_1h_price" field.
func CacheWrite1hPriceNotNil() predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNotNull(FieldCacheWrite1hPrice))
}

// CacheReadPriceEQ applies the EQ predicate on the "cache_read_price" field.
func CacheReadPriceEQ(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldEQ(FieldCacheReadPrice, v))
}

// CacheReadPriceNEQ applies the NEQ predicate on the "cache_read_price" field.
func CacheReadPriceNEQ(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNEQ(FieldCacheReadPrice, v))
}

// CacheReadPriceIn applies the In predicate on the "cache_read_price" field.
func CacheReadPriceIn(vs ...float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldIn(FieldCacheReadPrice, vs...))
}

// CacheReadPriceNotIn applies the NotIn predicate on the "cache_read_price" field.
func CacheReadPriceNotIn(vs ...float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNotIn(FieldCacheReadPrice, vs...))
}

// CacheReadPriceGT applies the GT predicate on the "cache_read_price" field.
func CacheReadPriceGT(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldGT(FieldCacheReadPrice, v))
}

// CacheReadPriceGTE applies the GTE predicate on the "cache_read_price" field.
func CacheReadPriceGTE(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldGTE(FieldCacheReadPrice, v))
}

// CacheReadPriceLT applies the LT predicate on the "cache_read_price" field.
func CacheReadPriceLT(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldLT(FieldCacheReadPrice, v))
}

// CacheReadPriceLTE applies the LTE predicate on the "cache_read_price" field.
func CacheReadPriceLTE(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldLTE(FieldCacheReadPrice, v))
}

// CacheReadPriceIsNil applies the IsNil predicate on the "cache_read_price" field.
func CacheReadPriceIsNil() predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldIsNull(FieldCacheReadPrice))
}

// CacheReadPriceNotNil applies the NotNil predicate on the "cache_read_price" field.
func CacheReadPriceNotNil() predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNotNull(FieldCacheReadPrice))
}

// ImageInputPriceEQ applies the EQ predicate on the "image_input_price" field.
func ImageInputPriceEQ(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldEQ(FieldImageInputPrice, v))
}

// ImageInputPriceNEQ applies the NEQ predicate on the "image_input_price" field.
func ImageInputPriceNEQ(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNEQ(FieldImageInputPrice, v))
}

// ImageInputPriceIn applies the In predicate on the "image_input_price" field.
func ImageInputPriceIn(vs ...float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldIn(FieldImageInputPrice, vs...))
}

// ImageInputPriceNotIn applies the NotIn predicate on the "image_input_price" field.
func ImageInputPriceNotIn(vs ...float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNotIn(FieldImageInputPrice, vs...))
}

// ImageInputPriceGT applies the GT predicate on the "image_input_price" field.
func ImageInputPriceGT(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldGT(FieldImageInputPrice, v))
}

// ImageInputPriceGTE applies the GTE predicate on the "image_input_price" field.
func ImageInputPriceGTE(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldGTE(FieldImageInputPrice, v))
}

// ImageInputPriceLT applies the LT predicate on the "image_input_price" field.
func ImageInputPriceLT(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldLT(FieldImageInputPrice, v))
}

// ImageInputPriceLTE applies the LTE predicate on the "image_input_price" field.
func ImageInputPriceLTE(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldLTE(FieldImageInputPrice, v))
}

// ImageInputPriceIsNil applies the IsNil predicate on the "image_input_price" field.
func ImageInputPriceIsNil() predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldIsNull(FieldImageInputPrice))
}

// ImageInputPriceNotNil applies the NotNil predicate on the "image_input_price" field.
func ImageInputPriceNotNil() predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNotNull(FieldImageInputPrice))
}

// ImageOutputPriceEQ applies the EQ predicate on the "image_output_price" field.
func ImageOutputPriceEQ(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldEQ(FieldImageOutputPrice, v))
}

// ImageOutputPriceNEQ applies the NEQ predicate on the "image_output_price" field.
func ImageOutputPriceNEQ(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNEQ(FieldImageOutputPrice, v))
}

// ImageOutputPriceIn applies the In predicate on the "image_output_price" field.
func ImageOutputPriceIn(vs ...float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldIn(FieldImageOutputPrice, vs...))
}

// ImageOutputPriceNotIn applies the NotIn predicate on the "image_output_price" field.
func ImageOutputPriceNotIn(vs ...float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNotIn(FieldImageOutputPrice, vs...))
}

// ImageOutputPriceGT applies the GT predicate on the "image_output_price" field.
func ImageOutputPriceGT(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldGT(FieldImageOutputPrice, v))
}

// ImageOutputPriceGTE applies the GTE predicate on the "image_output_price" field.
func ImageOutputPriceGTE(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldGTE(FieldImageOutputPrice, v))
}

// ImageOutputPriceLT applies the LT predicate on the "image_output_price" field.
func ImageOutputPriceLT(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldLT(FieldImageOutputPrice, v))
}

// ImageOutputPriceLTE applies the LTE predicate on the "image_output_price" field.
func ImageOutputPriceLTE(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldLTE(FieldImageOutputPrice, v))
}

// ImageOutputPriceIsNil applies the IsNil predicate on the "image_output_price" field.
func ImageOutputPriceIsNil() predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldIsNull(FieldImageOutputPrice))
}

// ImageOutputPriceNotNil applies the NotNil predicate on the "image_output_price" field.
func ImageOutputPriceNotNil() predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNotNull(FieldImageOutputPrice))
}

// ImageCacheReadPriceEQ applies the EQ predicate on the "image_cache_read_price" field.
func ImageCacheReadPriceEQ(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldEQ(FieldImageCacheReadPrice, v))
}

// ImageCacheReadPriceNEQ applies the NEQ predicate on the "image_cache_read_price" field.
func ImageCacheReadPriceNEQ(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNEQ(FieldImageCacheReadPrice, v))
}

// ImageCacheReadPriceIn applies the In predicate on the "image_cache_read_price" field.
func ImageCacheReadPriceIn(vs ...float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldIn(FieldImageCacheReadPrice, vs...))
}

// ImageCacheReadPriceNotIn applies the NotIn predicate on the "image_cache_read_price" field.
func ImageCacheReadPriceNotIn(vs ...float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNotIn(FieldImageCacheReadPrice, vs...))
}

// ImageCacheReadPriceGT applies the GT predicate on the "image_cache_read_price" field.
func ImageCacheReadPriceGT(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldGT(FieldImageCacheReadPrice, v))
}

// ImageCacheReadPriceGTE applies the GTE predicate on the "image_cache_read_price" field.
func ImageCacheReadPriceGTE(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldGTE(FieldImageCacheReadPrice, v))
}

// ImageCacheReadPriceLT applies the LT predicate on the "image_cache_read_price" field.
func ImageCacheReadPriceLT(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldLT(FieldImageCacheReadPrice, v))
}

// ImageCacheReadPriceLTE applies the LTE predicate on the "image_cache_read_price" field.
func ImageCacheReadPriceLTE(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldLTE(FieldImageCacheReadPrice, v))
}

// ImageCacheReadPriceIsNil applies the IsNil predicate on the "image_cache_read_price" field.
func ImageCacheReadPriceIsNil() predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldIsNull(FieldImageCacheReadPrice))
}

// ImageCacheReadPriceNotNil applies the NotNil predicate on the "image_cache_read_price" field.
func ImageCacheReadPriceNotNil() predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNotNull(FieldImageCacheReadPrice))
}

// InputPricePriorityEQ applies the EQ predicate on the "input_price_priority" field.
func InputPricePriorityEQ(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldEQ(FieldInputPricePriority, v))
}

// InputPricePriorityNEQ applies the NEQ predicate on the "input_price_priority" field.
func InputPricePriorityNEQ(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNEQ(FieldInputPricePriority, v))
}

// InputPricePriorityIn applies the In predicate on the "input_price_priority" field.
func InputPricePriorityIn(vs ...float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldIn(FieldInputPricePriority, vs...))
}

// InputPricePriorityNotIn applies the NotIn predicate on the "input_price_priority" field.
func InputPricePriorityNotIn(vs ...float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNotIn(FieldInputPricePriority, vs...))
}

// InputPricePriorityGT applies the GT predicate on the "input_price_priority" field.
func InputPricePriorityGT(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldGT(FieldInputPricePriority, v))
}

// InputPricePriorityGTE applies the GTE predicate on the "input_price_priority" field.
func InputPricePriorityGTE(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldGTE(FieldInputPricePriority, v))
}

// InputPricePriorityLT applies the LT predicate on the "input_price_priority" field.
func InputPricePriorityLT(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldLT(FieldInputPricePriority, v))
}

// InputPricePriorityLTE applies the LTE predicate on the "input_price_priority" field.
func InputPricePriorityLTE(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldLTE(FieldInputPricePriority, v))
}

// InputPricePriorityIsNil applies the IsNil predicate on the "input_price_priority" field.
func InputPricePriorityIsNil() predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldIsNull(FieldInputPricePriority))
}

// InputPricePriorityNotNil applies the NotNil predicate on the "input_price_priority" field.
func InputPricePriorityNotNil() predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNotNull(FieldInputPricePriority))
}

// OutputPricePriorityEQ applies the EQ predicate on the "output_price_priority" field.
func OutputPricePriorityEQ(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldEQ(FieldOutputPricePriority, v))
}

// OutputPricePriorityNEQ applies the NEQ predicate on the "output_price_priority" field.
func OutputPricePriorityNEQ(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNEQ(FieldOutputPricePriority, v))
}

// OutputPricePriorityIn applies the In predicate on the "output_price_priority" field.
func OutputPricePriorityIn(vs ...float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldIn(FieldOutputPricePriority, vs...))
}

// OutputPricePriorityNotIn applies the NotIn predicate on the "output_price_priority" field.
func OutputPricePriorityNotIn(vs ...float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNotIn(FieldOutputPricePriority, vs...))
}

// OutputPricePriorityGT applies the GT predicate on the "output_price_priority" field.
func OutputPricePriorityGT(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldGT(FieldOutputPricePriority, v))
}

// OutputPricePriorityGTE applies the GTE predicate on the "output_price_priority" field.
func OutputPricePriorityGTE(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldGTE(FieldOutputPricePriority, v))
}

// OutputPricePriorityLT applies the LT predicate on the "output_price_priority" field.
func OutputPricePriorityLT(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldLT(FieldOutputPricePriority, v))
}

// OutputPricePriorityLTE applies the LTE predicate on the "output_price_priority" field.
func OutputPricePriorityLTE(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldLTE(FieldOutputPricePriority, v))
}

// OutputPricePriorityIsNil applies the IsNil predicate on the "output_price_priority" field.
func OutputPricePriorityIsNil() predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldIsNull(FieldOutputPricePriority))
}

// OutputPricePriorityNotNil applies the NotNil predicate on the "output_price_priority" field.
func OutputPricePriorityNotNil() predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNotNull(FieldOutputPricePriority))
}

// CacheWritePricePriorityEQ applies the EQ predicate on the "cache_write_price_priority" field.
func CacheWritePricePriorityEQ(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldEQ(FieldCacheWritePricePriority, v))
}

// CacheWritePricePriorityNEQ applies the NEQ predicate on the "cache_write_price_priority" field.
func CacheWritePricePriorityNEQ(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNEQ(FieldCacheWritePricePriority, v))
}

// CacheWritePricePriorityIn applies the In predicate on the "cache_write_price_priority" field.
func CacheWritePricePriorityIn(vs ...float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldIn(FieldCacheWritePricePriority, vs...))
}

// CacheWritePricePriorityNotIn applies the NotIn predicate on the "cache_write_price_priority" field.
func CacheWritePricePriorityNotIn(vs ...float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNotIn(FieldCacheWritePricePriority, vs...))
}

// CacheWritePricePriorityGT applies the GT predicate on the "cache_write_price_priority" field.
func CacheWritePricePriorityGT(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldGT(FieldCacheWritePricePriority, v))
}

// CacheWritePricePriorityGTE applies the GTE predicate on the "cache_write_price_priority" field.
func CacheWritePricePriorityGTE(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldGTE(FieldCacheWritePricePriority, v))
}

// CacheWritePricePriorityLT applies the LT predicate on the "cache_write_price_priority" field.
func CacheWritePricePriorityLT(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldLT(FieldCacheWritePricePriority, v))
}

// CacheWritePricePriorityLTE applies the LTE predicate on the "cache_write_price_priority" field.
func CacheWritePricePriorityLTE(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldLTE(FieldCacheWritePricePriority, v))
}

// CacheWritePricePriorityIsNil applies the IsNil predicate on the "cache_write_price_priority" field.
func CacheWritePricePriorityIsNil() predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldIsNull(FieldCacheWritePricePriority))
}

// CacheWritePricePriorityNotNil applies the NotNil predicate on the "cache_write_price_priority" field.
func CacheWritePricePriorityNotNil() predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNotNull(FieldCacheWritePricePriority))
}

// CacheReadPricePriorityEQ applies the EQ predicate on the "cache_read_price_priority" field.
func CacheReadPricePriorityEQ(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldEQ(FieldCacheReadPricePriority, v))
}

// CacheReadPricePriorityNEQ applies the NEQ predicate on the "cache_read_price_priority" field.
func CacheReadPricePriorityNEQ(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNEQ(FieldCacheReadPricePriority, v))
}

// CacheReadPricePriorityIn applies the In predicate on the "cache_read_price_priority" field.
func CacheReadPricePriorityIn(vs ...float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldIn(FieldCacheReadPricePriority, vs...))
}

// CacheReadPricePriorityNotIn applies the NotIn predicate on the "cache_read_price_priority" field.
func CacheReadPricePriorityNotIn(vs ...float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNotIn(FieldCacheReadPricePriority, vs...))
}

// CacheReadPricePriorityGT applies the GT predicate on the "cache_read_price_priority" field.
func CacheReadPricePriorityGT(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldGT(FieldCacheReadPricePriority, v))
}

// CacheReadPricePriorityGTE applies the GTE predicate on the "cache_read_price_priority" field.
func CacheReadPricePriorityGTE(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldGTE(FieldCacheReadPricePriority, v))
}

// CacheReadPricePriorityLT applies the LT predicate on the "cache_read_price_priority" field.
func CacheReadPricePriorityLT(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldLT(FieldCacheReadPricePriority, v))
}

// CacheReadPricePriorityLTE applies the LTE predicate on the "cache_read_price_priority" field.
func CacheReadPricePriorityLTE(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldLTE(FieldCacheReadPricePriority, v))
}

// CacheReadPricePriorityIsNil applies the IsNil predicate on the "cache_read_price_priority" field.
func CacheReadPricePriorityIsNil() predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldIsNull(FieldCacheReadPricePriority))
}

// CacheReadPricePriorityNotNil applies the NotNil predicate on the "cache_read_price_priority" field.
func CacheReadPricePriorityNotNil() predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNotNull(FieldCacheReadPricePriority))
}

// PerRequestPriceEQ applies the EQ predicate on the "per_request_price" field.
func PerRequestPriceEQ(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldEQ(FieldPerRequestPrice, v))
}

// PerRequestPriceNEQ applies the NEQ predicate on the "per_request_price" field.
func PerRequestPriceNEQ(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNEQ(FieldPerRequestPrice, v))
}

// PerRequestPriceIn applies the In predicate on the "per_request_price" field.
func PerRequestPriceIn(vs ...float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldIn(FieldPerRequestPrice, vs...))
}

// PerRequestPriceNotIn applies the NotIn predicate on the "per_request_price" field.
func PerRequestPriceNotIn(vs ...float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNotIn(FieldPerRequestPrice, vs...))
}

// PerRequestPriceGT applies the GT predicate on the "per_request_price" field.
func PerRequestPriceGT(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldGT(FieldPerRequestPrice, v))
}

// PerRequestPriceGTE applies the GTE predicate on the "per_request_price" field.
func PerRequestPriceGTE(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldGTE(FieldPerRequestPrice, v))
}

// PerRequestPriceLT applies the LT predicate on the "per_request_price" field.
func PerRequestPriceLT(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldLT(FieldPerRequestPrice, v))
}

// PerRequestPriceLTE applies the LTE predicate on the "per_request_price" field.
func PerRequestPriceLTE(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldLTE(FieldPerRequestPrice, v))
}

// PerRequestPriceIsNil applies the IsNil predicate on the "per_request_price" field.
func PerRequestPriceIsNil() predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldIsNull(FieldPerRequestPrice))
}

// PerRequestPriceNotNil applies the NotNil predicate on the "per_request_price" field.
func PerRequestPriceNotNil() predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNotNull(FieldPerRequestPrice))
}

// LongContextInputThresholdEQ applies the EQ predicate on the "long_context_input_threshold" field.
func LongContextInputThresholdEQ(v int) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldEQ(FieldLongContextInputThreshold, v))
}

// LongContextInputThresholdNEQ applies the NEQ predicate on the "long_context_input_threshold" field.
func LongContextInputThresholdNEQ(v int) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNEQ(FieldLongContextInputThreshold, v))
}

// LongContextInputThresholdIn applies the In predicate on the "long_context_input_threshold" field.
func LongContextInputThresholdIn(vs ...int) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldIn(FieldLongContextInputThreshold, vs...))
}

// LongContextInputThresholdNotIn applies the NotIn predicate on the "long_context_input_threshold" field.
func LongContextInputThresholdNotIn(vs ...int) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNotIn(FieldLongContextInputThreshold, vs...))
}

// LongContextInputThresholdGT applies the GT predicate on the "long_context_input_threshold" field.
func LongContextInputThresholdGT(v int) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldGT(FieldLongContextInputThreshold, v))
}

// LongContextInputThresholdGTE applies the GTE predicate on the "long_context_input_threshold" field.
func LongContextInputThresholdGTE(v int) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldGTE(FieldLongContextInputThreshold, v))
}

// LongContextInputThresholdLT applies the LT predicate on the "long_context_input_threshold" field.
func LongContextInputThresholdLT(v int) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldLT(FieldLongContextInputThreshold, v))
}

// LongContextInputThresholdLTE applies the LTE predicate on the "long_context_input_threshold" field.
func LongContextInputThresholdLTE(v int) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldLTE(FieldLongContextInputThreshold, v))
}

// LongContextInputThresholdIsNil applies the IsNil predicate on the "long_context_input_threshold" field.
func LongContextInputThresholdIsNil() predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldIsNull(FieldLongContextInputThreshold))
}

// LongContextInputThresholdNotNil applies the NotNil predicate on the "long_context_input_threshold" field.
func LongContextInputThresholdNotNil() predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNotNull(FieldLongContextInputThreshold))
}

// LongContextThresholdInclusiveEQ applies the EQ predicate on the "long_context_threshold_inclusive" field.
func LongContextThresholdInclusiveEQ(v bool) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldEQ(FieldLongContextThresholdInclusive, v))
}

// LongContextThresholdInclusiveNEQ applies the NEQ predicate on the "long_context_threshold_inclusive" field.
func LongContextThresholdInclusiveNEQ(v bool) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNEQ(FieldLongContextThresholdInclusive, v))
}

// LongContextInputMultiplierEQ applies the EQ predicate on the "long_context_input_multiplier" field.
func LongContextInputMultiplierEQ(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldEQ(FieldLongContextInputMultiplier, v))
}

// LongContextInputMultiplierNEQ applies the NEQ predicate on the "long_context_input_multiplier" field.
func LongContextInputMultiplierNEQ(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNEQ(FieldLongContextInputMultiplier, v))
}

// LongContextInputMultiplierIn applies the In predicate on the "long_context_input_multiplier" field.
func LongContextInputMultiplierIn(vs ...float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldIn(FieldLongContextInputMultiplier, vs...))
}

// LongContextInputMultiplierNotIn applies the NotIn predicate on the "long_context_input_multiplier" field.
func LongContextInputMultiplierNotIn(vs ...float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNotIn(FieldLongContextInputMultiplier, vs...))
}

// LongContextInputMultiplierGT applies the GT predicate on the "long_context_input_multiplier" field.
func LongContextInputMultiplierGT(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldGT(FieldLongContextInputMultiplier, v))
}

// LongContextInputMultiplierGTE applies the GTE predicate on the "long_context_input_multiplier" field.
func LongContextInputMultiplierGTE(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldGTE(FieldLongContextInputMultiplier, v))
}

// LongContextInputMultiplierLT applies the LT predicate on the "long_context_input_multiplier" field.
func LongContextInputMultiplierLT(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldLT(FieldLongContextInputMultiplier, v))
}

// LongContextInputMultiplierLTE applies the LTE predicate on the "long_context_input_multiplier" field.
func LongContextInputMultiplierLTE(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldLTE(FieldLongContextInputMultiplier, v))
}

// LongContextInputMultiplierIsNil applies the IsNil predicate on the "long_context_input_multiplier" field.
func LongContextInputMultiplierIsNil() predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldIsNull(FieldLongContextInputMultiplier))
}

// LongContextInputMultiplierNotNil applies the NotNil predicate on the "long_context_input_multiplier" field.
func LongContextInputMultiplierNotNil() predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNotNull(FieldLongContextInputMultiplier))
}

// LongContextOutputMultiplierEQ applies the EQ predicate on the "long_context_output_multiplier" field.
func LongContextOutputMultiplierEQ(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldEQ(FieldLongContextOutputMultiplier, v))
}

// LongContextOutputMultiplierNEQ applies the NEQ predicate on the "long_context_output_multiplier" field.
func LongContextOutputMultiplierNEQ(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNEQ(FieldLongContextOutputMultiplier, v))
}

// LongContextOutputMultiplierIn applies the In predicate on the "long_context_output_multiplier" field.
func LongContextOutputMultiplierIn(vs ...float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldIn(FieldLongContextOutputMultiplier, vs...))
}

// LongContextOutputMultiplierNotIn applies the NotIn predicate on the "long_context_output_multiplier" field.
func LongContextOutputMultiplierNotIn(vs ...float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNotIn(FieldLongContextOutputMultiplier, vs...))
}

// LongContextOutputMultiplierGT applies the GT predicate on the "long_context_output_multiplier" field.
func LongContextOutputMultiplierGT(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldGT(FieldLongContextOutputMultiplier, v))
}

// LongContextOutputMultiplierGTE applies the GTE predicate on the "long_context_output_multiplier" field.
func LongContextOutputMultiplierGTE(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldGTE(FieldLongContextOutputMultiplier, v))
}

// LongContextOutputMultiplierLT applies the LT predicate on the "long_context_output_multiplier" field.
func LongContextOutputMultiplierLT(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldLT(FieldLongContextOutputMultiplier, v))
}

// LongContextOutputMultiplierLTE applies the LTE predicate on the "long_context_output_multiplier" field.
func LongContextOutputMultiplierLTE(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldLTE(FieldLongContextOutputMultiplier, v))
}

// LongContextOutputMultiplierIsNil applies the IsNil predicate on the "long_context_output_multiplier" field.
func LongContextOutputMultiplierIsNil() predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldIsNull(FieldLongContextOutputMultiplier))
}

// LongContextOutputMultiplierNotNil applies the NotNil predicate on the "long_context_output_multiplier" field.
func LongContextOutputMultiplierNotNil() predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNotNull(FieldLongContextOutputMultiplier))
}

// FastMultiplierEQ applies the EQ predicate on the "fast_multiplier" field.
func FastMultiplierEQ(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldEQ(FieldFastMultiplier, v))
}

// FastMultiplierNEQ applies the NEQ predicate on the "fast_multiplier" field.
func FastMultiplierNEQ(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNEQ(FieldFastMultiplier, v))
}

// FastMultiplierIn applies the In predicate on the "fast_multiplier" field.
func FastMultiplierIn(vs ...float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldIn(FieldFastMultiplier, vs...))
}

// FastMultiplierNotIn applies the NotIn predicate on the "fast_multiplier" field.
func FastMultiplierNotIn(vs ...float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNotIn(FieldFastMultiplier, vs...))
}

// FastMultiplierGT applies the GT predicate on the "fast_multiplier" field.
func FastMultiplierGT(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldGT(FieldFastMultiplier, v))
}

// FastMultiplierGTE applies the GTE predicate on the "fast_multiplier" field.
func FastMultiplierGTE(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldGTE(FieldFastMultiplier, v))
}

// FastMultiplierLT applies the LT predicate on the "fast_multiplier" field.
func FastMultiplierLT(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldLT(FieldFastMultiplier, v))
}

// FastMultiplierLTE applies the LTE predicate on the "fast_multiplier" field.
func FastMultiplierLTE(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldLTE(FieldFastMultiplier, v))
}

// FastMultiplierIsNil applies the IsNil predicate on the "fast_multiplier" field.
func FastMultiplierIsNil() predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldIsNull(FieldFastMultiplier))
}

// FastMultiplierNotNil applies the NotNil predicate on the "fast_multiplier" field.
func FastMultiplierNotNil() predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNotNull(FieldFastMultiplier))
}

// FlexMultiplierEQ applies the EQ predicate on the "flex_multiplier" field.
func FlexMultiplierEQ(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldEQ(FieldFlexMultiplier, v))
}

// FlexMultiplierNEQ applies the NEQ predicate on the "flex_multiplier" field.
func FlexMultiplierNEQ(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNEQ(FieldFlexMultiplier, v))
}

// FlexMultiplierIn applies the In predicate on the "flex_multiplier" field.
func FlexMultiplierIn(vs ...float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldIn(FieldFlexMultiplier, vs...))
}

// FlexMultiplierNotIn applies the NotIn predicate on the "flex_multiplier" field.
func FlexMultiplierNotIn(vs ...float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNotIn(FieldFlexMultiplier, vs...))
}

// FlexMultiplierGT applies the GT predicate on the "flex_multiplier" field.
func FlexMultiplierGT(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldGT(FieldFlexMultiplier, v))
}

// FlexMultiplierGTE applies the GTE predicate on the "flex_multiplier" field.
func FlexMultiplierGTE(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldGTE(FieldFlexMultiplier, v))
}

// FlexMultiplierLT applies the LT predicate on the "flex_multiplier" field.
func FlexMultiplierLT(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldLT(FieldFlexMultiplier, v))
}

// FlexMultiplierLTE applies the LTE predicate on the "flex_multiplier" field.
func FlexMultiplierLTE(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldLTE(FieldFlexMultiplier, v))
}

// FlexMultiplierIsNil applies the IsNil predicate on the "flex_multiplier" field.
func FlexMultiplierIsNil() predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldIsNull(FieldFlexMultiplier))
}

// FlexMultiplierNotNil applies the NotNil predicate on the "flex_multiplier" field.
func FlexMultiplierNotNil() predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNotNull(FieldFlexMultiplier))
}

// MaxReasoningEffortMultiplierEQ applies the EQ predicate on the "max_reasoning_effort_multiplier" field.
func MaxReasoningEffortMultiplierEQ(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldEQ(FieldMaxReasoningEffortMultiplier, v))
}

// MaxReasoningEffortMultiplierNEQ applies the NEQ predicate on the "max_reasoning_effort_multiplier" field.
func MaxReasoningEffortMultiplierNEQ(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNEQ(FieldMaxReasoningEffortMultiplier, v))
}

// MaxReasoningEffortMultiplierIn applies the In predicate on the "max_reasoning_effort_multiplier" field.
func MaxReasoningEffortMultiplierIn(vs ...float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldIn(FieldMaxReasoningEffortMultiplier, vs...))
}

// MaxReasoningEffortMultiplierNotIn applies the NotIn predicate on the "max_reasoning_effort_multiplier" field.
func MaxReasoningEffortMultiplierNotIn(vs ...float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNotIn(FieldMaxReasoningEffortMultiplier, vs...))
}

// MaxReasoningEffortMultiplierGT applies the GT predicate on the "max_reasoning_effort_multiplier" field.
func MaxReasoningEffortMultiplierGT(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldGT(FieldMaxReasoningEffortMultiplier, v))
}

// MaxReasoningEffortMultiplierGTE applies the GTE predicate on the "max_reasoning_effort_multiplier" field.
func MaxReasoningEffortMultiplierGTE(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldGTE(FieldMaxReasoningEffortMultiplier, v))
}

// MaxReasoningEffortMultiplierLT applies the LT predicate on the "max_reasoning_effort_multiplier" field.
func MaxReasoningEffortMultiplierLT(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldLT(FieldMaxReasoningEffortMultiplier, v))
}

// MaxReasoningEffortMultiplierLTE applies the LTE predicate on the "max_reasoning_effort_multiplier" field.
func MaxReasoningEffortMultiplierLTE(v float64) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldLTE(FieldMaxReasoningEffortMultiplier, v))
}

// MaxReasoningEffortMultiplierIsNil applies the IsNil predicate on the "max_reasoning_effort_multiplier" field.
func MaxReasoningEffortMultiplierIsNil() predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldIsNull(FieldMaxReasoningEffortMultiplier))
}

// MaxReasoningEffortMultiplierNotNil applies the NotNil predicate on the "max_reasoning_effort_multiplier" field.
func MaxReasoningEffortMultiplierNotNil() predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNotNull(FieldMaxReasoningEffortMultiplier))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesIsNil applies the IsNil predicate on the "notes" field.
func NotesIsNil() predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldIsNull(FieldNotes))
}

// NotesNotNil applies the NotNil predicate on the "notes" field.
func NotesNotNil() predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldNotNull(FieldNotes))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.FieldContainsFold(FieldNotes, v))
}

// HasAccounts applies the HasEdge predicate on the "accounts" edge.
func HasAccounts() predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, AccountsTable, AccountsPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccountsWith applies the HasEdge predicate on the "accounts" edge with a given conditions (other predicates).
func HasAccountsWith(preds ...predicate.Account) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(func(s *sql.Selector) {
		step := newAccountsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasBindings applies the HasEdge predicate on the "bindings" edge.
func HasBindings() predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, BindingsTable, BindingsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBindingsWith applies the HasEdge predicate on the "bindings" edge with a given conditions (other predicates).
func HasBindingsWith(preds ...predicate.ModelCatalogBinding) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(func(s *sql.Selector) {
		step := newBindingsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ModelCatalogEntry) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ModelCatalogEntry) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ModelCatalogEntry) predicate.ModelCatalogEntry {
	return predicate.ModelCatalogEntry(sql.NotPredicates(p))
}
