// Code generated by ent, DO NOT EDIT.

package modelcatalogtimepricing

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the modelcatalogtimepricing type in the database.
	Label = "model_catalog_time_pricing"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldEntryID holds the string denoting the entry_id field in the database.
	FieldEntryID = "entry_id"
	// FieldTimezone holds the string denoting the timezone field in the database.
	FieldTimezone = "timezone"
	// FieldWeekdaysOnly holds the string denoting the weekdays_only field in the database.
	FieldWeekdaysOnly = "weekdays_only"
	// FieldPeriods holds the string denoting the periods field in the database.
	FieldPeriods = "periods"
	// Table holds the table name of the modelcatalogtimepricing in the database.
	Table = "model_catalog_time_pricing"
)

// Columns holds all SQL columns for modelcatalogtimepricing fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldEntryID,
	FieldTimezone,
	FieldWeekdaysOnly,
	FieldPeriods,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultTimezone holds the default value on creation for the "timezone" field.
	DefaultTimezone string
	// TimezoneValidator is a validator for the "timezone" field. It is called by the builders before save.
	TimezoneValidator func(string) error
	// DefaultWeekdaysOnly holds the default value on creation for the "weekdays_only" field.
	DefaultWeekdaysOnly bool
)

// OrderOption defines the ordering options for the ModelCatalogTimePricing queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByEntryID orders the results by the entry_id field.
func ByEntryID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEntryID, opts...).ToFunc()
}

// ByTimezone orders the results by the timezone field.
func ByTimezone(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTimezone, opts...).ToFunc()
}

// ByWeekdaysOnly orders the results by the weekdays_only field.
func ByWeekdaysOnly(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWeekdaysOnly, opts...).ToFunc()
}
