// Code generated by ent, DO NOT EDIT.

package modelcatalogpriceinterval

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the modelcatalogpriceinterval type in the database.
	Label = "model_catalog_price_interval"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldEntryID holds the string denoting the entry_id field in the database.
	FieldEntryID = "entry_id"
	// FieldMinTokens holds the string denoting the min_tokens field in the database.
	FieldMinTokens = "min_tokens"
	// FieldMaxTokens holds the string denoting the max_tokens field in the database.
	FieldMaxTokens = "max_tokens"
	// FieldTierLabel holds the string denoting the tier_label field in the database.
	FieldTierLabel = "tier_label"
	// FieldInputPrice holds the string denoting the input_price field in the database.
	FieldInputPrice = "input_price"
	// FieldOutputPrice holds the string denoting the output_price field in the database.
	FieldOutputPrice = "output_price"
	// FieldCacheWritePrice holds the string denoting the cache_write_price field in the database.
	FieldCacheWritePrice = "cache_write_price"
	// FieldCacheWrite1hPrice holds the string denoting the cache_write_1h_price field in the database.
	FieldCacheWrite1hPrice = "cache_write_1h_price"
	// FieldCacheReadPrice holds the string denoting the cache_read_price field in the database.
	FieldCacheReadPrice = "cache_read_price"
	// FieldPerRequestPrice holds the string denoting the per_request_price field in the database.
	FieldPerRequestPrice = "per_request_price"
	// FieldInputMultiplier holds the string denoting the input_multiplier field in the database.
	FieldInputMultiplier = "input_multiplier"
	// FieldOutputMultiplier holds the string denoting the output_multiplier field in the database.
	FieldOutputMultiplier = "output_multiplier"
	// FieldCacheWriteMultiplier holds the string denoting the cache_write_multiplier field in the database.
	FieldCacheWriteMultiplier = "cache_write_multiplier"
	// FieldCacheReadMultiplier holds the string denoting the cache_read_multiplier field in the database.
	FieldCacheReadMultiplier = "cache_read_multiplier"
	// FieldSortOrder holds the string denoting the sort_order field in the database.
	FieldSortOrder = "sort_order"
	// Table holds the table name of the modelcatalogpriceinterval in the database.
	Table = "model_catalog_price_intervals"
)

// Columns holds all SQL columns for modelcatalogpriceinterval fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldEntryID,
	FieldMinTokens,
	FieldMaxTokens,
	FieldTierLabel,
	FieldInputPrice,
	FieldOutputPrice,
	FieldCacheWritePrice,
	FieldCacheWrite1hPrice,
	FieldCacheReadPrice,
	FieldPerRequestPrice,
	FieldInputMultiplier,
	FieldOutputMultiplier,
	FieldCacheWriteMultiplier,
	FieldCacheReadMultiplier,
	FieldSortOrder,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultMinTokens holds the default value on creation for the "min_tokens" field.
	DefaultMinTokens int
	// DefaultTierLabel holds the default value on creation for the "tier_label" field.
	DefaultTierLabel string
	// TierLabelValidator is a validator for the "tier_label" field. It is called by the builders before save.
	TierLabelValidator func(string) error
	// DefaultSortOrder holds the default value on creation for the "sort_order" field.
	DefaultSortOrder int
)

// OrderOption defines the ordering options for the ModelCatalogPriceInterval queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByEntryID orders the results by the entry_id field.
func ByEntryID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEntryID, opts...).ToFunc()
}

// ByMinTokens orders the results by the min_tokens field.
func ByMinTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMinTokens, opts...).ToFunc()
}

// ByMaxTokens orders the results by the max_tokens field.
func ByMaxTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxTokens, opts...).ToFunc()
}

// ByTierLabel orders the results by the tier_label field.
func ByTierLabel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTierLabel, opts...).ToFunc()
}

// ByInputPrice orders the results by the input_price field.
func ByInputPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInputPrice, opts...).ToFunc()
}

// ByOutputPrice orders the results by the output_price field.
func ByOutputPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutputPrice, opts...).ToFunc()
}

// ByCacheWritePrice orders the results by the cache_write_price field.
func ByCacheWritePrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCacheWritePrice, opts...).ToFunc()
}

// ByCacheWrite1hPrice orders the results by the cache_write_1h_price field.
func ByCacheWrite1hPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCacheWrite1hPrice, opts...).ToFunc()
}

// ByCacheReadPrice orders the results by the cache_read_price field.
func ByCacheReadPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCacheReadPrice, opts...).ToFunc()
}

// ByPerRequestPrice orders the results by the per_request_price field.
func ByPerRequestPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPerRequestPrice, opts...).ToFunc()
}

// ByInputMultiplier orders the results by the input_multiplier field.
func ByInputMultiplier(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInputMultiplier, opts...).ToFunc()
}

// ByOutputMultiplier orders the results by the output_multiplier field.
func ByOutputMultiplier(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutputMultiplier, opts...).ToFunc()
}

// ByCacheWriteMultiplier orders the results by the cache_write_multiplier field.
func ByCacheWriteMultiplier(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCacheWriteMultiplier, opts...).ToFunc()
}

// ByCacheReadMultiplier orders the results by the cache_read_multiplier field.
func ByCacheReadMultiplier(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCacheReadMultiplier, opts...).ToFunc()
}

// BySortOrder orders the results by the sort_order field.
func BySortOrder(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSortOrder, opts...).ToFunc()
}
