// Code generated by ent, DO NOT EDIT.

package modelcatalogalias

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldEQ(FieldUpdatedAt, v))
}

// Alias applies equality check predicate on the "alias" field. It's identical to AliasEQ.
func Alias(v string) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldEQ(FieldAlias, v))
}

// EntryID applies equality check predicate on the "entry_id" field. It's identical to EntryIDEQ.
func EntryID(v int64) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldEQ(FieldEntryID, v))
}

// Source applies equality check predicate on the "source" field. It's identical to SourceEQ.
func Source(v string) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldEQ(FieldSource, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldEQ(FieldNotes, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldLTE(FieldUpdatedAt, v))
}

// AliasEQ applies the EQ predicate on the "alias" field.
func AliasEQ(v string) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldEQ(FieldAlias, v))
}

// AliasNEQ applies the NEQ predicate on the "alias" field.
func AliasNEQ(v string) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldNEQ(FieldAlias, v))
}

// AliasIn applies the In predicate on the "alias" field.
func AliasIn(vs ...string) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldIn(FieldAlias, vs...))
}

// AliasNotIn applies the NotIn predicate on the "alias" field.
func AliasNotIn(vs ...string) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldNotIn(FieldAlias, vs...))
}

// AliasGT applies the GT predicate on the "alias" field.
func AliasGT(v string) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldGT(FieldAlias, v))
}

// AliasGTE applies the GTE predicate on the "alias" field.
func AliasGTE(v string) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldGTE(FieldAlias, v))
}

// AliasLT applies the LT predicate on the "alias" field.
func AliasLT(v string) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldLT(FieldAlias, v))
}

// AliasLTE applies the LTE predicate on the "alias" field.
func AliasLTE(v string) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldLTE(FieldAlias, v))
}

// AliasContains applies the Contains predicate on the "alias" field.
func AliasContains(v string) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldContains(FieldAlias, v))
}

// AliasHasPrefix applies the HasPrefix predicate on the "alias" field.
func AliasHasPrefix(v string) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldHasPrefix(FieldAlias, v))
}

// AliasHasSuffix applies the HasSuffix predicate on the "alias" field.
func AliasHasSuffix(v string) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldHasSuffix(FieldAlias, v))
}

// AliasEqualFold applies the EqualFold predicate on the "alias" field.
func AliasEqualFold(v string) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldEqualFold(FieldAlias, v))
}

// AliasContainsFold applies the ContainsFold predicate on the "alias" field.
func AliasContainsFold(v string) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldContainsFold(FieldAlias, v))
}

// EntryIDEQ applies the EQ predicate on the "entry_id" field.
func EntryIDEQ(v int64) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldEQ(FieldEntryID, v))
}

// EntryIDNEQ applies the NEQ predicate on the "entry_id" field.
func EntryIDNEQ(v int64) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldNEQ(FieldEntryID, v))
}

// EntryIDIn applies the In predicate on the "entry_id" field.
func EntryIDIn(vs ...int64) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldIn(FieldEntryID, vs...))
}

// EntryIDNotIn applies the NotIn predicate on the "entry_id" field.
func EntryIDNotIn(vs ...int64) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldNotIn(FieldEntryID, vs...))
}

// EntryIDGT applies the GT predicate on the "entry_id" field.
func EntryIDGT(v int64) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldGT(FieldEntryID, v))
}

// EntryIDGTE applies the GTE predicate on the "entry_id" field.
func EntryIDGTE(v int64) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldGTE(FieldEntryID, v))
}

// EntryIDLT applies the LT predicate on the "entry_id" field.
func EntryIDLT(v int64) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldLT(FieldEntryID, v))
}

// EntryIDLTE applies the LTE predicate on the "entry_id" field.
func EntryIDLTE(v int64) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldLTE(FieldEntryID, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v string) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v string) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...string) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...string) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldNotIn(FieldSource, vs...))
}

// SourceGT applies the GT predicate on the "source" field.
func SourceGT(v string) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldGT(FieldSource, v))
}

// SourceGTE applies the GTE predicate on the "source" field.
func SourceGTE(v string) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldGTE(FieldSource, v))
}

// SourceLT applies the LT predicate on the "source" field.
func SourceLT(v string) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldLT(FieldSource, v))
}

// SourceLTE applies the LTE predicate on the "source" field.
func SourceLTE(v string) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldLTE(FieldSource, v))
}

// SourceContains applies the Contains predicate on the "source" field.
func SourceContains(v string) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldContains(FieldSource, v))
}

// SourceHasPrefix applies the HasPrefix predicate on the "source" field.
func SourceHasPrefix(v string) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldHasPrefix(FieldSource, v))
}

// SourceHasSuffix applies the HasSuffix predicate on the "source" field.
func SourceHasSuffix(v string) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldHasSuffix(FieldSource, v))
}

// SourceEqualFold applies the EqualFold predicate on the "source" field.
func SourceEqualFold(v string) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldEqualFold(FieldSource, v))
}

// SourceContainsFold applies the ContainsFold predicate on the "source" field.
func SourceContainsFold(v string) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldContainsFold(FieldSource, v))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesIsNil applies the IsNil predicate on the "notes" field.
func NotesIsNil() predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldIsNull(FieldNotes))
}

// NotesNotNil applies the NotNil predicate on the "notes" field.
func NotesNotNil() predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldNotNull(FieldNotes))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.FieldContainsFold(FieldNotes, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ModelCatalogAlias) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ModelCatalogAlias) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ModelCatalogAlias) predicate.ModelCatalogAlias {
	return predicate.ModelCatalogAlias(sql.NotPredicates(p))
}
